web-platform-tests/wpt.fyi

webapp/components/reftest-analyzer.js
webapp/templates/analyzer.html

Fixes #1264 
Also drive-by fixes the width when the error message is shown, and handling the spinner stopping onerror.

Use 1+2 keys for toggling before+after on /analyzer

---

util/cleanup-versions.sh

We're false-negativing on the existence of branches, which is killing our staging environments.

Fetch before cleanup

---

Makefile

`killall` is missing after docker image change in 0c53a3bcebbeac9280bd142986e14bce8ee2e8d1

Add psmisc dep

---

results-processor/.gitignore
results-processor/config.py
results-processor/mypy.ini
results-processor/requirements-top_level.txt
results-processor/requirements.txt
results-processor/tox.ini
results-processor/wptreport.py
results-processor/wptscreenshot.py

This adds mypy to results-processor. This doesn't actually quite work yet, though. `wptreport.py` almost passes; we could maybe just enable it for that first.

Start running mypy on results-processor

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Related to https://github.com/web-platform-tests/wpt/issues/16187
We still don't know the root cause of the WPT issue, but we can work
around it from the wpt.fyi side.
I will temporarily promote the staging deployment as the default processor and see if it's able to process the broken Edge runs in our backlog.

[processor] Strip whitespaces from test names

---

api/query/cache/index/index.go
api/query/cache/service/main.go
shared/logger.go
shared/util.go

We already have an nginx "parent" request log spanning the request's duration.
This PR creates a gcloud logging client, for which all entries are aggregated by the request that they belong to (by replicating its traceId).
To verify:
- Visit appengine logs for `GAE application > searchcache > logging`
- Run a request that will be logged, e.g. `curl -X POST -d '{"run_ids":[5418908555149312,6317650003099648,5797013731934208,6197500226568192],"query":{"exists":[{"contains":"shadowRoot"}]}}' https://logging-dot-searchcache-dot-wptdashboard-staging.appspot.com/api/search/cache`
- See the log, expand, see child logs including the error.
Caveat: If we use the existing "parent" log from nginx, we are not able to set an overarching status (of the most severe log level from the "child" logs).
The …

Implement logging via a gcloud client in flex contexts

---

results-processor/processor.py
results-processor/processor_test.py

when Azure artifact cannot be downloaded.
Simple change with tests without observable changes.

[processor] Fix an uncaught exception

---

util/cleanup-versions.sh

Travis by default uses `git clone --depth=50` which will affect all
future `git fetch` in this checkout. We need to explicitly add
`--unshallow` to make sure branches older than 50 commits ago can also
be fetched.
e.g. https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/195992237#L417
This job will later go on deleting `smaller` incorrectly.

Fix cleanup script by forcing an unshallow fetch

---

api/query/cache/service/main.go

This is a tiny fix to log the actual, useful information instead of an empty string.
I just happened to notice this when looking at logs.

[searchcache] Log the actual project ID

---

api/query/cache/index/go.mod

My visual Studio Code kept parsing go.mod and it leads to an older version of logrus that causes breakage.

Remove go.mod, which leads to an old version of logrus

---

api/taskcluster/webhook.go

Taskcluster webhook previously returns 500 when there is no finished
result in the run, which is a fairly common non-fatal error (when all
jobs are still running). Returning 500 pollutes the request log and
might cause GitHub to retry the webhook delivery.

Do not return 500 for a non-fatal error

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Treat it similar to "edge_webdriver" (i.e. consider it as Edge).
The product was added to WPT in
https://github.com/web-platform-tests/wpt/pull/16691 .

[processor] Support the new "edgechromium" product

---

webapp/views/wpt-app.js

Restore accidentally deleted PRs list feature. 
PRs list feature is accidentally deleted in PR,  #1295 
- Visit https://pr-list-dot-wptdashboard-staging.appspot.com/flags
- Enable the feature for listing PRs in directories
- Go to a test folder with open PRs, e.g.  /screen-capture

add prs back

---

webapp/views/wpt-results.js

"Cannot redefine computed property 'showTestRefURL'." -- we have a
feature flag called showTestRefURL so we cannot have another computed
property with the same name.
Also rename and fix showTestURL by the way (previously it had the
incorrect type Boolean).
Open the staging instance. There should be no warnings in the console.

Fix a console warning in the frontend

---

Makefile
util/docker-dev/run.sh
webapp/views/wpt-app.js

Fixes #1330. The root cause is described in details at https://github.com/web-platform-tests/wpt.fyi/issues/1330#issuecomment-497486923
This PR removes `sys_update` altogether, which is causing too much trouble. Moving forward, we do NOT support updating the dev Docker instance in place.
Along the way, I also found out some other hidden bugs in our `Makefile` that may cause trouble in the future:
1. Apparently, we misunderstood [*order-only prerequisites*](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html) in `Makefile`. They don't actually guarantee the execution order (to be before or after the other prerequisites). We need to use sub-make to ensure the order.
2. We have a silent name collision between `gcloud-login` and `gcloud-%` whose behaviour depends on the …

Fix `npm install` in Docker

---

.travis.yml

This reverts commit 597415ca0a08313e26226286a326a0d1046898ca.
Turns out it's not related to #1330 .

Revert "Disable puppeterr_chrome_test"

---

webapp/app.yaml
webapp/components_handler.go
webapp/interop_handler.go
webapp/service-worker-uninstaller.js
webapp/templates/_head_common.html
webapp/test_results_handler.go
webapp/test_results_handler_medium_test.go

The main purpose of this PR is to improve the page load speed without (re)enabling the service worker (since we still have some cache invalidation bugs in our SW).
This is done via two approaches:
* Enable caching for `node_modules`.
* Do not load `service-worker-installer.js` if service worker isn't enabled (this saves both two unnecessary script loads and a console error).
Review the two commits separately. The second commit contains a refactor (renaming) of a private struct (as well as the function that populates it) to better reflect its meaning.
Open the staging instance. You shouldn't see any network errors in the console.

Improve caching for npm packages and hide SW installer behind a flag

---

shared/util.go

The name doesn't imply that it will return nil, and it lead to a nil-pointer bug.

Always return a non-nil set for NewSetFromStringSlice

---

.travis.yml
Dockerfile
api/query/cache/service/Dockerfile
revisions/service/Dockerfile

* Xenial is the new default on Travis: https://docs.travis-ci.com/user/reference/overview/#linux
* Upgrade to the latest stable version of go: 1.12 (from 1.11).
Changes are trivial. There shouldn't be any observable changes and tests should continue to pass.

Upgrade distro on Travis and go version in Docker

---

api/azure/api_test.go
api/azure/notify.go
api/checks/api.go
api/checks/webhook.go
api/checks/webhook_test.go
api/manifest/api.go
api/taskcluster/api.go
api/taskcluster/mock_taskcluster/api_mock.go
api/taskcluster/webhook.go
api/test_runs.go
shared/run_diff.go
shared/util.go

Handles master-branch cases, where we have multiple shards that need to be grouped (by waiting until all shards are completed).
Fixes one of the many issues in https://github.com/web-platform-tests/wpt.fyi/issues/1240

Respond to completed CheckSuiteEvent from Taskcluster

---

webapp/components/reftest-analyzer.js
webapp/components/test/fixtures/interop.json
webapp/components/test/test-runs-query-builder.html
webapp/components/test/wpt-interop.html
webapp/package-lock.json
webapp/package.json
webapp/wct.conf.json

There is a multitude of problems that lead to flaky web components test. This PR addresses all of the issues I can find but is not guaranteed to solve the problem (only to alleviate it).
1. Some network fetches aren't always intercepted, which would cause flaky failures. Looking at the devtools, I've identified two cases:
a) `test-runs-query-builder.html` stubs and restores `window.fetch` at the test level (`setup` and `teardown`). However, the query builder issues API requests after it becomes ready, which might happen after the test finishes, in which case the fetches would slip through. This is fixed by setting up the stub at the suite level (`suiteSetup` and `suiteTeardown`).
b) `wpt-interop.html` has the same issue. In addition, its URL matching is incorrect: in one case, a pathname …

Attempt to fix WCT

---

webapp/views/wpt-app.js

This is a trivial fix for a recent regression to make the top path copy-pastable again.

Remove whitespaces between path components

---

webapp/components/abstract-test-file-results-table.js
webapp/components/reftest-analyzer.js
webapp/components/test-file-results-table-terse.js
webapp/components/test-file-results.js
webapp/components/test/test-file-results.html
webapp/views/wpt-results.js

See individual commits -- fixes #1339 and #1340 respectively.
Demo: https://analzyer-button-dot-wptdashboard-staging.appspot.com/results/css/css-fill-stroke/paint-order-001.tentative.html?label=master&label=experimental
Try the new COMPARE button, as well as the "go back" button in the reftest analyzer.

Improve buttons for reftest-analzyer

---

shared/run_diff.go
shared/run_diff_test.go

Bug caused in #1302 
Diff field is omitted when empty, and we should handle unitialized `RunDiff` int arrays with the counting methods.
Added the test (failing) first, then fixed the bug.

Fix bug with nil diffs

---

webapp/components/test-runs.js
webapp/components/test/test-run.html
webapp/components/test/test-runs.html
webapp/components/wpt-permalinks.js
webapp/views/wpt-app.js

Fixes #1350 .
Check the staging deployment. Click on the "LINK" button near the top and the pop-up dialog should include run IDs. Then close the dialog and switch to interop. The LINK button should still work. The dialog should show **interop** instead of results, and the run IDs should still be there.
The first commit is a no-op cleanup (of tests, mostly), while the second commit is the actual fix.

Fix permalinks

---

api/checks/update.go
api/checks/update_test.go
webapp/components/wpt-flags.js

Should help with https://github.com/web-platform-tests/wpt.fyi/issues/1300
Changes the checks API to fetch the diff twice, with only `filter=C` the second time. The latter fetch is used when counting regressions, while the full diff is used for the summary text.

Add feature for changes-only regression detection

---

api/query/cache/service/main.go
api/query/search.go

Switches some trivial code to use a shared library method.
Changes the behaviour for `?diff=false` to correctly match diff not being present at all.

Parse boolean params, not just presence

---

api/checks/webhook.go
api/checks/webhook_test.go

Adding a "wpt.fyi - " prefix (https://github.com/web-platform-tests/wpt.fyi/pull/1148, I think?) broke the recompute action.
This PR adds a test for `recompute`, and covers prefixed names for the `ignore` action test too.

Fix recompute action

---

shared/run_diff.go
shared/run_diff_test.go

Fixes a bug from #1302 - the summaries weren't populated from the `SearchResults` format, which produces an empty CheckRun report.

Populate diff summaries from SearchResults

---

api/checks/summaries/completed.go

Add the recompute action to success outcomes. 
Occassionally we will have false-positive bugs, or bugs in the reporting for a positive outcome, and this allows us to trivially check the fixes.

Allow recompute on success

---

webapp/components/test/wpt-app.html
webapp/components/test/wpt-results.html
webapp/views/wpt-app.js
webapp/views/wpt-results.js

It got dropped in the migration to `wpt-app`. The `N tests (M subtests) from` message is being computed, but on the nest `wpt-results` class, which is not what we're using to populate the banner.

Restore the test counts message when viewing results

---

results-processor/processor.py
results-processor/wptreport.py

Currently when results from Azure Pipelines are abnormal, we will see
empty source URLs in the logs (e.g. "Conflicting 'browser_version' found
in the merged report ([])"). This change fixes the problem.

[processor] Improve logging for Azure Pipelines

---

webapp/components/self-navigator.js
webapp/views/wpt-results.js

Broken in https://github.com/web-platform-tests/wpt.fyi/pull/1295, which highlighted a weird mismatch of the `pathIsASubfolder` property.
This refactors the old `SelfNavigator` (still used) to re-use the `PathInfo` mixin to avoid that issue in future.

Bring back history button

---

api/test_runs.go
shared/product_spec.go
shared/test_run_filter.go
shared/test_run_query.go
shared/test_run_query_medium_test.go

Fixes the underlying cause of datastore timeouts, which in turn fixes https://github.com/web-platform-tests/wpt.fyi/issues/973
Example that is timing out: https://wpt.fyi/api/runs?pr=17560
(And its corresponding fix: https://runs-by-pr-dot-wptdashboard-staging.appspot.com/api/runs?pr=17560)

Fetch any/all matching product keys in a single datastore lookup

---

webapp/components/test-file-results-table.js
webapp/components/test-file-results.js
webapp/views/wpt-results.js

Includes the diff column in the single-file view, so that really large tests (e.g. /html/dom/interfaces.https.html) can be filtered when diffing.

Show diff + filtering on single file views

---

shared/run_diff.go

Gives more insight into why the UI might fail to consolidate renamed results

Log the number of renames found

---

api/checks/summaries/_pr_and_master_specs.md
api/checks/summaries/compile_test.go
api/checks/summaries/completed.go
api/checks/summaries/completed.md
api/checks/summaries/regressed.go
api/checks/summaries/regressed.md
api/checks/update.go
api/checks/update_test.go

Currently we only show the "After", which is based on the premise that newly-failing tests would be considered regressing. Now, however, only existing passes that change to failure are considered regressions, so we should show before and after in all cases (in case new tests exist).

Show before and after in non-regressing check summaries

---

api/test_runs_medium_test.go

We sort test runs by TimeStart, not by CreatedAt. The dummy data only
set CreatedAt but left TimeStart empty, which led to nondeterministic
ordering. This change fixes #1403 by setting TimeStart instead.

Fix flaky TestGetTestRuns_VersionPrefix

---

webapp/package-lock.json
webapp/package.json

A simple `npm update --depth 9999` to address some security warnings. Tests should continue to pass.

npm update

---

webapp/components/results-navigation.js
webapp/views/wpt-app.js

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1375
Additionally fixes a bug with the search field not updating when navigating back/forward with the browser.
Our use of URLSearchParams causes spaces to become '+' (unnecessarily), which are further encoded by the `app-location` Polymer component. On the way back out, we don't undo the problem.
The fix in this PR ties into the hack for param cleanup and undo the + conversion, resulting in an unambiguous %20 encoding (which decodes back to a space correctly).
- Visit the deployed environment, run a search containing a space. (e.g. `firefox:pass chrome:fail`)
- Change the query (e.g. `firefox:pass chrome:fail safari:pass`)
- Hit the back button
- See previous query in search box, spaces as were (no unexpected +).
- Reload the …

Fix bad decoding of space -> + -> %2B

---

webapp/components/wpt-insights.js

Avoids showing empty PR results some of the time.

Include master label for anomalies insight

---

webapp/components/path.js
webapp/views/wpt-app.js
webapp/views/wpt-interop.js
webapp/views/wpt-results.js

When N is pressed on the document body, finds the next full test path that isn't the current path, or the first test path, and navigates to it.
Feature kinda requested in #1421. We can build off the keycodes and add "expand" shorthands in a follow-up PR.
Head to the deployed env and try it.
Please make sure to test the interop view's behaviour works too; hard to test locally.

Move to next + prev individual test when n + p are pressed

---

api/receiver/api.go
api/receiver/api_medium_test.go
api/receiver/create_run.go
api/receiver/create_run_test.go
api/receiver/mock_receiver/api_mock.go
shared/datastore.go
shared/datastore_ae.go
shared/datastore_cloud.go
shared/models.go
shared/sharedtest/datastore_mock.go
webapp/admin_handler.go
webapp/admin_handler_test.go
webapp/templates/admin_upload.html

Design doc: https://docs.google.com/document/d/125dg-NST0xnEVqN7a-LrfGxPueSwXvDukAjOM8n5q50/
You can use https://lifecycle-dot-wptdashboard-staging.appspot.com/api/results/upload to upload a run, and check the `PendingTestRun` table in Datastore to see the new run going through WPTFYI_RECEIVED to VALID. I already did a manual integration test of the flow.
See each commit title. Changes are split into logical commits, so it might be easier to review by commits.

[lifecycle] Basic data models & WPTFYI_RECEIVED/VALID stages

---

webapp/components/path.js
webapp/components/test/path.html
webapp/views/wpt-app.js
webapp/views/wpt-interop.js
webapp/views/wpt-results.js

Fixes #1430 
We were naively splitting on slashes, and in the case that a slash appears (unencoded) in a URI's query params (for tests using `variant` metadata), we see the UI behave badly.
- Visit the auto-deployed environment
- Navigate to the webgpu test folder
- You should see some valid test names. cts.html has these variants:
- ?q=cts:buffers/create_mapped:
- ?q=cts:buffers/map:
- ?q=cts:buffers/map_detach:
- ?q=cts:buffers/map_oom:
- ?q=cts:canvas/context_creation:
- ?q=cts:command_buffer/basic:
- ?q=cts:command_buffer/compute/basic:
- ?q=cts:command_buffer/copies:
- ?q=cts:command_buffer/render/basic:
- ?q=cts:command_buffer/render/rendering:
- ?q=cts:examples:
- ?q=cts:fences:

Fix treatment of slashes in testname query params

---

api/pending_test_runs.go
api/pending_test_runs_medium_test.go
api/routes.go
webapp/routes_test.go

Adds api endpoint for `/api/status` to fetch all pending runs.
See https://api-pending-runs-dot-wptdashboard-staging.appspot.com/api/status

Add endpoint for fetching pending test runs

---

api/receiver/handlers.go
api/receiver/update_pending_run.go
api/receiver/update_pending_run_test.go
results-processor/processor.py
results-processor/processor_test.py
shared/models.go

Previously in https://github.com/web-platform-tests/wpt.fyi/pull/1437 ,
pending test runs wouldn't be updated if they were empty or duplicate
(i.e. they would remain in WPTFYI_PROCESSING forever). This change
handles the two missed edge cases by adding two stages to the enum and
setting them accordingly.
In addition, a few unit tests are added for better coverage.

Handle EMPTY and DUPLICATE results

---

webapp/components/test-search.js
webapp/views/wpt-app.js
webapp/views/wpt-results.js

Fixes #1443
`testPaths` wasn't propagated correctly; and `subroute` wasn't observed correctly.
Go to the staging instance and play with autocomplete.

Fix path autocomplete in the search bar

---

util/deploy-comment.sh
util/travis-deploy-staging.sh

Fix a couple of problems with #1453 which weren't caught until it hit master.
- `$APP_PATH` wasn't forwarded from the parent script; make it an `$ENVIRONMENT` param on the comment script.
- Fail out when the create POST fails
- Clear out the `required_contexts` so that running from travis isn't blocked by travis being unfinished.

Fix the environment name for GitHub deployments API calls

---

api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/concrete_query.go
webapp/components/test-search.js
webapp/components/test/test-search.html

Fixes #1460 
Adds handling of `is:different` atom, which will return true for rows where the size/cardinality of the set of result statuses is not 1.
- Search for is:different
- See only rows that have differing values.
- Try queries with 2, 3, and 4 runs, ensure behaves as expected.

Add structured search atom for filtering by results that differ

---

webapp/routes.go

Change the route from /processor to /status.
The "Processor" tab should now work.

Fix the processor status route

---

api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
webapp/components/test-search.js
webapp/components/test/test-search.html

Fixes #1467 
Adds root query options for `all` and `none` (instead of the default, `exists`).
Strangely, `count` and `seq` get wrapped in `exists`. I started to tweak that behaviour, but decided against busying up the PR. Will clean that up another time.

Add all/none root queries

---

api/pending_test_runs.go
api/pending_test_runs_medium_test.go
api/routes.go
webapp/components/wpt-processor.js
webapp/routes_test.go

API /api/status/invalid returns a list of invalid runs.
A tab bar is added to the /status interface to switch between pending
and invalid runs.
Go to the "processor" page (`/status`) of the staging deployment.

Add an API and UI for showing invalid runs

---

results-processor/processor.py

Whenever the full revision hash is available, we will report it to
/api/status/{id} to update the pending test run, so pending test runs
will almost always have revisions attached, making it easier to debug
problems.

[processor] Report revisions for invalid runs

---

.travis.yml
Makefile
results-processor/Dockerfile
results-processor/README.md
results-processor/tox.ini

Python 3.7 is the current stable version of Python 3 and is included in
Debian Stable, i.e. almost everywhere including our workstations and
Docker images.
3.7 is backward compatible with 3.6 and everything should just work.
If tests pass and staging is deployed, then we should be good.

Upgrade results-processor to Python 3.7

---

webapp/package-lock.json
webapp/package.json

The CLI flag --browser is deprecated.
Upgrade NPM packages by the way.
This is a rather trivial change: a one-liner except `npm up`.

Fix wct: use --local instead of --browser

---

webapp/views/wpt-results.js

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1461 which relies on sorted results.
- view /results/?diff&filter=ADC&run_id=257090008&run_id=231180012
- Smash the n key many times

Sort results when they arrive

---

webapp/components/test-file-results-table.js

Fixes #1472 
- View deployed environment
- See `notifications/constructor-basic.html` with `NOTRUN`
- Smile, and hi-five the person adjacent.

Use status, not FAIL, for terse messages

---

api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/concrete_query.go
webapp/components/test-search.js
webapp/components/test/test-search.html

Fixes #1496 
Adds `count<2([query])` style inequality count atoms to the structured search.

Add inequality atoms

---

results-processor/wptreport.py
results-processor/wptreport_test.py
shared/browsers.go
shared/browsers_test.go

This adds `webkitgtk` as a known browser. We want to start sending reports with runs of this browser to staging.wpt.fyi
The product from the wptreport is `webkitgtk_minibrowser`, which is normalized to `webkitgtk`
For related pull-request adding this browser to wpt see https://github.com/web-platform-tests/wpt/pull/19227
// cc @foolip

Add webkitgtk as a known browser:

---

api/query/autocomplete.go
api/query/autocomplete_medium_test.go
api/query/autocomplete_test.go
webapp/components/path.js
webapp/components/test-search.js
webapp/views/wpt-app.js
webapp/views/wpt-results.js
webdriver/path_test.go
webdriver/search_test.go

Changes the displayed row to explode out its contents when there's only one row, and it's a directory.
I did this to cover the behaviour of submitting a search which has results under some unique folder, because it also covers the general case of clicking/navigating down into a state with the same context (a single directory).
Additionally, contributes each separate folder of a test path as possible autocomplete suggestions, so that we can leverage the jump-on-autocomplete behaviour to achieve a different solution of the same issue.
- Head to the GitHub deployed environment
- Search for `web-animations/animation-model`
- See three rows, each of which is an exploded path nested under web-animations/animation-model

Explode folder contents in UI and collapse folders in autocomplete suggestions

---

api/query/README.md
webapp/components/test-search.js
webapp/components/test/test-search.html

Fixes #1510 
Allows an optional `:` after the `count` in the search syntax, which supports the same format as the GitHub inequality atoms.
- Visit deployed environment
- Search for `count:>3(status:pass)`
- See expected result.

Allow optional : in count inequalities

---

api/query/README.md
webapp/components/test-search.js
webapp/components/test/test-search.html

Follow-up for https://github.com/web-platform-tests/wpt.fyi/pull/1500 to fix #1507 
- Search for `all(status:pass) or none(status:pass)`
- See expected results

Support or-conjunction for root queries

---

webapp/components/test/wpt-app.html
webapp/views/wpt-app.js

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1455
Factor in the current path when computing the summary message. Also omits the test count when looking at a folder with just one test, or a single file (always 1 test), and the subtest count when there's exactly one subtest.
- Navigate around, verify that the message is sensible.

Update counts on path change

---

webapp/components/wpt-insights.js

Suggested in #1499 
Adds passing to the builder for anomaly query, for seeing solo-pass results.

Support browser-specific pass anomaly in insights

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
webapp/app.yaml

As part of [bug 1574668](https://bugzilla.mozilla.org/show_bug.cgi?id=1574668) we will need the ability to easily switch from one TC deployment to another.  
I modified the existing tests to suit, but nothing tests `getTaskGroupInfo`.  In fact, in its existing incarnation it was incorrect and would under-report tasks in large task groups since it did not use continuation tokens.  I think "large" means over 1000 tasks, but depending on the details of the Azure tables backend, could be smaller than that.
Deployments are identified by TASKCLUSTER_ROOT_URL.  So this PR modifies the TC webhook listener to use the TC client and taskcluster-lib-urls to query task groups and generate URLs, based on this env var.
Note that with this change, the API server must be run with `TASKCLUSTER_ROOT_URL` …

Bug 1574668 - use the Taskcluster client and taskcluster-lib-urls

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
go.mod

* `go get -u all` mainly to get taskcluster/client-go v19
* Fixed the expected Go version to match GAE runtime
* Removed unnecessary redirects
* `go mod tidy` to remove unused requires

Update go deps

---

Makefile
util/deploy.sh
util/docker-dev/web_server.sh

Ensures that the webapp/node_modules are pruned before we run `go generate`, which packs all the contents into the build (8MB when correct, >150MB when including web_component_tester deps).

Rejig go_build to prune webapp's node_modules

---

webapp/web/app.dev.yaml
webapp/web/app.yaml

- Visit the deployed environment's `/flags` endpoint
- See some client-side features are enabled (as per their environment defaults).

Exclude wpt-env-flags in /components/ regex

---

webapp/components/wpt-flags.js
webapp/views/wpt-app.js
webapp/views/wpt-results.js

The deployment formally available at web-platform-tests.live is now
hosted at wpt.live. Update references accordingly.

Update references to "live" deployment

---

shared/product_spec.go
webapp/components/product-info.js
webapp/components/test/test-run.html

* The minor version of WebKitGTK is significant: wpt.fyi should display `2.26` instead of `2`.
* Also the product name should be capitalized as WebKitGTK.
/cc @foolip

webkitgtk: capitalize the name and show minor version as significant.

---

webapp/components/wpt-flags.js
webapp/views/wpt-app.js
webapp/views/wpt-results.js

Reverts web-platform-tests/wpt.fyi#1531
(Re-land when `wpt.live` is actually live.)

Revert "Update references to "live" deployment"

---

webapp/components/display-logo.js

`replace` return a new string, so this didn't do anything.

Remove broken code to handle '-experimental' in product

---

go.mod
go.sum
shared/metadata.go

Use its canonical module path (gopkg.in/yaml.v2) as per its README
(https://github.com/go-yaml/yaml) to remove the "incompatible" tag and
dedupe deps.
`go.sum` changes are mechanical (from running `go mod tidy`).

Fix go-yaml dependency

---

renovate.json

The config added in https://github.com/web-platform-tests/wpt.fyi/pull/1548 leaves webdriver/package.json and webapp/package.json unmanaged. This *might* fix that.

Let Renovate bump node dependencies as well

---

.travis.yml

Now that we run all of our critical tests on GitHub Actions, which is
faster and more reliable than Travis, we can remove them from Travis to
make Travis finish faster (so that PRs don't get stuck in pending status
for that long).
We still run deployment and cleanup jobs on Travis. This commit also
cleans up the remaining job definitions a bit:
1. Upgrade from Ubuntu Xenial (16.04 LTS) to Bionic (18.04 LTS).
2. Change the deprecated keyword `matrix` to `jobs`.
3. Use conditional stages to simplify job definitions.
4. Run the cleanup job in a different stage to prevent race conditions.
5. Allow experimental Puppeteer tests to fail.
Check Travis. We should only see a Puppeteer job.
Unfortunately we need to merge it to master to test the remaining job definitions, but it's trivial to …

Clean up Travis configurations

---

.github/actions/make-in-docker/action.yml
.github/workflows/docker-update.yml

The official GitHub Action for interacting with Docker has been
deprecated and deleted (it used the alpha syntax), so we are switching
to a community-built action:
https://github.com/elgohr/Publish-Docker-Github-Action
Also switch from my personal account to a dedicated bot account with a
personal access token.
* Demo autobuild: https://github.com/web-platform-tests/wpt.fyi/pull/1561/checks?check_run_id=269028969
* Demo checks using the image built from this branch: https://github.com/web-platform-tests/wpt.fyi/pull/1561/checks?check_run_id=269028995
(The test commit will be reverted before merging.)

Fix Docker autobuild

---

renovate.json

Renovate does not support rewriting import paths yet. Simply changing
`go.mod` is pointless.
https://github.com/renovatebot/renovate/issues/3627
Also disable auto merge because Renovate can't auto merge when there is
branch protection (required review) in place.

Disable major upgrades for Golang

---

util/commands.sh

When the group already exists within Docker (e.g. on a macOS host where the
default user GID is 20), we won't create the "user" group in Docker, but we
always create a new user called "user", so using username ("user") instead
of groupname ("%user") in /etc/sudoers will work in both cases.
Fixes #1591 .
We don't have automated tests on macOS; I've tested locally.
Travis should still pass (which means this new setup would still work on Linux).

User username instead of groupname in sudoers

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

Sample URL from a real webhook payload:
https://tools.taskcluster.net/groups/VFI9FCVDTLW5rkvwdyM_yQ
May fix https://github.com/web-platform-tests/wpt.fyi/issues/1598.

Drop the /tasks/ part of the expected `target_url` for Taskcluster

---

webapp/components/wpt-header.js
webapp/templates/about.html

Previously it seemed like wpt.fyi was the one repo for both running and
serving the tests. Split that section into two.

[UI] Clarify github repos on the about page

---

api/taskcluster/api.go
api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
go.mod
go.sum
webapp/web/app.dev.yaml
webapp/web/app.yaml

This change allows us to accept GitHub events from both `taskcluster.net` and `community-tc.services.mozilla.com` (the new community deployment) by:
1. Extracting base URL from the target URL of the event
2. Accepting both `Taskcluster` and `Community-TC` context strings.
Fixes #1605 .
Tests should pass. And we can merge it to staging monitor that runs keep coming in correctly.

[webhook] Support Taskcluster community deployment

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

Old Taskcluster instance, which uses subdomains for different services
and we need to strip the subdomain away. For example, GitHub events from
the old Taskcluster instance have "tools.taskcluster.net" in their
target URLs, but the root URL should be "taskcluster.net".
#1605

[webhook] Fix URL handling for old Taskcluster

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

We are seeing target URLs from the new community Taskcluster instnace in
the form of:
https://community-tc.services.mozilla.com/tasks/groups/EhYVyJPYShqppX6EjsNWXQ
The /tasks/ part was unexpected by the previous pattern.
We should figure out a way to make this more robust, but let's take this quick fix for now for #1605 .

[webhook] Make URL pattern matching more tolerant

---

webapp/views/wpt-results.js

web-platform-tests.live doesn't work at this point, and this will be the new domain per <https://github.com/web-platform-tests/rfcs/pull/36>.

Update links to use wpt.live.

---

api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/cache/service/.gitignore
webapp/components/test-search.js
webapp/components/test/test-search.html

Add is:tentative command

---

api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
webapp/components/test-search.js
webapp/components/test/test-search.html

Similar to `is:tentative`, this atom filters for tests marked as optional (currently based on file name).

[API] Add `is:optional` command

---

webapp/components/wpt-flags.js
webapp/views/wpt-app.js

web-platform-tests.live is no longer online. wpt.live is.

Update web-platform-tests.live to wpt.live

---

util/deploy.sh

Switch to a more sophisticated two-pass `tr` translation to clean up
branch names:
1. Convert all uppercase to lowercase.
2. Convert all non-alphanumeric chars to hyphens.
Fixes #1578.

[deploy] Filter all illegal chars in branch names

---

api/pending_test_runs.go
api/pending_test_runs_medium_test.go
api/routes.go

1. Filter more precisely: /api/status/invalid now only returns invalid
runs, but not empty or duplicate runs. /api/status/{empty,duplicate}
would return those runs. The frontend isn't changed (i.e. we show
only the invalid runs on /status now), because empty or duplicate
runs aren't that interesting. We could tweak the UI later if needed.
2. Limit the max number of pending runs returned to 500 to fix #1642. We
should add pagination support later.
Go to `/status` of the staging deployment. The page should now fast and the "invalid" tab should not include empty or duplicate runs.

Improve filters for PendingTestRuns

---

webapp/views/wpt-app.js

keydown events do not have the `path` property on Firefox.
Open the staging deployment on Firefox and press some random keys. No exceptions should be raised.

Fix an uncaught exception when keydown on Firefox

---

.travis.yml
util/cleanup-versions.sh

The version cleanup script deletes version older than 1 day without a corresponding branch in origin. Previously, this was done by checking the *local* refs fetched from the remote. There was a problem: Travis uses a shallow clone so we don't have all the refs, so I "worked around" it using `--unshallow`: #1290 . However, I didn't actually test it. Turns out the fix is not working. `git clone --depth=N` also implies `--single-branch`, so even with `--unshallow` we'd only only fetch the full history of the master branch, not the other branches.
This PR fixes the problem properly using `git ls-remote`, which directly queries the remote end without fetching. And this time, I tweaked the Travis setup to actually test it.
Example dry run (before reverting the debug commits): …

Fix stale version cleanup

---

shared/appengine.go

Create a method to retrieve an instance of wpt.fyi Github Bot client, for the implementation of /api/metadata PATCH endpoint. See [design](https://docs.google.com/document/d/1iRkaK6cGgXp3DKbNbPMVsYGMaOHO-5CfqEuLPUR_2HM/edit#heading=h.tx8rv4daaxk9)

Retrieve wpt.fyi Github Bot Client Instance

---

api/manifest/api.go
shared/params.go
shared/params_test.go

There are two fundamental problems:
1. The SHA param validation is not strict enough: regex matching is
prefix matching by default unless the $ anchor is used, so there
might be invalid characters at the end.
2. We construct regexes from untrusted user inputs, which is a big no
and is also unnecessary in this use case.
Coincidentally, this PR also fixes the support for partial (short) SHA
in /api/manifest.
Example crash:
```
regexp: Compile(`MANIFEST-(fd56faf446\).json.gz`): error parsing regexp: missing closing ): `MANIFEST-(fd56faf446\).json.gz`
at google.golang.org/appengine/panic (panic.go:513)
at regexp.MustCompile (regexp.go:245)
at github.com/web-platform-tests/wpt.fyi/api/manifest.getGitHubReleaseAssetForSHA (api.go:88)
at …
```

Fix a crash when /api/manifest gets invalid SHAs

---

results-processor/processor.py
results-processor/processor_test.py
results-processor/test_server.py
results-processor/wptreport.py
results-processor/wptreport_test.py

This PR contains two relatively independent commits, so it's best to review them separately:
1. Improvement: When there are conflicting fields in run_info, try to preserve as much information as possible by delaying raising exceptions.
2. Bug fix: The field name for the SHA in report.run_info should be `revision`; `full_revision_hash` is the field name used in Datastore on the server (due to historical reasons).
There's nothing to "preview". We rely on unit tests in results-processor, which are rather comprehensive.

Improve error handling in results-processor and fix the missing SHAs in invalid runs

---

api/receiver/api.go
api/receiver/api_medium_test.go
api/receiver/create_run.go
api/receiver/create_run_test.go
results-processor/processor.py
results-processor/processor_test.py
shared/models.go
webapp/components/product-info.js
webapp/components/wpt-processor.js

Currently, a pending test run does not include product-related metadata, even though we sometimes do have the data in the JSON report. This change plugs said data into the `PendingTestRun` entity whenever it's available to make debugging much easier.
Again, the changes are split into multiple commits logically, so it'd be easier to review commit by commit.
Demo: https://pending-runs-dot-wptdashboard-staging.appspot.com/status
(Switch to "invalid runs" and you'll see an invalid run uploaded by me manually.)

Include and display product info in pending runs

---

api/query/cache/service/Dockerfile
revisions/service/Dockerfile

This fixes the build for Go App Engine Flex services (announcer &
searchcache) by building the services outside of GOPATH in the builder
container to make sure go.mod is in effect.
Background:
Previously, we did not use go.mod so we needed to copy source code into
GOPATH inside the builder container for Flex services. We did not change
that setup when created go.mod.
However, the Go toolchain does NOT enable the module mode when running
inside GOPATH. The setup happened to continue working because we had
been using the latest major versions (same as the master branches) of
all dependencies. This setup finally broke when go-github released v29
and we haven't upgraded.
This change fixes the root cause (bonus: now we are sure all deps are
also pinned properly in announcer & searchcach). We …

Fix build: use Go modules properly in flex

---

shared/triage_metadata.go
shared/triage_metadata_test.go

Fix the issue where `TestPath` is not being populated when the amendment has no `Results` field. e.g. https://github.com/web-platform-tests/wpt-metadata/pull/60

TestPath is Missing When There is no Results Field in Metadata

---

util/deploy.sh

1. Allow trailing slashes in APP_PATH, which generally come from tab
completion.
2. Do not ask for confirmation in deploy.sh when not in quiet mode:
gcloud CLI already asks for confirmation itself.

Minor improvements of deploy.sh

---

webapp/components/test/test-wpt-metadata.html
webapp/components/wpt-metadata.js

Feature request from https://github.com/web-platform-tests/wpt-metadata/issues/49. Displaying test names with wildcards.
Test name with a wildcard will be displayed in all tests of the current directory and its subdirectories.

Support Display for Metadata Test Name with a Wildcard

---

api/azure/api.go
api/azure/api_test.go
api/azure/mock_azure/api_mock.go
api/azure/webhook.go

And return early when err != nil or build == nil.
Drive-by: switch to the best practice of wrapping errors with more
information in Golang, instead of logging along the way.
Fixes #1406 .
(Note: tests will fail until we land #1752 .)

[Azure] Return error from azureAPI.GetBuild

---

api/routes.go
webapp/web/routes_test.go

This is currently hosted on my github.io but may move in the future.

Update metadata triage CORS rule for gecko dashboard

---

webapp/static/robots.txt
webapp/web/app.yaml

Otherwise based on our routing rules, the request will be redirected to
/results/robots.txt.
This stops Lighthouse from showing a big warning.

Create a valid robots.txt

---

webapp/.lighthouserc.yml
webapp/components/path.js
webapp/components/test-file-results.js
webapp/components/test-search.js
webapp/components/test/path.html

1. Add labels to the expand toggle button and the search box.
2. Get rid of tiny fonts.
3. Remove empty `<a>` elements.
This brings the Lighthouse a11y scores over 90.

More a11y improvements

---

util/deploy.sh

Set the length limit of version names to 22, to leave enough space for
the HTTPS domain name (which could have a very long suffix like
"-dot-searchcache-wptdashboard-staging"). Domain name parts can be no
longer than 63 characters.

Use a shorter version name

---

webapp/components/test-file-results.js
webapp/components/test/test-file-results.html

Previously, the duration row was incorrectly hidden (filtered out) when
a search query is applied, because "Duration" was treated as a subtest
name.
Fixes #1786
Compare https://fix-duration-dot-wptdashboard-staging.appspot.com/results/2dcontext/drawing-images-to-the-canvas/2d.drawImage.animated.poster.html?label=master&label=experimental&aligned&q=chrome%3Afail
against https://staging.wpt.fyi/results/2dcontext/drawing-images-to-the-canvas/2d.drawImage.animated.poster.html?label=master&label=experimental&aligned&q=chrome%3Afail

[webapp] Show duration when searching

---

api/azure/api_test.go
api/query/search.go
api/query/search_test.go
api/receiver/client/client.go
api/receiver/mock_receiver/api_mock.go
api/taskcluster/webhook_test.go
shared/appengine.go
shared/run_diff.go
shared/sharedtest/appengine_mock.go
shared/sharedtest/run_diff_mock.go
shared/sharedtest/test_run_query_mock.go

We still don't know why #1808 is happening, but based on experiments
switching to net/http fixes #1808, and it is recommended anyway (also
part of #1747).
This unfortunately changes the signature of a widely used method.

Migrate from appengine/urlfetch to net/http

---

api/query/cache/service/main.go
api/query/cache/service/search.go

Previously we had a bunch of cases where the API handler did not return
after encountering fatal errors. In some cases, we would even try to
rewrite the status code of the response after writing out the error
message, which is impossible.
There is no bulletproof way to prevent missing returns, but it still
helps to extract the bulk of the handler into a new function that
explicitly returns an error which is then handled in one single place.
This is largely a no-op refactor.

[searchcache] Improve error handling

---

api/metadata_cache.go
api/metadata_handler.go
api/metadata_handler_test.go
api/query/atoms.go
api/query/cache/poll/poll.go
api/query/cache/service/main.go
api/query/metadata_cache.go
shared/metadata.go
shared/metadata_util.go
shared/triage_metadata.go

Fix for #1776 in searchcache and webapp. This change polls Metadata update in the background in searchcache and update Metadata through memcache in webapp on a 10-minute interval.

[Searchcache, webapp] Create Caching for WPT Metadata

---

api/manifest/util.go
api/manifest/util_test.go
shared/manifest.go
shared/manifest_test.go
shared/models.go

The first commit fixes #1777 , while the second commit implements a new API for `wpt-metadata` (cc @KyleJu : let me know if `Contains` isn't enough for wpt-metadata).

Manifest trie

---

shared/manifest.go
shared/manifest_test.go

Rename `Contains` to `ContainsFile` to make it clear that it checks the
existence of a file path (or directory path), and implement a new
`ContainsTest` method to check the existence of a test URL.
`ContainsTest` supports both multi-global tests and test variants.
I'm not quite happy about some of the names (especially the exported one). Please feel free to give suggestions.

Implement Manifest.ContainsTest

---

api/receiver/client/client.go
api/receiver/client/client_test.go
api/receiver/receive_results.go
api/receiver/receive_results_test.go

This attempts to fix #1830.
Missing Content-Type: application/x-url-form-encoded when posting an
HTTP form is clearly a bug, but it is unclear why it only started to
surface after #1811.
A preventative measure is also added to return an error when the upload
payload is empty, along with some minor improvements to logging.

Add the missing Content-Type header back

---

api/README.md

Taken from https://github.com/web-platform-tests/wpt-metadata/pull/62 with minor changes on line 604

Update the Triage Metadata API Doc

---

api/README.md
api/diff.go

panic: runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
google.golang.org/appengine/panic
/usr/local/go/src/runtime/panic.go:513
github.com/web-platform-tests/wpt.fyi/api.handleAPIDiffGet
/tmp/staging/srv/api/diff.go:83
github.com/web-platform-tests/wpt.fyi/api.apiDiffHandler
/tmp/staging/srv/api/diff.go:25
The direct cause is trying to dereference an incorrect error (err
instead of parseErr). However, the whole function body was convoluted
and error-prone, so I've decided to refactor it (extract `loadDiffRuns`
out) to make error handling clearer.
Also remove an unused type definition.

Fix a panic in diff.go

---

api/user.go

log-in in the response should be login.

Fix a typo in /api/user

---

webdriver/webdriver.go

`e.shadowRoot` might be null if the custom element hasn't been defined, in which case we should not try to query elements in the shadow DOM (and retry instead).
Example panic:
```
panic: javascript error: javascript error: Cannot read property 'querySelectorAll' of null
(Session info: chrome=80.0.3987.132)
(Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Linux 5.0.0-1032-azure x86_64) [recovered]
panic: javascript error: javascript error: Cannot read property 'querySelectorAll' of null
(Session info: chrome=80.0.3987.132)
(Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Linux 5.0.0-1032-azure x86_64)
```

Avoid dereferencing null in webdriver tests

---

.gitignore
webapp/web/.gcloudignore

* Some files no longer exist.
* Simplify rules (e.g. `**/foo` and `foo/*` are equivalent to `foo/`).
* Sort rules by categories.

Cleanup .gitignore and .gcloudignore

---

shared/triage_metadata_test.go

Add Triage Metadata Tests for Asterisks and Subtests. In preparation for landing #1866

Add Triage Metadata Tests for Asterisks and Subtests

---

shared/triage_metadata.go
shared/triage_metadata_test.go

if the user does not have a public email address on GitHub.
Fixes #1863.

Fall back to the GitHub no-reply email

---

webapp/components/wpt-header.js

Continuing to show this caveat prominently isn't really helpful.

Remove the "wpt.fyi is a work in progress" warning

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

We forgot to add crashtest into the regex which is used to filter only
the recognized task names (and exclude e.g. Python unit tests).

Collect crashtest results from Taskcluster

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

Follow up to #1883
Stupid me... I clicked the button right after entering `git push` and ended up merging the #1883 without including this change.

[taskcluster] Relax regex and add tests

---

shared/datastore.go
shared/params_test.go
shared/test_run_query.go

This fixes #1913 .
The root cause is that when the filter is too broad (e.g. without `label=master`), we will find thousands of candidates for further filtering in `clientSideFilter`, which exceeds the limit of `GetMulti` (up to 1000 entities per call). This PR sets a limit on the number of candidates, and adds a warning to logs.
Note that this is not a perfect fix. It is possible that we will miss runs. Due to Datastore limitations (inequality can only be used on one field), we cannot filter by timestamps here if we are already filtering by some other criterias, so we really need to get *all* runs matching all the other filters to make sure we don't miss any in the time range. However, this was already broken before and I don't see a good way to fix it properly without refactoring (once …

Fix "too many runs" in /api/runs

---

api/README.md

Note that the `query` parameter is still not documented.
@mikewest was tripped up by /api/runs not returning the same runs as wpt.fyi searches today, after reading this documentation.

Improve documentation for /api/search

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

Since commit b8fac0b the webkitgtk runs from taskcluster are not longer updated to wpt.fyi
This is caused because the browser identifier on TC has an underscore.
This fixes: https://github.com/web-platform-tests/wpt/issues/23313
Tested by:
```
go test -tags=small -v  ./... -run TestTaskNameRegex
```

[taskcluster] Allow underscore (_) for the browser name identifier.

---

util/deploy.sh

We used the short SHA of the version name when deploying master.
However, the short SHA might happen to take the form of scientific
notation, e.g. 1e12345, in which case it'd be interpreted as a floating
point number by gcloud command and the deployment would fail.
Add a prefix "rev-" to the version name to prevent this from happening.
Example: https://travis-ci.com/github/web-platform-tests/wpt.fyi/jobs/330780571#L1939

Fix version name errors when deploying master

---

api/taskcluster/api.go

This is guessing based on logs, since I can't find where on GitHub you
actually get the app id. However it is likely that it changed since the
last time we tried to switch to the checks API, as we've moved from
TaskCluster to Community-TC since then.

Update the ID of the Community-TC GitHub App

---

api/checks/webhook.go

Previously we logged debug information for check_run immediately upon receiving them,
but check_suites only after filtering them for 'allowed' checks. This unifies the two codepaths
to both log immediately, so that we can better understand calls we receive.
In addition, this commit also fixes a misleading log line in handleCheckRunEvent (which used
'check_suite' instead of 'check_run'), and adds the GitHub App Name to the debug info.

Improve logging for check_run and check_suite paths

---

webapp/views/wpt-results.js

Fix for #1951. Users are unable to deselect test directories in the Triage Metadata UI.
The issue is caused by the fact that the `test` is being overwritten with extra `/*` inside of `handleSelectMetadata`

[UI] Unable to deselect test directories

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
webapp/components/wpt-flags.js

This flag decides whether or not taskcluster runs on all branches or
just master. Turning the flag off today would break pull request checks
and epoch runs, so it seems like a candidate for flag clean-up.

Remove always-on 'taskclusterAllBranches' flag

---

webapp/components/test/wpt-amend-metadata.html
webapp/components/wpt-amend-metadata.js

Add a href that links to a test search in Monorail.
Enable the Triage Metadata toggle, click on failing chrome tests and click on Triage. The tests on the triage view are hyperlinks to Monorail

Add href that searches test in Monorail

---

webapp/components/wpt-flags.js

This flag is no longer in use after
https://github.com/web-platform-tests/wpt.fyi/pull/1956

Remove processTaskclusterCheckRunEvents flag from the admin UI

---

.travis.yml

This is a regression caused by lhci 0.3.9 (#1805 ). First failure:
https://travis-ci.com/github/web-platform-tests/wpt.fyi/jobs/289437504#L2179
The root cause is that lhci-cli started to require branch names when uploading results:
https://github.com/GoogleChrome/lighthouse-ci/commit/8691dcb75b40a302d6db84fc3f963ff2f7040fb9#diff-cc0cba378c8a7fa9b550e5c205605ccfR80
However, the upload failure is only a warning so we didn't notice. I've filed https://github.com/GoogleChrome/lighthouse-ci/issues/325 for that.
The fix is to pass `TRAVIS_BRANCH` and `TRAVIS_PULL_REQUEST_BRANCH` into Docker, which will be used by
https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/utils/src/build-context.js#L104

[webapp] Fix lhci upload

---

webapp/views/wpt-results.js

See https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1590518415027-18038.report.html#accessibility
This button was somehow missed by older versions of lhci (including the one built into Chrome 83) but picked up by the new version.

[webapp] Increase the contrast of "show history"

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

This is a prepatory refactor for the Taskcluster Checks migration.
Instead of using tcqueue.TaskDefinitionAndStatus directly, we extract
the information we actually need into a new taskInfo struct.
The goal is to ultimately share the logic in extractArtifactURLs and
processTaskclusterBuild between the GitHub Status and the (upcoming)
GitHub Checks paths.

Abstract Taskcluster tasks into their own struct

---

Makefile

This new option was introduced to lhci in
https://github.com/GoogleChrome/lighthouse-ci/pull/329
It'd prevent regressions in upload from going unnoticed.

Make lighthouse fail on upload failures

---

api/taskcluster/webhook_test.go

The PR to introduce an EventInfo struct pulled the test code into its
own package. Just before it landed, another PR added a new test that was
not updated to handle being in a different package. Since we don't have
a commit queue both PRs landed cleanly, but the combination broke the
build for master.
This PR fixes the newly added test.

Unbreak api/taskcluster/webhook_test.go build

---

api/taskcluster/webhook.go

Due to a merge conflict, the original definitions of taskInfo and
taskGroupInfo were left behind when they were made into public
interfaces. (Their location in the file was moved at the same time).

Remove some unused code

---

api/taskcluster/mock_taskcluster/webhook_mock.go
api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

This PR adds the ability to handle GitHub `check_suite` events as part of the
Taskcluster webhook. Similarly to the existing flow for `status` events, we
extract the relevant event information and then post tasks to the receiver for
the found tasks.

Support handling CheckSuite events for taskcluster

---

renovate.json

google.golang.org/genproto contains automatically and frequently updated code
generated from protobuf. Most of the time, there's no need to update it
explicitly.

Ask Renovate to ignore genproto

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

Previously we hardcoded the WPT owner and repository. This failed for
the wpt-tc-checks test repository, and would also provide a less than
useful error message if a non-WPT repository sent us a check_suite
event. Instead, check specifically that we are receiving the event from
an allowed source, and then use it in the check_runs call.

Use the input owner/repo when requesting check_runs for a check_suite

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

A CheckSuite has a Repository member, but GitHub actually sends the
repository information in the CheckSuiteEvent.Repo member instead.

[Taskcluster] Read repo name/owner from correct struct member

---

webapp/components/product-info.js
webapp/components/test-file-results-table.js
webapp/components/test-runs.js
webapp/views/wpt-results.js

Fix for https://github.com/web-platform-tests/wpt.fyi/issues/2006, https://github.com/web-platform-tests/wpt.fyi/issues/1896
The mismatch between `products` and `testRuns` lies at the use of `/api/run` and `api/search`. When `run_ids` and `q` are used directly in `api/search`, `products` becomes outdated. However, updating `products` immediately after `testRuns` is fetched will trigger another cycle of `testRuns` update.
IMO, `products` should be named something like `queryProducts` because it's exclusively used for the query parameters of `/api/runs`. For https://github.com/web-platform-tests/wpt.fyi/issues/1896, the question is when a user deletes/adds a product, are they deleting a `queryProducts` or a `displayedProduct`?

Products and TestRuns mismatch

---

api/checks/runs.go
api/taskcluster/webhook.go

This is a quick fix to workaround the missing shards from WPT results.
Longer term we should properly deal with pagination, but for now we use
the fact that we know there are less than 100 results.

Receive 100 check-runs per page

---

api/checks/runs.go
api/taskcluster/webhook.go

The code as written was just pretty wrong for how GitHub APIs work. Firstly, it checked if `NextPage >= LastPage`, which is an off-by-one error. Secondly, go-github actually just returns 0 for **both** those fields once it reaches the last page... from a test file I wrote, querying check_suite 898247597:
```
$ go run main.go
request 0
NextPage: 2 PrevPage: 0 FirstPage: 0 LastPage: 2
request 1
NextPage: 0 PrevPage: 1 FirstPage: 1 LastPage: 0
done
```

Fix GitHub pagination handling

---

api/taskcluster/webhook.go

This repo was a temporary testing ground for moving WPT to the
Taskcluster Checks api. That migration has now taken place, so the
repository is no longer needed.

Remove references to wpt-tc-checks repository

---

results-processor/wptreport.py
results-processor/wptreport_test.py

This change refactors the logic for adding release channel labels based
on browser_channel so that the mapping is browser-dependent, with two
changes in behaviours:
1. Treat Chrome Nightly differently from Firefox Nightly. Chrome Nightly
is in fact Chromium ToT (recently added in
https://github.com/web-platform-tests/wpt/pull/24702), and we don't
want to add the experimental label to it which would mix it with the
official Chrome Dev.
2. Add a "nightly" label to Chrome/Edge Canary (we only have Edge Canary
runs as of now) to allow easy comparison between e.g. Chrome Nightly
(Chromium ToT) and Edge Canary.

[results-processor] Handle Chrome Nightly

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

During the migration to the GitHub Checks API for Taskcluster, we
mistakenly interpreted the 'status' field of a CheckRun as equivalent to
the 'status' field of a Taskcluster task. This is not the case; in the
Taskcluster case 'status' captures the success/failure state of a task,
but for CheckRuns it merely captures the finished/not-finished state.
Instead, CheckRuns should use the 'conclusion' field to get the result
of the task.
To keep things compatible with the existing logic that assumes
Taskcluster status results, we map 'success' --> 'completed'. In the
future we should remove the old status code and switch to just using the
conclusion.
Issue: https://github.com/web-platform-tests/wpt.fyi/issues/2091

[Taskcluster] Reject tasks that have non-success state

---

ISSUE_TEMPLATE/prod-deployment.md

We are still using the legacy template style, which is just a markdown
file (with no metadata), because it allows you to specify a default
template that is automatically used for 'new issue' (without showing
a selection UI).

Move prod-deployment.md to correct template location

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Drive-by:
1. Use log.warning instead of deprecated log.warn
2. Use frozenset to prevent accidental modification
See https://github.com/web-platform-tests/wpt/issues/24752#issuecomment-672308403

[results-processor] Fix experimental label for WebKitGTK

---

webapp/components/wpt-processor.js

Fixes #2106
Click the "processor" link on the staging deployment and switch to the "invalid" tab. You should see runs, and no errors in DevTools.

Fix timestamps on /status page

---

webapp/components/test-file-results-table.js
webapp/components/test/test-file-results-table.html

Fix https://github.com/web-platform-tests/wpt.fyi/issues/2118
For computed properties, "the computing function is not invoked until at least one dependency is defined (!== undefined)". In this case, testRuns is defined but assigned to null instead of a real value.

[Triage Metadata] testRuns null issue

---

Makefile

This is a hopefully temporary workaround for https://github.com/web-platform-tests/wpt.fyi/issues/2128,
to stop making unrelated PRs red and avoid missing real regressions.

[web-components-test] Pin Chrome to 84 to workaround hang

---

api/query/cache/service/search.go
shared/cache.go
shared/run_diff.go

Part of #1747.
Drive-by: fix a warning discovered by the latest version of golang:
api/query/cache/service/search.go:110:40: conversion from RunID (int64) to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

Remove remaining uses of urlfetch

---

shared/appengine.go
webapp/about_handler_test.go

Migrate away from deprecated google.golang.org/appengine; #1747.
There should be no observable changes, except one when running locally: stop showing the current local git branch as the version, as the added convenience don't justify the complexities.

Get application identity from env vars and APIs

---

api/checks/update.go
api/checks/webhook.go

Make sure to log errors for 5xx responses and always return after
setting the error code.
This is a follow-up to the outage in #2158 .

[checks] Fix logging

---

shared/appengine.go

Follow up to #2153 and part of #1747 .
TODO (in a future PR): figure out a way to test this locally. The new SDK no longer provides a local emulator for TaskQueue.

Fixup: restore Content-Type in CloudTasks

---

api/interop_medium_test.go
shared/logger.go
shared/sharedtest/util.go

A part of #1747,  AppEngine Context migration.

Migrate appengine.NewContext to request.Context()

---

api/metadata_handler.go
api/metadata_handler_test.go
api/user.go
shared/appengine.go
shared/github_oauth.go
shared/sharedtest/github_oauth_mock.go
webapp/login.go
webapp/login_test.go

This is in part a refactor to pave the way for migrating away from AppEngine User API to GitHub User API (part of #1747 ) and also a fix for #2157.
It'd be easier to review by commits.

Refactor part of GitHub OAuth

---

shared/logger.go

A part of #1747, preparing for the logger migration. No behavioural changes.
- Removed unused `NewRequestContext`, `NewLoggerMux` functions and all `loggerMux` related methods
- Made `withLogger`, `newGAELogger`, `newAppEngineFlexContext` private
- Rearranged the order so it flows better
Verify [logs here](https://pantheon.corp.google.com/logs/viewer?project=wptdashboard-staging&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2Fgo112-log&minLogLevel=0&expandAll=false&timestamp=2020-09-23T20:52:39.411000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-09-23T19:52:39.662Z&dateRangeEnd=2020-09-23T20:52:39.662Z&interval=PT1H&logName=projects%2Fwptdashboard-staging%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2020-09-23T20:50:28.793821000Z)

Clean up logger.go for the migration

---

api/diff.go
api/test_run.go
api/test_runs.go
shared/datastore.go
shared/datastore_ae.go
shared/datastore_cloud.go
shared/github_oauth.go
shared/sharedtest/github_oauth_mock.go
webapp/admin_handler.go
webapp/admin_handler_test.go
webapp/login.go
webapp/web/app.dev.yaml
webapp/web/app.yaml
webapp/web/routes_test.go

Extracted from #2173 (the first half)
#2173 will be rebased to contain only the api/* part after this lands. 
* Try https://admin-via-github-dot-wptdashboard-staging.uk.r.appspot.com/admin/flags ; You should see permission denied.
* Login on https://staging.wpt.fyi and copy the session cookies to https://admin-via-github-dot-wptdashboard-staging.uk.r.appspot.com . Then visit https://admin-via-github-dot-wptdashboard-staging.uk.r.appspot.com/admin/flags again ; you should see again permission denied.
* I'll add your GitHub handle to the admin table. Now you should see the admin page. Note that the actual upload function won't work until #2173 lands.
It'd be easier to review by commits. Please skip all `*_mock.go` files.

Use GitHub to manage access to admin/* pages

---

api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/poll/poll.go
api/query/concrete_query.go
webapp/components/test-search.js
webapp/components/test/test-search.html
webapp/routes.go
webapp/web/app.dev.yaml
webapp/web/app.yaml

This reverts commit 14c45844f0ee96efb359a30b4361e584472b191c, removing
the search-by-content feature which never launched* and whose underlying
AppEngine API is being deprecated (#1747 ).
* It was a PoC. To launch it, we'd also need a cronjob to update the full-text search index.
Also remove the remote_api from the prod configuration; after this revert, we now only use remote_api locally for testing.
This is almost a pure revert (only one small merge conflict). To review, maybe try some structured queries in the staging instance to do some smoke tests.

Revert "Add atom for filtering by test-file contents (#1216)"

---

webapp/about_handler.go
webapp/about_handler_medium_test.go
webapp/admin_handler.go
webapp/analyzer_handler.go
webapp/components/github-login.js
webapp/dynamic_components_handler.go
webapp/flags_handler.go
webapp/insights_handler.go
webapp/interop_handler.go
webapp/processor.go
webapp/routes.go
webapp/service_worker_handler.go
webapp/template.go
webapp/templates/_ga.html
webapp/templates/_head_common.html
webapp/templates/_test_run_query_params.html
webapp/templates/_test_run_ui_query_params.html
webapp/templates/about.html
webapp/templates/admin_flags.html
webapp/templates/admin_upload.html
webapp/templates/analyzer.html
webapp/templates/flags.html
webapp/templates/index.html
webapp/templates/insights.html
webapp/templates/processor.html
webapp/templates/test-runs.html
webapp/test_results_handler.go
webapp/test_results_handler_medium_test.go
webapp/test_runs_handler.go
webapp/views/wpt-app.js

This PR replaces #2166 and is a proper fix for https://github.com/web-platform-tests/wpt.fyi/pull/2166#issuecomment-696546751. With it, we now show the user header correctly and consistently across all of our public pages (in other words, except for admin/*), and only show triage-related help/toggle in the homepage.
Please review all changes at once (they'll be squash-merged).
Homepage:
Other pages:
Homepage:
Other pages:

[webapp] Populate user header everywhere

---

api/checks/mock_checks/api_mock.go
api/receiver/api.go
api/receiver/api_medium_test.go
api/receiver/mock_receiver/api_mock.go
api/receiver/receive_results.go
api/receiver/receive_results_test.go
shared/appengine.go
shared/sharedtest/appengine_mock.go

This is a follow-up to #2175 (which is also a part of #1747 ), finishing up the remaining migration from appengine.user to GitHub OAuth in api/* (namely the results receiver and its admin upload page).
The tests should be fairly self-explanatory. For manual testing:
* Try https://admin-via-github-dot-wptdashboard-staging.uk.r.appspot.com/admin/results/upload ; You should see permission denied.
* Login on https://staging.wpt.fyi and copy the session cookies to https://admin-via-github-dot-wptdashboard-staging.uk.r.appspot.com . Then visit https://admin-via-github-dot-wptdashboard-staging.uk.r.appspot.com/admin/flags again ; you should see again permission denied.
* I'll add your GitHub handle to the admin table. Now you should see the admin upload page. Try uploading a random JSON (not …

Use GitHub to authenticate admin access to api/*

---

shared/appengine.go

This is a very sad dirty fix. I'm not even sure if it'd work until I push it to prod (our staging project is in a different region). And it's very hard to test as Cloud Tasks doesn't have an emulator.
Fixes #2189 .

Map us-central to us-central1 for Cloud Tasks

---

shared/appengine.go
shared/appengine_test.go

Follow-up to #2189 where I forgot to actually use the new variable.
Sorry about the mistake. We really should have a test for this. Short of a local emulator for Cloud Tasks, WDYT about introspecting the proto?

Actually use the correct location when scheduling tasks

---

api/checks/api.go
api/checks/suites_medium_test.go
api/checks/update_medium_test.go
api/interop.go
api/interop_medium_test.go
api/labels_medium_test.go
api/pending_test_runs_medium_test.go
api/query/search_medium_test.go
api/receiver/api_medium_test.go
api/shas_medium_test.go
api/test_run_medium_test.go
api/test_runs_medium_test.go
api/versions_medium_test.go
shared/datastore.go
shared/datastore_ae.go
shared/datastore_cloud.go
shared/models_test.go
shared/sharedtest/datastore_mock.go
shared/test_run_query_medium_test.go
util/populate_dev_data.go

This is part of #1747 and a pure refactor without any behaviour changes.
Refactor all direct use of .../appengine/datastore library with datastore_ae. Implement the missing `NewIncompleteKey` and `PutMulti` APIs.

[Go 1.12] Refactor the direct use of /appengine/datastore library with datastore_ae

---

api/query/cache/service/main.go
shared/logger.go

A part of https://github.com/web-platform-tests/wpt.fyi/issues/1747, this PR modifies searchcache logging to the correct google cloud logging setup.
With this change, searcache logging will show structured logging and severity in the appengine. A few behavioral changes are introduced:
- When fail to initiate gclog, the program is [terminated](https://github.com/web-platform-tests/wpt.fyi/pull/2190/files#diff-29135f505c736f13d37da653c9755a6a17118cd4363bee5998e54d5a04cb615cR168), rather than [continue without a logger](https://github.com/web-platform-tests/wpt.fyi/pull/2190/files#diff-63407b1c55c2275cab0b2de74003827d3e5a4fdaa4c3208dcce9e5fb91b580bcL150)
- HTTP response status codes are not set for gclog, and it might also affect Stackdriver alerting; see the …

[Go 1.12] Correct the Google Cloud logging setup for searchcache

---

api/diff.go
shared/datastore_ae.go
shared/datastore_cloud.go
shared/errors.go
shared/errors_test.go

Return shared.MultiError from both AppEngine and Cloud
datastore.GetMulti, including unification of ErrNoSuchEntity.
Part of #1747

Encapsulate MultiError from datastore SDKs

---

.travis.yml
api/labels_medium_test.go
go.mod
go.sum
shared/appengine.go
shared/cache.go
shared/cache_test.go
util/deploy.sh
util/travis-deploy-staging.sh
webapp/admin_handler.go
webapp/web/app.dev.yaml
webapp/web/app.staging.yaml
webapp/web/app.yaml

Part of #1747 . I followed https://cloud.google.com/appengine/docs/standard/go/using-memorystore#setup_redis_db for the setup (note that this needs to be repeated on prod before the next prod release; **update**: I've completed this).
This completely migrates us off of the legacy memcache in AppEngine to Cloud Memorystore (Redis). With this change, each instance of webapp creates a pool of Redis connections on startup for API handlers to use if it is running in the cloud; when running locally, it'd skip memcache altogether.
Tested manually (by verifying the logs and inspecting the Redis instance). Unfortunately we have to drop a test for now as it requires a local Redis, which we don't have.

Migrate from AppEngine memcache to Memorystore (Redis)

---

Makefile
shared/sharedtest/util.go
webdriver/webapp_server.go

Part of #1747 
1. Enable Cloud Datastore emulator when running tests (this will unblock us from switching to Cloud Datastore SDK)
2. Attach a nil logger to local dev_appserver (this suppresses a large number of "logs will be lost" warnings when running tests)

Tweak local testing setup in preparation for go1.12 switchover

---

shared/appengine.go

One theory for https://github.com/googleapis/google-cloud-go/issues/3205
(and https://github.com/web-platform-tests/wpt.fyi/issues/2224)
is that the instance might receive a request when it is shutting down
(and closing the clients).
To discover and/or prevent this scenario, we
* Add a log message at the beginning of shared.Clients.Close()
* Set the clients to nil before closing them (this would cause a panic
if a client is later used)

Prevent a potential race condition when closing clients

---

Makefile
api/interop.go
util/docker-dev/dev_data.sh
util/docker-dev/web_server.sh

Fixes #2259.
Make sure we start Cloud Datastore emulator in Docker as well, and plumb
the necessary flags (e.g. the port number) around.
Drive-by: fix a flaky WebDriver test. In api/interop.go, we use
`it.Next` to load the next entity into a struct that may not be zero,
in which case Datastore library will not zero it out first and may leave
stale data in the struct (e.g. if a slice field already has N items but
the entity to be loaded only has N-1 items in that field, the last item
will not be removed from the struct). The issue only surfaced after
PR #2252 as the IDs in Datastore emulator are no longer sequential.

Fix Docker environment after #2252

---

.github/actions/make-in-docker/action.yml
Dockerfile
go.mod
webapp/web/app.staging.yaml
webapp/web/app.yaml

On the language side, here's a brief changelog: https://en.wikipedia.org/wiki/Go_(programming_language)#Version_history
In short, a few minor backward-compatible additions; my favourites? [error wrapping](https://blog.golang.org/go1.13-errors) and [overlapping interface embedding](https://dave.cheney.net/2020/05/24/diamond-interface-composition-in-go-1-14)!
On the AppEngine side: https://cloud.google.com/appengine/docs/standard/go/release-notes
Again, nothing major here.

Upgrade to Go 1.14

---

webapp/components/test/wpt-metadata.html
webapp/components/wpt-metadata.js

Fix #2216; verify [here](https://ui-link-not-shown-dot-wptdashboard-staging.uk.r.appspot.com/results/css/css-flexbox?label=master&label=experimental&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk&aligned&q=triaged%3Awebkitgtk)

[Triage Metadata] Links not shown when metadata entries have same URLs

---

api/query/cache/service/Dockerfile

Bump searchcache to Go 1.14 as well

---

api/query/README.md

Just "q" has no effect, and is not what the wpt.fyi frontend uses.

Fix name of query parameter in /api/search payload

---

api/README.md
api/query/README.md

https://github.com/web-platform-tests/wpt.fyi/blob/f8d9beebe98a4d254d1ae0d0283c4fe7cef3196e/api/query/atoms.go#L437

Document run_ids as non-optional for /api/search

---

api/README.md

Reverts web-platform-tests/wpt.fyi#2284
Turns out we were confused by structured (POST) vs. unstructured (GET) queries. `q` does still work for unstructured queries.

Revert "Link to more documentation of /api/search"

---

webapp/components/test-runs-query.js
webapp/views/wpt-app.js

A temporary fix for #2272. This change hides EDIT button when the URL params use `run_id` or `max_count`. 
To properly fix it, we first need to figure out how a browser can be added when a user queries by `run_id` (e.g. fetching the latest run_id of that browser). I think it is better to hide it for now.

[UI] Hide EDIT when URL params use run_id or max_count

---

webdriver/builder_test.go
webdriver/label_test.go
webdriver/path_test.go
webdriver/product_test.go
webdriver/search_test.go
webdriver/test_runs_test.go
webdriver/webdriver.go

The main motivation is to extend the timeout everywhere as we started to see timeouts more often since the Go 1.12 migration (which is presumably caused by the slower Datastore emulator), but I took the chance to do some other cleanup as well.

Cleanup helpers and timeouts WebDriver tests

---

api/README.md
webapp/components/info-banner.js
webapp/components/wpt-bsf.js
webapp/components/wpt-flags.js
webapp/static/expand_less.svg
webapp/static/expand_more.svg
webapp/views/wpt-app.js

Frontend UI for BSF on wpt.fyi [milestone one](https://docs.google.com/document/d/1YsWyovoje7rvW_u-kaCJAWvFJ2QjafvyVqWKtmafFHw/edit#heading=h.4agfzcyzhu2y).
This PR doesn't define the list of cases that hide the BSF graph on the homepage. A follow-up PR will be sent shortly for it.
To see the BSF graph, go to /flags and click on `Enable Browser Specific Failures graph`

[BSF] Frontend for BSF on wpt.fyi milestone one

---

webapp/views/wpt-app.js

Define a list of conditions that hide the BSF graph
- the search bar is in use
- users visit non-results page
- query by run_id or sha

[BSF] Conditions for hiding the BSF graph

---

webapp/components/test/wpt-metadata.html
webapp/components/wpt-metadata.js

Fix  #2333. Don't skip `metadataMap` from `seenProductURLs` . 
`metadataMap` stores metadata for all triaged tests and is used to show inline icons. `displayedMetadata` displays the metadata on the bottom of test results view and only show metadata on the test-file level. 
See [here](https://fix-subtest-missing-dot-wptdashboard-staging.uk.r.appspot.com/results/css/selectors/attribute-selectors/attribute-case/semantics.html?label=experimental&label=master&aligned)

[Triage Metadata] Unskip metadataMap from seenProductURLs

---

webapp/components/wpt-bsf.js
webapp/views/wpt-app.js

Set up Google Analytics for hover and hide actions:
- `hover` tracks the duration spent on the general area of the BSF graph, including the banner
- `hide` tracks the number of times users hide/open the BSF graph
For the setup, see https://developers.google.com/analytics/devguides/collection/analyticsjs/events.
Also work around a [known issue](https://stackoverflow.com/questions/17244996/why-do-the-mouseenter-mouseleave-events-fire-when-entering-leaving-child-element) where the children svg (in this case Google Chart) interferes with parent's `onmouseenter` event. Use `isInteracting` to keep track of the state of interaction with the BSF chart.
Note that unlike the origin design, we can track clicks on stable/experiment through the /api/bsf endpoint usage and zoom-in/zoom-out are covered …

[BSF] Set up Google Analytics for hover and hide actions

---

webapp/components/wpt-amend-metadata.js

A follow-up fix for https://github.com/web-platform-tests/wpt.fyi/pull/2222#issuecomment-761100542 as it is breaking the staging instance

[Triage Metadata] wrong order of getSearchURL params

---

webapp/components/wpt-flags.js

Take down the `showBSF` flag due to https://github.com/web-platform-tests/wpt.fyi/issues/2349. This PR should unblock the wpt.fyi release

[BSF] Disable showBSF flag temporarily 

---

webapp/components/wpt-flags.js
webapp/views/wpt-app.js

Fix https://github.com/web-platform-tests/wpt.fyi/issues/2349. 
This fix wraps the `iron-collapse` with `dom-if` so BSF graphs are only loaded when it is shown. The cause I suspect is that [`iron-collapse adjusts the max-height/max-width of the collapsible element to show/hide the content`](https://www.webcomponents.org/element/@polymer/iron-collapse), which messes up the calculation of axis width when hide.

[BSF] Fix axis title display issues

---

webapp/components/test-file-results-table.js

Fix #2300.
See [here](https://passing-subtest-icon-dot-wptdashboard-staging.uk.r.appspot.com/results/eventsource/format-field-id-null.window.html?label=experimental&label=master&aligned) and its [wpt-metadata](https://github.com/web-platform-tests/wpt-metadata/blob/master/eventsource/META.yml)

[Triage Metadata] Show all metadata in triage mode

---

webapp/components/test/wpt-metadata.html
webapp/components/wpt-metadata.js

Fix #2355. When `path` is a subfolder, add a `/` for correct prefix matching.
See [here](https://fix-metadata-matching-dot-wptdashboard-staging.uk.r.appspot.com/results/css/cssom?label=experimental&label=master&aligned)

[Triage Metadata] Fix incorrectly matched path prefix

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Currently conflicts reported by the processor report the field that
conflicted but not the values that it saw, e.g.:
"Conflicting 'browser_version' found in the merged report"
This change adds the values, to better help debugging what conflict
occurred. Note that we bail on the first report that fails, so it is
possible that we could have (e.g.) 5 reports with 5 different
'browser_version's, and we would only report the first two after
this change.

[results-processor] Make conflicts easier to debug

---

webapp/package-lock.json
webapp/package.json

Reverts web-platform-tests/wpt.fyi#2377. In the previous [rollback](https://github.com/web-platform-tests/wpt.fyi/pull/2378), the suspected cause of the failure already existed; see [here](https://github.com/web-platform-tests/wpt.fyi/runs/1814557480). 
I suspected the real issue is a regression in the [accessibility score](https://travis-ci.com/github/web-platform-tests/wpt.fyi/jobs/479823457). However, this major update in lhci seems to [worsen the build failure](https://travis-ci.com/github/web-platform-tests/wpt.fyi/jobs/479823876).

Revert "Update dependency @lhci/cli to v0.7.0"

---

webapp/components/github-login.js
webapp/views/wpt-app.js

Fix the GitHub check failures due to a low accessibility score. The failing test expects the score to be > 90.
- [Use the `aria-label` attribute for buttons](https://web.dev/button-name/?utm_source=lighthouse&utm_medium=devtools#how-to-add-accessible-names-to-buttons)

[UI] Improve accessibility score for Lighthouse

---

webapp/package-lock.json
webapp/package.json

Reverts web-platform-tests/wpt.fyi#2381. See https://github.com/web-platform-tests/wpt.fyi/issues/2411

Revert "Update dependency @vaadin/vaadin-context-menu to v5"

---

webdriver/chrome.go

This works around failures in go_chrome_test when running in docker locally.
The failures appear to stem from Chrome failing to load resources from the
network (net::ERR_INSUFFICIENT_RESOURCE), which some googling implies
may be caused by trying to use shm and hitting memory limits.
Note that puppeteer specifically suggests to do this:
https://developers.google.com/web/tools/puppeteer/troubleshooting#tips

[webdriver-tests] Disable shm usage for Chrome

---

api/taskcluster/webhook.go
go.mod
go.sum

There appear to be no breaking changes, based on
https://github.com/taskcluster/taskcluster/releases/tag/v42.0.0

Upgrade major version of taskcluster

---

webapp/components/test/wpt-amend-metadata.html
webapp/components/wpt-amend-metadata.js

The link is only added for test-level issues, and links to the new-issue
interface in the wpt-metadata repository. The title is pre-filled based
on the test name, and a 'compat2021-test-issue' label is added.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/2420

[triage] Add a 'file issue' link for test-level issues

---

shared/test_run_filter.go
util/populate_dev_data.go
webapp/components/wpt-flags.js
webapp/test_results_handler.go

Both of these flags have been default-on in wpt.fyi for many years, and
we are exceedingly unlikely to change them to be false at any point.
Removing them clarifies the intent of the code - and has also revealed
an existing inconsistency in our codebase (see Default() in
shared/test_run_filter.go).

Remove deprecated experimentalByDefault and experimentalAligned flags

---

renovate.json

Switch renovate to batch updates every Monday. Currently Renovate sends updates whenever there is one available.
See the [schedule](https://docs.renovatebot.com/presets-schedule/#scheduleearlymondays) syntax

[Renovate] Schedule renovate update every Monday

---

webapp/components/test-file-results.js
webapp/components/wpt-flags.js

The reftest analyzer has been on by default for years; we're happy with
it and don't need this flag.

Remove deprecated useReftestAnalyzer flag

---

webapp/compat_2021_handler.go
webapp/components/compat-2021.js
webapp/routes.go
webapp/templates/compat-2021.html

This adds a (very) incomplete version of https://ecosystem-infra.github.io/wpt-results-analysis/compat
to wpt.fyi, at `wpt.fyi/compat2021`. The page currently is just static text, and is not yet exposed via
any UI. Later PRs will add the summary numbers, graph, and test list.

[compat2021] Add an initial `/compat2021` page

---

webapp/components/test/wpt-interop.html
webapp/components/wpt-flags.js
webapp/views/wpt-interop.js

This flag was never turned on, and the feature it hid was never
completed. We've since moved on from this view almost entirely, so
remove the dead code.

Remove deprecated interopScoreColumn flag

---

api/metadata_handler.go
api/query/atoms.go
api/query/atoms_test.go
shared/metadata.go
shared/metadata_test.go
webapp/components/test-search.js
webapp/components/test/test-search.html
webapp/components/wpt-metadata.js

This PR both adds the ability to search for test-level metadata (that is, metadata
that has no product associated with it), and stops test-level metadata showing up
for specific product searches.
To achieve this, we:
1. Expand the `triagedExp` atom on the front-end to also accept `test-issue` and
to convert it to an empty product.
2. Change `shared.GetMetadataResponse` to invert its handling of empty-product
metadata from matching any product to matching no products.
This does mean that for a request like: `"query":{"exists":[{"triaged":"test-issue"}]}` we
create N identical `query.Triaged` objects, one for each test-run in the query. This is
inefficient (because `triaged:test-issue` should not be bound to multiple runs), but is an
artifact of how `AbstractExists` works and is identical …

[triage] Add support for searching for test-level triage

---

webapp/components/test-file-results.js
webapp/components/wpt-flags.js
webapp/views/wpt-results.js

The use of the manifest in the frontend never shipped, and the flags are
off in prod and staging. This code is non-trivial and removing it makes
the code easier to understand.
The /api/manifest endpoint is not removed because it is still [used by
Bikeshed](https://github.com/tabatkins/bikeshed/blob/e797b9548c0bd140c9b1500809869b09f50f7d99/bikeshed/update/updateWpt.py)
and the [GitHub checks in wpt-metadata](https://github.com/web-platform-tests/wpt-metadata/blob/557b49eb329670395d90744b084869e848b268ac/test_paths_test.go#L30)
Updates #56

Remove the never-launched manifest frontend code

---

webapp/compat_2021_handler.go
webapp/components/compat-2021.js
webapp/templates/compat-2021.html

When 'embedded' is passed as a param, don't include the wpt.fyi header.
This is intended to be used for iframing the dashboard.

[compat2021] Add an embedded mode

---

webapp/views/wpt-results.js

In cf18d4857908847293741223559193b4755a019c, we removed the unused
manifest code. However we overlooked that there was an invisible
zero-width table column in existence for this unused feature, and when
it was removed the 'path' cell stretched too far.
Fix this by making the path column single-wide, not double.

Fix alignment of test results page

---

api/query/cache/lru/lru.go
api/query/cache/lru/lru_test.go

This PR tidies up the lru code a bit:
1. Correct the interface documentation to correctly describe its behavior.
2. Fully generalizes the naming to remove the assumption that the values
are run IDs (previously it was half general, half specific).
3. Extracts a variable to make the code clearer.
4. Fixes a test that was inherently flaky, as it relied on 0.5 * 2.0
being >= 1 when by floating point it could be slightly less than 1.

[code health] Tidy up the lru code

---

api/bsf_handler.go
api/labels.go
api/manifest.go
api/manifest/api.go
api/manifest/mock_manifest/api_mock.go
api/manifest_test.go
api/metadata_cache.go
api/query/query.go
api/query/query_test.go
api/query/search.go
api/query/search_medium_test.go
api/shas.go
api/versions.go
shared/cache.go
shared/datastore_cached.go
shared/datastore_cloud.go
shared/request_caching.go
shared/test_run_query.go

Since go 1.14 migration, we have migrated from Memcache to Redis. Rename all occurrences of memcache to redis.

Rename all Memcache to Redis

---

api/metadata_handler.go
api/metadata_handler_test.go

Cache a PR number and its pending metadata to Redis in a triage. If cache fails, the request still returns 200.
The TTL of pending metadata in Redis is 7 days. If a PR is still stuck in the wpt-metadata repo after 7 days, the PR should be removed from the pending metadata cache set. The pending metadata information is temporarily lost until the stuck PR is addressed.

[Triage Metadata] Cache pending metadata in a triage

---

api/query/cache/poll/poll.go
api/query/cache/service/app.staging.yaml
api/query/cache/service/app.yaml
api/query/cache/service/main.go
shared/cache.go
shared/metadata_util.go
shared/triage_metadata.go

Set up Redis in searchcache and remove no longer PRs and their pending metadata from Redis every 10 minutes.
[Instructions to set up Redis](https://cloud.google.com/memorystore/docs/redis/connect-redis-instance-flex). It should share the same Redis memorystore as webapp. 
Checked the log in staging using https://github.com/web-platform-tests/wpt-metadata/pull/1068

[Triage Metadata] Clean orphaned pending metadata in searchcache polling

---

api/receiver/client/client.go
webapp/components/test-search.js
webapp/components/wpt-flags.js

On <https://wpt.fyi/results/> I've noticed when clicking on "[`view the search documentation`](https://github.com/web-platform-tests/wpt.fyi/blob/master/api/query/README.md)" you'll be taken to the documentation, but a banner from GitHub distracts you, telling you've been redirected to the default branch. This PR removes the redirect by directly linking to the main branch (which is the default). I've also changed two other occurrences. The redirect was acknowledged in https://github.com/web-platform-tests/wpt.fyi/issues/2280#issuecomment-737269724, but I thought it would be nicer without it.
There are more links containing master linking to other repos. If you want me to I can check and change those too.
Not applicable, code is run as before, no change.
Not really applicable. While the …

Update three links to point to main branch instead of master, removing the redirect

---

webapp/components/compat-2021.js

This PR also:
1. Sets a max-width of 700px for the page (based on Una's old PR)
2. Centers the page.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/2494

[compat2021] Make the feature graph responsive to narrow layouts

---

shared/triage_metadata.go
util/docker-dev/run.sh

Skipping the PR template this time, sorry 0:-)
Following up #2497, finally.
Checked the [other five](https://github.com/web-platform-tests/wpt.fyi/search?q=%22blob%2Fmaster%22&type=) (as mentioned in https://github.com/web-platform-tests/wpt.fyi/pull/2497#issuecomment-805999071) as well, but those are currently still correct and without redirect. [`"tree/master"`](https://github.com/web-platform-tests/wpt.fyi/search?q=%22tree%2Fmaster%22) was only one.
Guess I was a bit eager because for some reason I thought there would be a lot more.
---
However I found hardcoded `master` while searching. I didn't dig in if thats correct or not (probably is currently correct, since otherwise you surely would have noticed because of failings builds or the like). Maybe just a heads up for the future if …

Update more links to point to main branch instead of master (follow up #2497)

---

webapp/package-lock.json
webapp/package.json

Reverts web-platform-tests/wpt.fyi#2551. Fix #2411. This upgrade causes the following error on the status page
Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".

Revert "Update dependency @vaadin/vaadin-grid to v20"

---

webapp/package-lock.json
webapp/package.json

Reverts web-platform-tests/wpt.fyi#2549. Fix #2411. This upgrade causes the following error on the status page
Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".

Revert "Update dependency @vaadin/vaadin-context-menu to v20"

---

Makefile
results-processor/app.yaml
util/deploy-staging.sh

Follow up for #2560. Increase the timeout to 300 seconds according to [the official doc](https://cloud.google.com/endpoints/docs/openapi/troubleshoot-aeflex-deployment)
[Latest processor deployment] has errors:
ERROR: (gcloud.app.deploy) Error Response: [4] Flex operation projects/wptdashboard-staging/regions/us-east4/operations/7aaf2005-f08f-469b-a1fc-8bdbd82b318d error [DEADLINE_EXCEEDED]: An internal error occurred while processing task /app-engine-flex/flex_await_healthy/flex_await_healthy>2021-06-30T03:13:09.949Z3699.xi.0: Your deployment has failed to become healthy in the allotted time and therefore was rolled back. If you believe this was an error, try adjusting the 'app_start_timeout_sec' setting in the 'readiness_check' section.
Also fix the deployment VERSION on the main …

 Increase app_start_timeout_sec in processor

---

webapp/views/wpt-results.js

fix: render missing tests gray

---

api/query/cache/service/app.staging.yaml

An attempt to fix https://github.com/web-platform-tests/wpt.fyi/issues/2617#issuecomment-930601372.
The max available memory_gb is [cpu * [0.9 - 6.5] - 0.4 = 2*6.5 - 0.4 = 12.6GB.](https://cloud.google.com/appengine/docs/flexible/nodejs/reference/app-yaml#resource-settings)

[Searchcache] Increase memory_gb to 10

---

webapp/wct.conf.json

Fix https://github.com/web-platform-tests/wpt.fyi/issues/2677. `wct --local chrome && wct --local firefox` isn't able to detect already installed selenium. To avoid that, turn off the selenium Installation check. 
To find out the root cause, we might need to file an issue. But no one seems to maintain https://github.com/Polymer/tools/tree/master/packages/web-component-tester any more.

Add skipSeleniumInstall and turn on verbose

---

webapp/components/compat-2021.js

STP is no longer blocked on WPT, so we now have up-to-date data.
See https://github.com/web-platform-tests/wpt/pull/30256
This reverts commit 9078a92d4e1c44cc360ffc146f24337aef36da71.

Revert "[compat2021] Add disclaimer for STP version (#2679)"

---

api/metadata_handler_test.go
api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/concrete_query.go
shared/metadata.go
shared/metadata_test.go
webapp/components/test-search.js
webapp/components/test/test-search.html

Add test labelling support for https://github.com/web-platform-tests/wpt.fyi/issues/1491.
- Add an optional `label` entry in Metadata `Link`.
- Add the ability to search triaged tests based on its `labels`. The label exists at the test-level (that is, metadata
that has no product associated with it), regardless of browsers. One test can associate with multiple labels.
On the [staging instance](https://metadata-label-dot-wptdashboard-staging.uk.r.appspot.com/results/css/css-align/gaps?q=testlabel%3Aexample-label1&run_id=5312968510144512), search `label:example-label1`, which should show a dummy data `gap-animation-001.html`
Support multiple labels

Add support for arbitrary labeling of tests  

---

api/query/atoms_test.go
api/query/cache/index/index_filter_test.go
shared/metadata.go
shared/metadata_test.go

Tweak Metadata label format per https://github.com/web-platform-tests/wpt-metadata/pull/2186. A follow-up for https://github.com/web-platform-tests/wpt.fyi/pull/2678. This PR includes
- Move metadata `label` field to a level above in the `link`
- Support multiple labels per test
- Add tests for `&` and '|` testlabel search logic for searchcache

Tweak Metadata label field and support multiple labels

---

shared/metadata.go
shared/metadata_test.go

Fixed a existing bug when constructing test-level metadata. The `break` was premature and likely carried over from the old code.
The issue is surfaced in [web-platform-tests/wpt-metadata#2196 (comment).](https://github.com/web-platform-tests/wpt-metadata/pull/2196#issuecomment-977133256)

Remove un-needed break for test-level metadata

---

api/azure/mock_azure/api_mock.go
api/checks/mock_checks/api_mock.go
api/manifest/mock_manifest/api_mock.go
api/receiver/mock_receiver/api_mock.go
api/taskcluster/mock_taskcluster/webhook_mock.go
shared/sharedtest/appengine_mock.go
shared/sharedtest/cache_mock.go
shared/sharedtest/datastore_mock.go
shared/sharedtest/fetch_bsf_mock.go
shared/sharedtest/github_oauth_mock.go
shared/sharedtest/metadata_util_mock.go
shared/sharedtest/run_diff_mock.go
shared/sharedtest/test_run_query_mock.go
shared/sharedtest/triage_metadata_mock.go

Running `./util/docker-dev/web_server.sh` produces these changes, which
are changing import order and adding punctuation. Commit these to get
fewer local changes in development.

Match auto-formatted style of Go code

---

Makefile
git/hooks/pre-push
util/commands.sh
util/deploy.sh

`realpath` was used in three places to get an absolute path to the repo
directory. We can use `git rev-parse --show-toplevel` for this instead
and avoid the dependency.
WPT_PATH was never used anywhere, and therefore removed.
In the pre-push script, commands.sh is sourced, so that will define
WPTD_PATH, so the redefinition can just be dropped.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/2743.

Replace realpath with git rev-parse --show-toplevel

---

webapp/components/wpt-header.js

At the same time, remove the link to the interop view, since this could
now easily be confused with Interop 2022. The view itself isn't removed,
but it hasn't been as valuable since we added the search cache and can
filter to different combinations of pass and fail directly.

Link to Interop 2022 in header navigation

---

webapp/components/interop-2022.js

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/2770.
Also tweak the footer text a bit to remove the "Source on GitHub" link
which is redundant with /about.

[Interop 2022] Replace hardcoded wpt.fyi links with relative links

---

webapp/components/interop-2022.js

As it turns out, https://wpt.fyi/interop-2022 has been live with first
copy-pasted version of the dashboard since Feb 2:
https://github.com/web-platform-tests/wpt.fyi/issues/2741
https://github.com/web-platform-tests/wpt.fyi/pull/2735
Since the URL has been linked in at least one place, empty the page to
avoid confusion.
Removing the route entirely would be another option, but then it would
just redirect to /results/interop-2022, which is not good either.

Make /interop-2022 just the "will launch soon" box

---

webapp/components/interop-2022.js

This centralizes the calculation into the place where it will be natural
to add in the investigation score.

Scale the Interop 2022 summary score to 90% in graph

---

Dockerfile

Node.js 10 is very old by now and not the version anyone is likely to be
using locally. Upgrade to avoid any problems this might cause in the
future.

Update Node.js to version 16 (LTS)

---

api/README.md
shared/fetch_bsf.go
webapp/components/compat-2021.js
webapp/components/interop-2022.js

Part of https://github.com/web-platform-tests/rfcs/pull/106.

Switch to the new location of BSF / Compat 2021 / Interop 2022 metrics

---

webapp/components/product-info.js

A temporary workaround for the `chrome_android` icon.

chrome_android icon workaround

---

api/README.md

The old example is 404, pointed out by @bkardell.

Update /api/runs example to use an existing run

---

webapp/components/product-info.js

Add a separate check for Chrome_Android. In some pages, it is looking for icons `chrome_android-dev_64x64` because it has channel

Add a separate check for Chrome_Android

---

webapp/components/test-file-results-table.js
webapp/components/test-file-results.js
webapp/components/test/test-file-results-table.html
webapp/views/wpt-app.js
webapp/views/wpt-results.js

fixes #2759 and #2667
This is a fix to ensure that the number of subtests shown in the blue banner matches of single test views will accurately represent the number of rows displayed to the user. Additionally, a "Total" row is added to subtest and directory views to display the aggregation of pass/total values of all of the tests numbers in the respective column.
~~**NOTE:** Issue #62 is still a problem for the aggregate number of subtests shown in levels higher than the subtest view, so this total will not match higher-level views by 1 in most instances.~~
Edit: This is a separate issue and this implementation has been removed from this PR.
- The top blue banner now correctly displays the number of subtests being displayed in the subtest view.
- A row displaying the fraction of …

Display test totals information on subtest and directory views

---

webapp/components/interop-2022.js

Swap the "How are these scores calculated?" and "Focus Areas" sections on the [Interop 2022 page](https://interop-section-swap-dot-wptdashboard-staging.uk.r.appspot.com/interop-2022).

Swap Interop 2022 sections

---

.gitignore
api/query/cache/service/.gcloudignore
results-processor/.gcloudignore
webapp/web/.gcloudignore

client-secret.json is needed for deploying not for runtime.
Details in #2906 found that it was being uploaded
Fixes #2906
Check #2906 for more details of the problem.
Added client-secret.json to .gitignore and .gcloudignore files for the various services
Before changes:
After changes:
The client-secret.json is gone now

Ignore client-secret.json from being committed or uploaded

---

webapp/components/self-navigator.js
webapp/templates/_ga.html
webapp/views/wpt-app.js

Part of #2916. Need to move to gtag.js. Instead of jumping straight to
gtag.js for Google Analytics 4, this work moves Universal Analytics to
use gtag.js. That we can test out the same functionality before point
the data to Google Analytics 4 without having to change the syntax.
A future PR will remove the Universal Analytics code.
- Add Google Analytics 4 tracking codes for prod and non-prod while also keeping the Universal Analytics code.
- Remove the analytics.js script and place the gtag script from the Universal Analytics dashboard
- Move the exception event handling to the gtag.js. Syntax is a little different. [Docs](https://developers.google.com/analytics/devguides/collection/gtagjs/exceptions)
- Changed Page View events [syntax](https://developers.google.com/analytics/devguides/co …

Move from analytics.js to gtag.js

---

results-processor/processor.py
results-processor/wptreport.py
results-processor/wptreport_test.py
shared/util.go
shared/util_test.go
webapp/components/test-file-results.js
webapp/components/test/test-file-results.html
webapp/components/test/util/helpers.js

Part of deprecating old summary formats. This change will now write new summary files with the `_v2` suffix, but will use any summary file, old or new. Additional checks will later be added to verify this suffix exists before using the file.
The plan is to ship this change and allow the new summaries to be written with the new filename, which will limit the need to delegate the work to the searchcache, as summary files are rarely referenced at later dates.

Write new summaries as "_v2"

---

webapp/package.json

#2955
The recent update of `cpy-cli` requires the path to be supplied with quotes.
Staging link: https://logo-fix-dot-wptdashboard-staging.uk.r.appspot.com/

Fix logo install errors

---

webapp/templates/_ga.html

This commit should be merged in once we are ready to fully move away
from Universal Analytics. The Google Analytics 4 tracking codes are
already in place from the work on #2917. This commit just removes
Universal Analytics
Closes #2916

Remove Universal Analytics tracking

---

webapp/package-lock.json

V2 is used by node v16 (npm v7) which we now use by default.

Upgrade to the backwards-compatible lockfile v2

---

webapp/.eslintrc.json
webapp/package.json

Needed for linting modern `assert {type: "json"}` imports.

Update lint parser

---

Makefile

The error message in #2985 suggests to try passing --fix-missing, which although I am not certain it will help, I confirmed that it doesn't hurt. Code spelunking indicates that this bit was added in #1165 without a lot of rigor anyway.

Fix missing dependencies when Chrome install fails

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/docker-update.yml

Upgrade to actions/checkout@v3, which runs node16 by default. Resolve following [warnings](https://github.com/web-platform-tests/wpt.fyi/actions/runs/3228727256):
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-
09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please 
update the following actions to use Node.js 16: actions/checkout, actions/checkout
```

Upgrade to actions/checkout

---

.github/dependabot.yml
.github/workflows/ci.yml

For security reasons, dependabot builds do not have access to the same secrets as a regular CI build. As a result, it cannot run gcloud tests properly. This patch ignores gcloud tests for dependabot builds.
Also, configure dependabot to ignore certain packages for /webapp. They were ignored in renovate previously. During the migration, they were only ignored for webdriver/ but not webapp/. This fixes that.

Ignore gcloud tests for dependabot & ignore certain npm packages

---

api/checks/jwt.go
go.mod
go.sum

Upgrade from 3.2.0 to 3.2.2
Release notes: https://github.com/golang-jwt/jwt/releases Did not update to version 4 because did not want to fix any breaking changes.
As noted in the release notes, the import path changed: github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt
https://github.com/web-platform-tests/wpt.fyi/security/dependabot/9

Fix https://github.com/web-platform-tests/wpt.fyi/security/dependabot/9

---

Dockerfile
api/query/cache/service/Dockerfile
webapp/web/app.staging.yaml
webapp/web/app.yaml

go1.19 went to Public Preview on app engine
https://cloud.google.com/appengine/docs/standard/go/runtime
This commit updates it.
The steps that were followed are at https://github.com/web-platform-tests/wpt.fyi/blob/main/docs/upgrading-go.md
Steps 3 & 4 were skipped because webplatformtests/wpt.fyi:latest is still go 1.16
Why is it safe to use go 1.19 on a bunch of go 1.16 packages? Go guarantees [backwards compatibility](https://go.dev/doc/go1compat) for all 1.x versions
This PR is part 1 of 2.

Upgrade to go 1.19

---

shared/sharedtest/util.go

More details in #3093
Turns out that even though we have "--no-store-on-disk" added to the datastore command, it still uses some default directory. 
Changes:
- In order to debug why the datastore is intermittently failing, print out the stdout and stderr of the command.
- Temporarily create a directory per time the datastore is created.
- I temporarily added a log to see when the datastore emulator started up / and torn down. If you check the logs for `removing data dir` now in this particular `go_test` [run](https://github.com/web-platform-tests/wpt.fyi/actions/runs/3795116942/jobs/6453905629), you will see that the datastore was being created multiple times.
- **HYPOTHESIS**: There is some clean up that did not happen properly whenever the emulator shut down with "--no-store-on-disk" …

Fix flaky tests that use datastore emulator

---

shared/browsers.go
shared/browsers_test.go
shared/product_spec.go
webapp/components/product-info.js

Add chrome_ios as a browser name in wpt.fyi.
We plan to publish wpt test results for chrome ios to wpt.fyi.

Add chrome_ios as a browser name

---

webapp/package-lock.json
webapp/package.json

So far the remaining vulns are for dev dependencies. This is to remediate the ones that can be safely.
- https://github.com/web-platform-tests/wpt.fyi/security/dependabot/2
- diff 3.2.0 -> 3.5.0
- https://github.com/web-platform-tests/wpt.fyi/security/dependabot/1
- growl 1.9.2 -> 1.10.0
- https://github.com/web-platform-tests/wpt.fyi/security/dependabot/46
- multer 1.4.2 -> 1.4.5-lts.1
- More about how it fixes it: https://github.com/expressjs/multer/issues/1173#issuecomment-1372021849

Fix any critical or high vulns

---

webapp/components/interop.js
webapp/static/interop-data.json

This PR adds MDN and spec links to the interop-data.json file for interop 2023. I picked the links by following the issue originally proposed. When I couldn't find a specific issue I used my working knowledge of the platform. Not sure if I got everything right. When there was more than one spec I did my best to pick the best entry point. Review appreciated.

add mdn and spec links to interop focus areas

---

webapp/components/interop.js

- Each table is now a `<table>`, instead of having a giant `<table>` with multiple tables
- `<thead>` is now used for each table header
- `<tbody>` is now used for each table body
- `<tfoot>` is now used for each table footer
This should improve accessibility a bit.

Improve Interop table markup

---

webapp/components/interop.js

This change fixes a small rounding error that caused the numbers in the table totals to sometimes differ from the summary number bubbles.
---
Before with rounding error:
After:

Fix small rounding error for Interop Dashboard

---

webapp/components/interop.js

Fixes #3114 
Small change that moves the "INTEROP" and "INVESTIGATIONS" labels below their summary numbers and adds a small amount of spacing between the summary number rows.
---
Before:
After:

Move interop and investigation label

---

webapp/components/product-info.js

Followup to #3161 updating the short display name for node.js.
cc @past @KyleJu

update shortVersion display for node.js

---

api/query/README.md

Explicit `and` doesn't appear to work.
Fix docs to not suggest using `and` keyword in the search query, since it doesn't work. Omitting it works.

README: Correct syntax for and-conjuction

---

docs/app-engine.md

The deployment steps currently assume you are either:
1.  logged in, or
- (works if deploying from local but not docker since the docker instance has a separate GCP profile),
2.  have a client-secret.json from the IAM GCP panel
- (works if for local or docker given the user has downloaded a client-secret beforehand)
This update ensures case number 1 works when running the docker instance by making users to log in using gcloud auth login

Update app-engine.md deployment instructions

---

docs/app-engine.md

For staging deployment, **app.staging.yaml** should be used instead of **app.yaml** for all three services. This instruction updates do not affect the existing CI deployment instructions, as CI uses the correct commands.
[This deployment instruction is tested on a Mac environment](https://pantheon.corp.google.com/appengine/versions?project=wptdashboard-staging&serviceId=default)

Update staging deployment instructions

---

Dockerfile
Makefile
api/query/cache/service/Dockerfile
docs/upgrading-go.md
go.mod
results-processor/Dockerfile
results-processor/README.md
results-processor/tox.ini
webapp/web/app.staging.yaml
webapp/web/app.yaml

- Upgrade to Go 1.20.1 and pin the patch version
- Upgrade to Python 3.9 and use the official Python image
- Get rid of the obsolete dependency on Python 2
- Upgrade to Debian 11 for local development
Further upgrades to Python 3.10+ would need an updated official Go image that doesn't exist yet. This should resolve most of issue #3033, modulo the dependabot change that will come in a future PR.

Make some Dockerfile maintenance improvements

---

Dockerfile
results-processor/Dockerfile

Use python3-crcmod apt-get package for results-processor and developer Dockerfiles
In the results-processor, `virtualenv` is not there by default. added `python3-virtualenv` to install it.

Use python3-crcmod apt-get package for results-processor and developer Dockerfiles

---

webapp/components/interop-data.js

See https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/3

Update score for Accessibility Testing (60%)

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

This change excludes `go_cloud_test`and `Deploy staging.wpt.fyi` CI checks for PRs coming from forked versions of the repo.

Skip cloud test and staging deploy on fork PRs

---

webapp/components/test-runs-query.js
webapp/components/test/test-runs-query.html

This PR removes `view=subtest` param from `/runs` query as mentioned in #3011 
https://user-images.githubusercontent.com/65391345/226902761-1513656b-0858-4bf4-8e1d-cba803e81d90.mp4

removed view param runs route

---

webapp/components/test-file-results-table.js
webapp/views/wpt-results.js

Fixes #3224 
Quick fix for an issue I found while doing some unrelated work. Avoids whitespace being underlined as part of the bug links.
Before:
After:

Remove whitespace from bug links

---

webapp/components/interop-dashboard.js

This PR adds sort functionality to the Interop 2023 dashboard in the Active Focus Areas table, a feature requested in #3117. By default the data will sort in ascending order by feature name. When you click the toggle above any data column, it will sort the features in ascending order. If you click a toggle on any column that is sorted in ascending order, it will re-sort into descending order.
This PR adds a row of buttons in the Active Focus Areas table header, as well as a click handler (`handleSortClick`) and a sorting method (`sortRows`)

Interop Dashboard Sort Functionality 

---

webapp/views/wpt-results.js

In the results analysis script, we currently do not zero out test scores that contained harness errors. This change updates wpt.fyi's aggregations to match the analysis script. This should remove anamolies that exist today on the "Test Totals" section of the page.

Do not zero out tests with harness errors in Interop view

---

webapp/components/interop-dashboard.js
webapp/static/expand_inactive.svg

This change takes the newly-added sorting functionality and makes some UX changes to make the table headers clickable rather than adding a new row of clickable arrows.
This PR:
- Moves the new click handler logic to the table headers rather than a new row of arrows.
- Displays an arrow at the top right of the column sorted by, indicating the direction of the sort.
---
The table is sorted alphabetically ascending by default.
Clicking a new column header will sort it in descending order.
Clicking a column header twice will sort the table in ascending order.

Adjust table sort UX

---

webapp/components/interop-data.js
webapp/components/test/interop-data.html
webapp/static/interop-data.json

Adds back the `interop-data.json` file by request, as it is being referenced by outside tooling. Also, adds a test to ensure that the data in `webapp/components/interop-data.js` matches the data in `webapp/static/interop-data.json`, so that any changes are made to both files.

add back interop-data.json

---

webapp/views/wpt-results.js

This change fixes the sorting functionality on the main results page, which was not working properly due to a bad reference to the `this` keyword.

Fix sorting on main results page

---

shared/browsers.go
shared/browsers_test.go
shared/product_spec.go
webapp/.gitignore
webapp/components/product-info.js
webapp/components/test/wpt-amend-metadata.html
webapp/components/wpt-amend-metadata.js
webapp/package-lock.json
webapp/package.json

This largely mimics what was done in #3161; let me know if I've missed anything.

Add "WebKit" as a product

---

.github/workflows/docker-update.yml

Fix CI issues in #3259. The error messages:
```
>> elgohr/Publish-Docker-Github-Action@master has been deprecated.
>> Please use elgohr/Publish-Docker-Github-Action@v4 for a blast in speed and security.
```

Upgrade Docker GitHub CI

---

.github/dependabot.yml
.github/workflows/deploy.yml
.github/workflows/docker-update.yml

Dependabot has been modified to ignore major and minor updates to docker images. Comments are in YAML as to why.
More details:
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?learn=dependency_version_updates&learnProduct=code-security#specifying-dependencies-and-versions-to-ignore
Also, change the docker update conditional to prevent pushing a docker image for the patch docker updates since dependabot does not have access to repo secrets

Fix dependabot docker update & docker update conditional

---

shared/triage_metadata.go
shared/triage_metadata_test.go

A part of https://github.com/web-platform-tests/wpt-metadata/issues/3954.  Add an "interop" PR label to metadata that is labelled "interop-*".
https://github.com/web-platform-tests/wpt-metadata/pull/4104

Detect interop-* triage metadata

---

shared/triage_metadata.go
shared/triage_metadata_test.go

Follow-up for #3275. Only label it when it prefixes with **interop-**

Tighten the interop label criteria

---

webapp/components/interop-data-manager.js

The `file an issue` `<a>` in the interop dashboard does not have its `href` attribute: 
The component reads `issueURL` from the year info. But the data manager was not creating this property by reading it from the data.

Fix the link to file an issue in the interop dashboard

---

webapp/components/test-search.js

Currently, navigating to a file-path with uppercase characters like `/encoding/encodeInto.any.html` does not work.  
Somewhat related issue: #3009 
Enter any file-path which contains upper-case characters into the search-box.
Local build vs production:
https://user-images.githubusercontent.com/11293086/230372141-ed486db7-25b1-483f-adec-f58e5a7f8a77.mp4
```javascript
matches = matches
.filter(p => p.toLowerCase())
.filter(p => p.includes(query))
``` 
Auto-complete options are generated from `matches`. I believe the intention here was to map all paths to a lower-case string and perform query matching. However, converting all paths to lowercase would cause further issues later (since the file-path is case-sensitive). Thus, the change was to perform case-insensitive query matching while …

Fix case-sensitive path matching for the search box

---

webapp/components/interop-dashboard.js
webapp/components/interop-data.js
webapp/static/interop-data.json

Fixes #3286
This change adds the stable or experimental labels to test results links on the Interop dashboard based on the view that the user is viewing. Previously, the "experimental" label was used for all links, even when viewing stable data.

Dynamically add stable or experimental labels to Interop Dashboard URLs

---

webapp/components/interop-dashboard.js

This PR adds a banner that displays on Interop dashboards for previous years noting that the user is viewing interop scores from a previous year, and contains a link to view the current interop year's dashboard.
The banner is displayed for Interop 2021 and 2022.
The banner does not display for Interop 2023.

Display a banner on dashboards for previous Interop years

---

api/query/atoms.go
api/query/atoms_test.go
webapp/components/test/test-search.html

Fix #3171. The and-conjunction likely stopped working since https://github.com/web-platform-tests/wpt.fyi/pull/1057. The issue never surfaced because `AND` is implied between query terms, and the top-level queries work properly without it.
and-conjunction does not work when it queries two or more distinct products. For example,  a simple query like `edge:pass and triaged:edge` works, but `edge:pass and triaged:chrome` does not work.
https://github.com/web-platform-tests/wpt.fyi/pull/1057 introduces the notion of `exists` root node, and `exists` is implied [unless another root node is specified](https://github.com/web-platform-tests/wpt.fyi/tree/main/api/query#root-queries), e.g. all, none. A query is parsed differently when `and` is explicit vs implicit:
```
assertQueryParse('chrome:pass …
```

Fix AND conjunction in query

---

api/query/README.md

Reverts web-platform-tests/wpt.fyi#3170. https://github.com/web-platform-tests/wpt.fyi/pull/3313 fixed the `and` issue

Revert "README: Correct syntax for and-conjuction"

---

webapp/components/test-runs.js
webapp/views/wpt-app.js
webapp/views/wpt-results.js

TestRunsQueryLoader is actually extended and used everywhere. So no parent objects actually need to be notified with an event listener.
---
Removed the notify from TestRunsQueryLoader
TestRunsQueryLoader is a base class that is extended by:
- TestRunsBase ('wpt-results-base') which is the parent class for
- TestFileResultsTable ('test-file-results-table'). Not wrapped or extended by anything else.. CONCLUSION SAFE.
- TestRunsUIBase, which is the parent class for:
- WPTRuns ('wpt-runs') - Has no parents. Not extended anymore. Only used by webapp/template/test-runs.html. notify does not go up.
- WPTApp ('wpt-app'). Conclusion: SAFE
- WPTResults ('wpt-results'). Used in wpt-app. Conclusion: NEED TO INVESTIGATE. Turns out that wpt-app has the testRuns already.

Remove notify for testruns.

---

.github/workflows/docker-update.yml

Currently docker-update GH action triggers on pushes to all branches [1] (The other GH workflows trigger on pushes only to the main branch [2][3])
As a result, the docker-update runs with the push event to dependabot's branch and it fails because it cannot access the credentials to push a docker image.
This change moves the conditional against dependabot to apply for all events against this repository instead of just for the pull_request event.
[1] https://github.com/web-platform-tests/wpt.fyi/blob/1824e41a7d02d33b90cc60c574a58551ee756391/.github/workflows/docker-update.yml#L3-L9
[2] https://github.com/web-platform-tests/wpt.fyi/blob/1824e41a7d02d33b90cc60c574a58551ee756391/.github/workflows/ci.yml#L4-L5
[3] https://github.com/web-platform-tests/wpt.fyi/blob/1824e41a7d02d33b90cc60c574a5855 …

Exclude dependabot from all events for docker-update GH action

---

api/test_history.go
webapp/components/new-test-results-history-grid.js
webapp/views/wpt-results.js

This PR alters the existing `/api/history` endpoint to accept POST requests rather than GET requests. This is due to GET requests supporting a finite URL length. The POST request body will give us more flexibility with what information can be sent along with the request.

Update history endpoint

---

api/test_history.go
shared/models.go
util/populate_dev_data.go
webapp/components/new-test-results-history-grid.js

This PR removes the `BrowserVersion` item in the `TestHistoryEntry` struct because it is not being used. It also renames the item `Browser` to `BrowserName` to better match naming conventions elsewhere in the project.

change testHistoryEntry format

---

shared/browsers.go
shared/browsers_test.go
shared/product_spec.go
webapp/components/product-info.js
webapp/components/wpt-amend-metadata.js

This change adds support for Chromium runs, which have not been ingested by wpt.fyi since the renaming of "chrome nightly" to "chromium nightly" in the WPT repo.

Add Chromium to wpt.fyi browsers

---

api/screenshot/cache.go
api/screenshot_redirect_handler.go
webapp/analyzer_handler.go

Fix CI issues in pending PRs. [Annotate](https://github.com/securego/gosec#annotating-code) the false positive G101 rules
```
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.54.2 for v1.54.2/linux/amd64
golangci/golangci-lint info installed /go/bin/golangci-lint
golangci-lint run ./api/...
api/screenshot_redirect_handler.go:28:2: G101: Potential hardcoded credentials (gosec)
bucket := "wptd-screenshots-staging"
^
api/screenshot/cache.go:76:2: G101: Potential hardcoded credentials (gosec)
bucketName := "wptd-screenshots-staging"
^
make: *** [Makefile:77: golangci_lint] Error 1
```

Exclude false positive gosec rule

---

webapp/components/new-test-results-history-grid.js
webapp/views/wpt-results.js

This PR solves issue #3446 where the same data was persisting for different tests. I solved this by checking for and clearing any existing data before running the query for new data. I also added logic to hide the history timelines when a new test page is visited after viewing a previous one.

Refresh history data when page is changed

---

api/test_history.go

This PR fixes issue #3462 sorting the datastore run results by date.

Add date sort to history handler

---

api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go

Fix https://github.com/web-platform-tests/wpt-metadata/issues/4665 and a part of https://github.com/web-platform-tests/wpt.fyi/issues/3448.  Probe directory tree for wildcard matching, regardless if a match has found. 
It should not have much performance impact before and after the change.

Probe directory tree for wildcard matching

---

util/deploy-production.sh

This shell script automates steps 1-3 of the production deployment instructions. I used it successfully for #3490 and I hope to add the remaining steps in the future.

Add a new script to automate prod deployment

---

webapp/components/new-test-results-history-grid.js
webapp/components/test-file-results.js
webapp/views/wpt-results.js

This PR fixes issue #3473 by correcting the order in which subtests appear. Previously they were appearing in alphabetical order. Now the subtest names are being imported from the row info on the table above, so they should appear in the same order.
Edit: Logic refactored to use event listeners instead of two-way data binding.

Correct subtest order

---

webapp/components/new-test-results-history-grid.js
webapp/views/wpt-results.js

Found a quick fix for a bug caused from a test having no historical data available. Also, an update to clean the subtest name the same new way that the processing script does.

No historical test data quick bug fix

---

api/README.md

(#3488) This adds documentation to the `/api` readme for the new test history endpoint.

Add documentation for /api/history

---

shared/browsers.go
shared/browsers_test.go
shared/product_spec.go
util/commands.sh
webapp/components/product-info.js

Remove the Chrome iOS product since the work to upload test runs will not be done any time soon.
Also remove an unused variable that was causing errors in hterm.

Remove the unfinished chrome_ios product

---

util/deploy-production.sh

This is useful for restarting a production deployment that was interrupted due to a transient or intermittent error. A common case is an internal error during 'make deploy_production' that disappears when retrying.
This was used successfully for #3584.

Add a flag to skip bug creation during deployment

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Since we don't control the OS versions we get from Azure, we can't guarantee there will be no conflicting versions.

Ignore version and os_build conflicts

---

webapp/components/product-info.js

Chrome Canary runs can have both the "nightly" and "canary" labels. Some special logic will label old "nightly" Chrome runs with the Chromium logo. Now that we're expecting to have canary runs for Chrome, the logic needs to be adjusted to not give Chrome Canary the Chromium logo.

Ensure Chrome Canary logo is used

---

webapp/components/wpt-header.js
webapp/interop_handler.go
webapp/interop_handler_test.go
webapp/routes.go

Fixes #3641
This change makes the `/interop` route redirect to the interop dashboard of the current active interop effort.

Add default Interop dashboard URL route

---

shared/web_features.go
shared/web_features_manifest_util.go
shared/web_features_manifest_util_test.go
shared/web_features_test.go

This commit introduces WebFeaturesData which is a struct that consumers of the web features data can use to check if a feature matches with a web feature.
This commit supports the initial v1 of the manifest file which will be generated during each WPT release
This commit excludes the GitHubDownloader to actually download from GitHub in order to make the PRs easier to review

Add WebFeaturesData container [Part 1/4]

---

api/query/README.md
api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/cache/poll/poll.go
api/query/cache/poll/poll_test.go
api/query/cache/service/main.go
api/query/concrete_query.go
api/query/web_features_manifest_cache.go
shared/web_features.go
shared/web_features_manifest_github_download.go
shared/web_features_manifest_github_download_test.go
shared/web_features_manifest_util.go
shared/web_features_manifest_util_test.go
shared/web_features_test.go

The service will now interpret a query that takes the form of feature:<web-feature-key>
Similarly to the searchcacheMetadataFetcher, there is now a searchcacheWebFeaturesManifestFetcher

Add support to search for web features in searchcache [Part 3/4]

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Adjust labeling logic so that:
- Chrome Canary runs are labeled as "experimental"
- New runs of Chrome Dev are no longer labeled with "experimental".
- Chrome Canary no longer has the "nightly" label.

Label Chrome Canary runs with "experimental" label

---

webapp/components/interop-dashboard.js
webapp/components/interop-data-manager.js
webapp/components/interop-data.js
webapp/static/interop-data.json

This change updates a number of focus area info links, as well as adding an additional link overall to the Interop 2024 focus areas README

[Interop 2024] Add mdn/spec links and focus area descriptions

---

webapp/components/interop-data-manager.js
webapp/components/wpt-header.js
webapp/interop_handler.go
webapp/interop_handler_test.go

Final settings to add Interop 2024 as the default interop dashboard

Set 2024 as default interop year

---

webapp/components/interop-data.js
webapp/static/interop-data.json

The DSD focus area contains a test outside of the `/shadow-dom/declarative` directory, which caused some confusion about which tests are part of the focus area. This change updates the link to navigate outside of the subdirectory to make all relevant tests visible.

Change Declarative Shadow DOM interop link

---

webapp/components/interop-summary.js

Updates the Interop dashboard to use a color based on a gradient when displaying the summary scores.
---
Example with 2024 Stable dashboard
---
Interop 2023 dashboard

Update Interop color logic for summary scores

---

webapp/wct.conf.json

The old headless mode is no longer maintained.

Use the new headless mode in Chrome

---

webapp/components/interop-data.js
webapp/static/interop-data.json

Closes https://github.com/web-platform-tests/interop/issues/630
This adds the missing URL for the accessibility area as the repo has now been created.
I also updated links for the other 2 investigation areas as the repositories have been renamed (the old name redirects to the new one, so the links were not broken)

Update the links for 2024 investigation areas

---

api/query/search.go
webapp/admin_handler.go
webapp/interop_handler.go
webapp/processor.go
webapp/test_runs_handler.go

As I am approaching the codebase to take care of the golint related issues that are currently open, I took care of some linter errors that came out through a dry run of golangci-lint.
Replaced string literals for HTTP methods and integers for status codes as required from the linter errors.
No requirements should be needed as this just replaces some parts of the code with an equivalent that is compliant with what I have read in the majority of the codebase.

Changed HTTP Status Codes and Methods with constants defined in http lib

---

Dockerfile
Makefile

Node.js 16 [reached the end of life](https://github.com/nodejs/Release) last November.

Upgrade node.js to version 18

---

webapp/components/interop-data.js
webapp/static/interop-data.json

This fixes the URL to use the actual repo name (the section for the 2023 data had the right URL)

Fix the URL for the accessibility investigation area

---

shared/params.go
shared/params_test.go
webapp/components/wpt-flags.js
webapp/views/wpt-results.js

Backend changes:
- Add "test" to the allowlist values for the view url parameter
- Add TestParseViewParam to assert behavior for existing view params and the new "test" parameter
Frontend changes:
- Add new Test View button
- Add test_view_ prefix. This prefix is used to keep track of the new view=test mode.
- Add new helper method isTestView() to support this new view
- Add helper method isInteropView to retroactively support the already supported interop view.
- Create getNodeTotalProp and getNodePassProp to encapsulate the logic of which property from the aggregation node to use.
About view=test mode
- Test pass is only counted if the number of subtest passes == the total subtests
- This should **not** display percentages. Only the counts from the first bullet point when at  directory …

Add support for view=test query parameter

---

webapp/components/test-results-history-timeline.js

The timeline is now populated using Canary runs rather than Dev runs.

Update Chrome logo in test history timeline

---

results-processor/README.md
results-processor/main.py

This should fix the related code scanning [alert](https://github.com/web-platform-tests/wpt.fyi/security/code-scanning/3).
I bet nobody is using the debugger at the moment, but at least leaving the parameter in the source will remind anyone who wants to do so in the future.

Disable local debug mode by default

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Removes references to deprecated edge_webdriver, which was removed from WPT Tests via https://github.com/web-platform-tests/wpt/pull/44233 back in Feb 2024. 
Also supports both edge and edgechromium as valid product names, as edgechromium is being renamed edge via https://github.com/web-platform-tests/wpt/pull/45959
Only files changed are in results processor, and only related to removing edge_webdriver and supporting both edge, and edgechromium.
No special requirements/configuration needed.

Remove edge_webdriver, and add support for edge as well as edgechromium in results-processor.

---

shared/test_run_filter.go

Currently it uses the `from` field after checking the to field

Fix to filter building for runs pagination

---

.golangci.yaml
Makefile
api/query/cache/backfill/backfill.go

https://github.com/golangci/golangci-lint/issues/4733. Fix linter failures temporarily

Temporary workaround for Linter err

---

api/query/README.md

These noticed have been there since 2019:
https://github.com/web-platform-tests/wpt.fyi/pull/1445
https://github.com/web-platform-tests/wpt.fyi/pull/1463
https://github.com/web-platform-tests/wpt.fyi/pull/1471
https://github.com/web-platform-tests/wpt.fyi/pull/1498
They've been stable since then, so not beta.
TODO
TODO
TODO
TODO

Remove beta notices for searchcache docs

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/deploy.yml
.github/workflows/docker-update.yml

I missed one more warning in our Actions page. Turns out that checkout v4 has been released.

Upgrade actions/checkout to v4

---

Dockerfile
api/query/cache/service/Dockerfile
go.mod
go.sum
webapp/web/app.staging.yaml
webapp/web/app.yaml

One of the last few PRs caused go to demand we run `go mod tidy`, which updated the Go version in go.mod. I went ahead and updated everything else in order to make that happen.

Upgrade Go to version 1.21

---

api/query/query.go
docs/upgrading-go.md
go.mod

Fixes a gosimple [lint error](https://github.com/web-platform-tests/wpt.fyi/actions/runs/10410088455/job/28831116906?pr=3948): "api/query/query.go:102:5: S1009: should omit nil check; len() for []int64 is defined as zero (gosimple)"

Remove a reduntant nil check

---

Makefile
api/query/cache/backfill/backfill.go
api/query/cache/index/index.go

Fix the int conversion warning in Linter, suggested in https://github.com/securego/gosec/issues/1185#issuecomment-2304307264. Nolint the intended use of int64 to int conversion

Fix the int conversion warning in linter

---

api/README.md
api/azure/webhook.go
api/ghactions/notify.go
api/ghactions/notify_test.go
api/ghactions/routes.go
api/receiver/api.go
api/receiver/api_medium_test.go
api/receiver/client/client.go
api/receiver/client/client_test.go
api/receiver/mock_receiver/api_mock.go
api/receiver/receive_results.go
api/receiver/receive_results_test.go
api/taskcluster/webhook.go
go.mod
go.sum
results-processor/processor.py
results-processor/processor_test.py
webapp/components/product-info.js

This is very much a derivative of the implementation used for Azure Pipelines, perhaps unsurprising given the similarity between the two systems, but is very much different enough to justify a totally separate implementation.
Like Azure Pipelines, we rely on a notification from the workflow that it is complete, rather than relying on webhooks from GitHub (as Taskcluster does), as this allows the workflow to provide metadata to endpoint, rather than having to hard code so many magic strings in wpt.fyi (notably, the name of the artifacts we're looking for).
I'm not really sure how best to test this, and am welcome to feedback here.
Fixes #3906.

Fix #3906: Implement a /api/checks/ endpoint for GitHub Actions

---

webapp/components/interop-dashboard.js
webapp/views/wpt-app.js

This change adds a banner across the front page and interop dashboard page of wpt.fyi to direct users to more information about proposal submission for Interop 2025. 
This is a simple update, and any design or wording choices can be changed as needed or directed.
Note that this change should be cleanly reverted once the proposal period has ended.

Add Interop 2025 proposal submission banner

---

webapp/web/main.go

This was omitted before and means the path currently fails.
See, e.g., https://github.com/web-platform-tests/wpt/actions/runs/10894890454/job/30236033515

Call ghactions.RegisterRoutes()

---

webapp/web/main.go

Per the mux docs, "Routes are tested in the order they were added to the router. If two routes match, the first one wins."
This means that `checks.RegisterRoutes()` needs to be called after everything else defining a route in /api/checks/ as it otherwise matches every path under /api/checks/.
Fixes #4009; see also #4010. @past said in the latter said:
> > Oh, that would probably work, too.
> 
> Turns out it doesn't and I don't know why.
In way of minimal testing:
```
gsnedders@gsnedders-milk wpt.fyi % curl -v -Li --data-urlencode 'run_id=10906214822' --data-urlencode 'owner=web-platform-tests' --data-urlencode 'repo=wpt' --data-urlencode 'artifact_name=safari-technology-preview-results-%2A' 'http://localhost:8080/api/checks/github-actions/'
* Host localhost:8080 was resolved.
* IPv6: ::1 …
```

Fix #4009: reorder the registration of routes

---

api/ghactions/notify.go

It turns out logging lines like `Skipping artifact %!s(*string=0xc0009bede0)` aren't super useful.
c.f. https://github.com/web-platform-tests/wpt.fyi/issues/4020#issuecomment-2375499942

Fix logging from github-actions

---

results-processor/processor.py

Sometimes (e.g., from GitHub Actions), we might get passed a URL to process which on api.github.com, which requires a token to access. Thus, we should pull down our GitHub token and add that as a header.
See also https://github.com/web-platform-tests/wpt.fyi/issues/4020, which this hopefully fixes.

[results-processor] Provide GitHub token for api.github.com

---

webapp/components/interop-data.js
webapp/static/interop-data.json

Without the labels present here, consumers of this JS/JSON data had two choices: one was to rely on the fact this data is implicitly in this file (within the `tests` URL), and the other was to pull down the category-data.json file from the results-analysis repo which explicitly contains the focus area to label mapping (but does not contain data like "what is an active focus area").

Add labels to interop-data.{js,json}

---

api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go

Per https://web-platform-tests.org/writing-tests/file-names.html, tentative can be set at a directory level via the directory being called "tentative".
https://wpt.fyi/results/css/css-borders?label=master&label=experimental&aligned&q=is%3Atentative notably misses the entire "tentative" directory.

Make is:tentative match tentative directories

---

results-processor/processor.py

Fix an issue in https://github.com/web-platform-tests/wpt.fyi/issues/4020. The self.datastore.get(key)['Secret'] should be capitalized. See [here](https://pantheon.corp.google.com/datastore/databases/-default-/entities;kind=Token;ns=__$DEFAULT$__/query/kind?inv=1&invt=Abe2ew&project=wptdashboard)

[Processor] Correct cap for secret access

---

api/ghactions/notify.go

We don't actually really care, provided the workflow was run against the right thing.
Fixes #4063. If we were to stick with `workflow_run` for https://github.com/web-platform-tests/wpt/issues/48659, we would end up with this being wrong (as we couldn't trust the Workflow Run metadata from GitHub then), but I don't think we are.
And, importantly, this gets runs actually showing up.

Be lax about what event triggered a workflow for the `master` label

---

webapp/components/interop-dashboard.js
webapp/components/interop-data-manager.js
webapp/components/interop-data.js
webapp/components/interop-summary.js
webapp/components/wpt-flags.js
webapp/interop_handler.go
webapp/interop_handler_test.go
webapp/static/interop-data.json

This change pulls mobile results data from the [interop-results repo](https://github.com/jgraham/interop-results) and uses it to display a new mobile results view on the Interop dashboard. The mobile results view can only be seen by toggling a flag in `/flags`.
https://github.com/user-attachments/assets/afeef440-e2f3-4727-8e13-4132cbd028dc

Add experimental interop mobile results view

---

webapp/components/interop-data.js
webapp/static/interop-data.json

This appears to have been omitted, while I believe everything else is present.

Add interop-2023-webcomponents as a previous focus area in 2024

---

webapp/components/interop-dashboard.js
webapp/components/interop-data.js
webapp/components/interop-summary.js
webapp/static/interop-data.json

Small change to add the "Interop" and "Investigations" scores to the mobile results view, as well as the Investigations scores table.

Add interop and investigation scores to mobile results

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

Fixes #3187.
The idea that I had in that issue doesn't work for a number of reasons. I will note that docker-update.yml runs not only for `Dockerfile` changes, but also for `.github/workflows/docker-update.yml` changes, which doesn't apply in this case.

Use the new docker image on PRs that change it

---

webapp/views/wpt-results.js

Resolves #1783/#2217 by adding a grey background to every other row in the table.
Before/after:
Untested because I'm on NixOS and Docker isn't trivial, though based on #3840 I'm guessing it wouldn't have worked anyway. The above screenshot was taken by adding the rule via the dev tools.
idk man
Added a single CSS rule. edit: two now
N/A

Add subtle striping for table in `<wpt-results/>`

---

Makefile

Works around #4129. Note that the dashboard is working fine with M131, it's only the test that is failing.

Pin Chrome to make go_chrome_test work again

---

webapp/views/wpt-results.js

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/4107
The test results page was handling score rounding slightly differently than the interop dashboard (rounding to the nearest whole percent rather than nearest tenth of a percent). In order to avoid rounding up to 100% in cases where there were still some tests/subtests failing, [some logic was added to instead display the score as 99.9% in those cases](https://github.com/web-platform-tests/wpt.fyi/blob/b2c8fe3da11a55d5ad22f8d2d89b2f45c1fad94f/webapp/views/wpt-results.js#L1191-L1193). This created a situation in which the interop dashboard and the results page looked close enough to each other (99.7% vs. 99.9%) that it seemed as if there was a calculation error on one of the pages. I hadn't looked at this logic in some time and …

Update rounding logic for results page

---

webapp/components/interop-data.js
webapp/static/interop-data.json

A Github action that imports Wasm core tests into WPT is up for review in https://github.com/web-platform-tests/wpt/pull/49277.
Per the [scoring guidelines](https://github.com/web-platform-tests/interop-2024-wasm?tab=readme-ov-file#scoring), this is worth 1/3 of the overall score for this investigation.

Update Wasm testing investigation score to 33.3%

---

webapp/views/wpt-results.js

Fixes #4107 
This change removes totals percentage rounding up when aggregating the interop percentages on the test results page. The first fix landed for this still utilized rounding to the nearest tenth of one percent, which is not in line with the actual interop score aggregation, [which does not implement any rounding up](https://github.com/web-platform-tests/results-analysis/blob/d64417c4761ead5058c6470be99d5b8ea68aa0e5/interop-scoring/main.js#L245-L247).

Remove rounding on interop test results totals cells

---

webapp/components/test/wpt-app.html

Fixes #3090. 
The error happens when the fetches are executed after the top-level [suite](https://github.com/web-platform-tests/wpt.fyi/blob/c96d81c013414e912bb21b25586630c31df02102/webapp/components/test/wpt-app.html#L29) is done (after the top-level [teardown()](https://github.com/web-platform-tests/wpt.fyi/blob/c96d81c013414e912bb21b25586630c31df02102/webapp/components/test/wpt-app.html#L47) has been called), but before the test is finished. It seems that [suiteSetup()](https://github.com/web-platform-tests/wpt.fyi/blob/c96d81c013414e912bb21b25586630c31df02102/webapp/components/test/wpt-app.html#L22) is mostly redundant since there is only one parent suite() in the file and it already throws for captured URLs.

Remove redundant suiteSetup since there is only one top-level suite

---

webapp/components/interop-dashboard.js
webapp/components/interop-data.js
webapp/static/interop-data.json

This is a small change that adds a separate field to `interop-data.js` in order to populate the mobile test results links with new links that navigate to results that are congruent with the main browsers displayed on the mobile results page.

Add separate results links for mobile results

---

webapp/components/interop-data.js
webapp/static/interop-data.json

The PR that imports Wasm tests was merged in https://github.com/web-platform-tests/wpt/pull/49277 and is now approved and running.
Per the [scoring guidelines](https://github.com/web-platform-tests/interop-2024-wasm?tab=readme-ov-file#scoring), this is worth 1/3 of the overall score for this investigation.
CC @dschuff, @ajklein

Update Wasm testing investigation score to 66.6%

---

webapp/components/test/wpt-flags.html
webapp/components/wpt-flags.js
webapp/package-lock.json

Added a test for the persistence of flags. This is another step in the migration from Polymer to Lit.

Use one-way bindings for the flags component

---

webapp/components/loading-state.js

Also, make some code health improvements while I'm here:
- Mark private methods with an underscore
- Use console.error for error messages
- Use numerice comparison for numeric variables
- Make isLoading read-only
- Add comments

Use one-way binding for loading-state

---

webapp/components/test-file-results-table.js
webapp/components/wpt-amend-metadata.js
webapp/components/wpt-metadata.js
webapp/views/wpt-results.js

This migration was a bit larger than usual due to the fact that the metadata component and the triage component interact so closely. The main changes are:
- Removal of `notify: true` and change double angle brackets to double brackets.
- Use get/set to let Polymer properly detect array property updates.
- DOM manipulation logic is now encapsulated within methods to better adhere to Polymer's data flow principles.

Use one-way bindings for wpt-metadata and wpt-amend-metadata

---

api/README.md
api/metadata_handler_test.go
api/query/README.md
webapp/components/test/test-search.html
webapp/components/test/wpt-amend-metadata.html
webapp/components/wpt-amend-metadata.js

I noticed that the triage UI search functionality is currently broken for Chromium, in that the query to search for bugs mentioning the selected file name results in a search for all open bugs. This is caused by the migration from Monorail to Buganizer, which uses slightly different paths.
I took the opportunity to update all Chromium bug tracker URLs to the new format, with the exception of those in `metadata_util_test.go` that are trying to match the data included in an old archive from wpt-metadata. Arguably the test should be rewritten to not rely on explicit string values in those fields, but it doesn't seem very useful to update the actual archive as well to really eliminate every old URL instance.

Chromium bug searches should use the new URL

---

Makefile

On pr #4227 the tests are failing because the download of firefox fails:
```
2025-02-04T19:10:22.4216170Z if [[ "$(which bzip2)" == "" ]]; then sudo apt-get install -qqy --no-install-suggests bzip2; fi
2025-02-04T19:10:22.4241117Z if [[ "$(which wget)" == "" ]]; then sudo apt-get install -qqy --no-install-suggests wget; fi
2025-02-04T19:10:22.4263913Z if [[ -z "$(which firefox)" ]]; then \
2025-02-04T19:10:22.4264789Z 	wget -O firefox.tar.bz2 -q "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"; \
2025-02-04T19:10:22.4265763Z 	mkdir -p $HOME/browsers; \
2025-02-04T19:10:22.4266220Z 	tar -xjf firefox.tar.bz2 -C $HOME/browsers; \
2025-02-04T19:10:22.4266812Z 	sudo ln -s $HOME/browsers/firefox/firefox /usr/bin/firefox; \
2025-02-04T19:10:22.4267281Z fi …
```

Fix download of firefox for the tests: it is now a tar.xz file

---

webapp/routes.go
webapp/web/app.staging.yaml
webapp/web/app.yaml

Implements handlers for the default liveness and readiness checks in the webapp, just like we do in the searchcache service.

Add handlers for App Engine liveness and readiness checks

---

util/deploy-production.sh

According to https://cloud.google.com/appengine/docs/flexible/known-issues we should be waiting 15 minutes before redirecting traffic in order to avoid some 500 errors. We might choose not to do that in some instances when urgent deployments need to happen, so I just made it a notice in the prompt.

Add a notice to wait 15' before redirecting traffic

---

webapp/web/nginx.conf

According to the docs, if we set client_max_body_size to 0, it won't check the size. This will make the behavior like before.
https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size:~:text=Setting%20size%20to%200%20disables%20checking%20of%20client%20request%20body%20size
TODO
TODO
TODO
TODO

Disable nginx body check

---

webapp/components/interop-data.js
webapp/static/interop-data.json

Some suggested name changes ahead of the release of the Interop 2025 dashboard. Additionally, adding some proposal links for the investigation areas.

Focus area name changes

---

webapp/web/app.staging.yaml
webapp/web/app.yaml

The current webapp VM configuration is:
```
automatic_scaling:
cool_down_period: 120s
min_num_instances: 2
max_num_instances: 20
cpu_utilization:
target_utilization: 0.5
```
This change removes the `instance_class` that is only applicable to the standard environment (c.f. [flex docs](https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=go)), doubles the minimum number of instances and increases the cool down period to avoid health check errors during instance initialization.

Increase the min number of instances and the cool down period

---

webapp/components/interop-data.js
webapp/static/interop-data.json

More focus area name changes to match the names in the newly landed documentation:
https://github.com/web-platform-tests/interop/tree/main/2025

Interop 2025 naming changes

---

webapp/components/interop-data.js
webapp/static/interop-data.json

For the dashboard to work, names need to be the same between the table sections and the investigation scores.
For now, all investigation areas have `#` as link on the dashboard because the corresponding info is not found (they would also fail to display a score, even though this is not yet different as no investigation area has a score registered yet)
I updated the `investigation_scores` section to use the same names that table sections.
n/a

Fix the info about investigation areas

---

webdriver/package-lock.json
webdriver/package.json

A month ago flags [migrated](https://github.com/dpup/node-flags?tab=readme-ov-file#package-name-update) to flg, and a couple weeks ago @vercel/flags [became](https://vercel.com/changelog/npm-i-flags) flags. This was enough to confuse dependabot into generating #4287, but this PR implements the proper migration.

Bump flags 0.2.2 to flg 3.0.0

---

webapp/components/test/wpt-results.html
webapp/views/wpt-results.js

Moves isMissing logic to a common method. It will continue to be used for calculating whether we have a single subtest. Additionally, it will be used with the new logic for view=test. Without this check, we will add missing tests as passing tests.
More details in #4293 
Fixes #4293

Add & use isTestMissing helper when calculating passes in view=test

---

results-processor/app.staging.yaml

We often get alerts due to the results-arrival queue depth exceeding the alert threshold for a long time. Given that task queue configuration is the same across staging and production, let's try to use more CPU for staging to avoid that problem.

Use the same number of processor instances in staging as in prod

---

webapp/components/interop-data.js
webapp/static/interop-data.json

In #4297 I [discovered](https://github.com/web-platform-tests/wpt.fyi/issues/4297#issuecomment-2707387033) that the 2025 focus areas links don't show results from aligned runs. This appears to be the intention according to the [Interop 2025 README](https://github.com/web-platform-tests/interop/blob/main/2025/README.md?plain=1) file. This PR fixes that, as well as a broken mobile view link.

Use aligned runs for focus area links in 2025

---

shared/params.go
shared/params_test.go

webkitgtk and wpewebkit nightly versions have the following format: `wpewebkit-2.49.1 (294826@main)` where `2.49.1 (294826@main)` is the version.
This is the standard naming on the WebKit repository where each commit on the main WebKit branch has a unique identifier of `number@main`.
However, the current version/sha parser expects the WPT Git SHA identifier to be passed after an `@`.
This patch improves the parser to ignore the first `@main` in the identifier string, allowing it to get the right version and also the optional SHA.

Improve support for parsing WebKit Nightly versions and SHAs

---

.github/dependabot.yml
webapp/web/Dockerfile

Also add the Dockerfile to the dependabot config so that it will update automatically in the future (added the same comment used for other Go Dockerfiles).

chore: bump webapp Dockerfile version

---

Dockerfile
api/query/cache/service/Dockerfile
go.mod
go.sum
webapp/web/Dockerfile

This bumps go to the most recent version, from 1.24.6 to 1.25.0 so that PR #4503 can be merged.
Updated references to the go version in go.mod and the Dockerfile files, and ran go get -u ./...

Update go to 1.25.0 to unblock PR 4503.

---

webapp/components/test/test-runs-query-builder.html

We talked about #4372 during the Septemeber WPT infra meeting. However, the checks had not run for it. And there was a broken test.
This change fixes it. It is similar to https://github.com/web-platform-tests/wpt.fyi/pull/2791

Fix broken test from #4372

---

api/query/search.go

The searchcache service returns a 422 Unprocessable Entity status when one or more requested test runs are not in its in-memory index. This is a cache-miss scenario, not a critical error.
This change reduces the log severity for these specific 422 responses from ERROR to WARNING to avoid unnecessary noise in the error logs.

Reduce log severity for searchcache cache misses
