web-platform-tests/wpt.fyi

- .travis.yml
Gets rid of the extra build for PRs as discussed in https://github.com/web-platform-tests/wpt.fyi/pull/40#pullrequestreview-111399400
> Only trigger Travis for the master branch

- util/populate_dev_data.go
- webapp/anomaly_handler.go
- webapp/interop_handler.go
> Update wpt/results-analysis packages

- README.md
(Doesn't fix https://github.com/web-platform-tests/wpt.fyi/issues/51.)
> Remove bits of README.md with broken run.py links

- webapp/templates/_footer.html
- webapp/templates/anomalies.html
- webapp/templates/caveat.html
- webapp/templates/index.html
- webapp/templates/interoperability.html
- webapp/templates/test-runs.html
Drive-by: Web Platform Tests -> web-platform-tests
> Have the caveat/disclaimer only appear once, at the top

- .travis.yml
Travis config change: Specify golang 1.10
None
Travis config change: Specify golang 1.10
None
> Travis config: Same golang version as AppEngine: 1.10

- util/deploy.sh
Removes some debugging flags that were added while trying to diagnose the deploy in Travis.
Also, fixes some bugs with `exit` on cancellation (was only working because of `set -e` and a nested exit)
Note that `-q` is taken from `gcloud app deploy` for consistency.
> I don't approve this flag name.
_Me, just now_
> Remove deprecated changes from deploy.sh

- util/docker-dev/run.sh
Re-uses the existing wptd-dev-instance if it exists. We sometimes have old instances hanging around.
> run.sh: Re-use already running image

- util/logging.sh
Small tweak to the way that `confirm` helper is done to get a sweet newline.
> Use -p on the read to improve output appearance

- .travis.yml
Prevents unnecessary bloat of the versions in appengine.
> Don't deploy to staging unless webapp folder changed

- shared/browsers.go
See https://github.com/web-platform-tests/wpt.fyi/issues/144
> Add v 16 + 17 to Edge browser entries

- Makefile
- util/deploy.sh
Pushing to prod highlighted some bugs in the script.
> Fix deploy.sh issues

- .travis.yml
- Makefile
- git/hooks/pre-push
- webdriver/install.sh
After fixing HTML imports in Firefox, the webdriver tests are happy again.
> Re-enable integration tests

- .vscode/settings.json
Ensures vscode user's Golang test integration works as intended :)
> Add shared project vscode settings

- util/travis-deploy-staging.sh
Manifests as a 404 for the GitHub API POST request:
{ [data not shown]
100   228  100   121  100   107    821    726 --:--:-- --:--:-- --:--:--   823
* Connection #0 to host api.github.com left intact
{
"message": "Not Found",
"documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}
https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/383445159
> No github comment on master branch

- shared/util.go
- webapp/components/runs.html
- webapp/components/wpt-results.html
- webapp/templates/index.html
- webapp/test_results_handler.go
Resolves #188 for the `label` param.
Pipe through the param and append it when navigating.
https://label-param-persist-dot-wptdashboard-staging.appspot.com/results?label=chrome
> Preserve the label param

- .travis.yml
Something was wrong with the conditions. The two staging deployment should never run at the same time.
Travis docs: https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
// Not sure if this will fix the problem. Let's wait for the Travis build.
> Try to fix Travis staging deployment

- results-processor/Dockerfile
This fixes #203. See the comment in Dockerfile for details.
> [processor] Remove the cached gce flag in Docker

- shared/models.go
Alias for a `[]TestRun` with a helper method for getting IDs from the entities (in one line).
> Add TestRuns helper type

- shared/fetch_runs.go
Return the `[]TestRun` helper type `TestRuns` when fetching the latest runs.
> Return TestRuns for FetchLatestRuns

- Dockerfile
- util/docker-dev/run.sh
This reverts commit a2b3f48b6f72d6be876c56d420762ee01f974af1. (PR #230)
> Revert "Mount volume that includes local Go code for results-analysis (#230)"

- shared/models.go
Follow on from #231  towards supporting https://github.com/web-platform-tests/results-analysis/pull/39
> Add shared.TestRunIDs helper

- api/README.md
PR aims to address some of the issues listed in https://github.com/web-platform-tests/wpt.fyi/issues/224
> Improve API docs

- Makefile
- util/docker-dev/run.sh
Re-attempt at #230, which hides the behaviour in a flag (so as to not affect travis).
> Add a flag to run.sh that mounts the results-analysis dir too

- api/receiver/results_receiver.go
- api/receiver/results_receiver_test.go
Add a missing assignment along with a test for it.
> [receiver] Use the username of basic auth as the uploader

- util/deploy.sh
- util/travis-deploy-staging.sh
Instead of running `gcloud app versions` again, which fixes #191.
Perhaps just land it and see how the master build goes?
> Grep URL from the output of `gcloud app deploy`

- api/README.md
- webapp/components/wpt-results.html
Adds `visual` to the listed set of test types in the manifest.
> Add visual test type

- Makefile
Similar to https://github.com/aledbf/ingress-nginx/commit/c680112405d4d37a2c07142722f21a9a4c588eab
> Workaround golang/go#25872

- util/travis-deploy-staging.sh
Travis deploy announcer: Depend on whole revisions dir
> Travis deploy announcer: Depend on whole revisions dir

- results-processor/main.py
Fix #275 and catch future exceptions.
Although the [documentation](https://cloud.google.com/storage/docs/gsutil/commands/rsync) of `gsutil rsync` gives examples like `gsutil rsync -r data gs://mybucket/data`, this won't work if a file that matches the prefix (e.g. `gs://mybucket/data.txt`) already exists in the bucket.
The workaround is to add a trailing slash to the destination to force it into a directory.
> Fix an edge case in `gsutil rsync` about subdirs

- revisions/api/handlers/latest_test.go
- revisions/api/types.go
Announcer API output: comit timestamps in UTC
> Announcer API: Marshal timestamps in UTC

- webapp/components/anomalies.html
This fixes #296 , but ideally we should add WebDriver tests for the view like #269 .
Check out `/anomalies` once the staging deployment is up.
> Fix anomalies view

- revisions/epoch/gregorian.go
- revisions/epoch/gregorian_test.go
> Announcer: Weeks start Monday

- Makefile
- webapp/package-lock.json
- webapp/package.json
Fixes #256
`npm update` output:
+ web-component-tester@6.7.0
added 9 packages, removed 47 packages and updated 191 packages
(Waiting for Travis to pass)
> Update node packages

- webapp/templates/admin_upload.html
Try the `/admin/results/upload` page once the staging instance is up.
> Add labels fields to admin upload page

- webapp/bower.json
- webapp/components/interop.html
- webapp/components/path-part.html
- webapp/components/results-navigation.html
- webapp/components/wpt-results.html
Adds "tabs" at the top of the `wpt-interop` and `wpt-results` elements that link to each other.
See auto-deployed environment.
> Add interop tab

- .travis.yml
First step of #319 , I'm expecting the Travis deployment job to *fail*.
Meanwhile, I'm investigating the actual failure itself.
> Make Travis fail when deploy fails

- webapp/components/interop.html
- webapp/components/test-file-results.html
Add individual (sub)test results to bottom of interop view iff view is at the file level.
> Add test file results to interop view

- Makefile
- util/docker-dev/run.sh
Otherwise we can end up in an annoying broken state.
> Update stuff when you start running docker

- Makefile
- webapp/components/wpt-runs.html
- webdriver/search_test.go
- webdriver/test_runs_test.go
Adds an integration test that would have caught the breakage, then fixes the breakage.
Fixes #360
> Fix test-runs

- shared/params.go
- shared/params_test.go
Fixes #366 . Deflake a unit test.
> Serialize labels deterministically

- util/docker-dev/dev_data.sh
I forgot to remove these in #348. I've tested it locally.
> Remove some out-of-date warnings about creds

- webapp/components/interop.html
- webapp/components/path-part.html
- webapp/components/results-navigation.html
- webapp/components/self-navigator.html
- webapp/components/test-file-results-time-series.html
- webapp/components/test-file-results.html
- webapp/components/test-runs.html
- webapp/components/wpt-results.html
Fixes #362 .
Navigate to `/dom/idlharness` and click around. Everything should work.
> Support test names with query strings

- webapp/components/interop.html
- webapp/interop_handler.go
- webapp/templates/interoperability.html
- webdriver/label_test.go
- webdriver/webdriver.go
Merge of #384 and #383 (with a small amount of clean-up).
See auto-deployed enviroment.
> Propagate params to interop, fetch from the client

- webdriver/file_results_test.go
Follow up for #390 - adding a test that would have caught the regression.
> Add integration test for test-file-results

- webapp/components/test-file-results-table-terse.html
- webapp/components/test-file-results-table-verbose.html
Fixes #420. Badly. There are still layout differences, but there are fewer and they don't involve font size.
> Slightly better table layout consistency

- api/README.md
Correct some minor editorial errors in the documentation of the revision announcer.
(none)
Just the docs
(none)
> Revision announcer docs

- Makefile
- api/results_redirect_handler.go
- shared/params.go
- webapp/test/interop.html
- webapp/test/test-file-results.html
- webapp/test/test-runs.html
- webapp/wct.conf.json
- webdriver/chrome.go
- webdriver/file_results_test.go
- webdriver/firefox.go
- webdriver/install.sh
- webdriver/search_test.go
- webdriver/test_runs_test.go
(This is a painful fix...)
I tried my best to split commits logically and write plenty of explanation in the commit messages. Please review commit by commit and pay attention to the messages (and merge by rebasing).
I also tried to fix the actual tests that have been broken for a supposedly long time, but unfortunately I couldn't hone up my modern JavaScript & Web Component skills fast enough and there are simply too many failures -- many tests are quite outdated and need to be completely rewritten. Therefore, after spending one whole day of trying, I decided to skip the failing tests for now and fix the setup first to stop further bleeding.
> Fix the setup of integration tests and skip failing tests

- Makefile
- webdriver/chrome.go
- webdriver/firefox.go
- webdriver/search_test.go
- webdriver/test_runs_test.go
- webdriver/webapp_server.go
- webdriver/webdriver.go
This PR is based on #439 . I plan to merge that one first, and rebase this PR onto master.
This PR improves the setup of our WebDriver tests and fixes the broken tests disabled in #439.
Again, please review commit by commit.
> Fix and re-enable WebDriver integration tests

- webapp/components/test-runs.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/441.
> Use ?complete=true as default query for /api/runs

- webapp/components/wpt-results.html
`wpt-results` must filter search results in `computeDisplayedTests`
> Fix history chart

- webapp/components/test-results-chart.html
- When hidden, issue waning with 'Show anyway' button
- Reset 'Show anyway' state when tests, chunkSize, labels, or isFeasible changes
Do over of #357.
> Fix up result history chart UX

- util/populate_dev_data.go
> Fail nicely when an attempted run fetch fails.

- util/travis-deploy-staging.sh
Do an inverted `egrep` on `_test.go$` (and, webapp/components/test/ for webapp)
> Ignore tests when deciding whether to deploy

- webapp/components/test-file-results-table-terse.html
- webapp/components/test-run.html
- webapp/components/test/test-file-results-table-terse.html
- webapp/components/test/test-file-results.html
- webapp/components/test/test-runs.html
- webapp/components/test/util/helpers.html
Re-enables more WCT tests.
`make web_components_test`
> Fix test-file-results WCT tests

- webapp/components/test-runs-query.html
- webapp/components/test-runs.html
- webapp/components/wpt-results.html
- webapp/templates/interoperability.html
- webapp/templates/results.html
The properties needed a rename, missed in #555 
Fixes #575
> Fix product-spec query parameter propagation

- shared/datastore.go
- shared/storage.go
> Use memcache+datastore to fetch TestRun entities

- api/test_runs.go
- shared/datastore.go
Partial correction for #569 and #587
> Cap test-run limit

- Dockerfile
- Makefile
This reverts commit 8a929da3e49449dedfb0bb870ecfe5c84c3f5a05.
Reopens #459
> Revert "Install go1.11 gofmt as part of go_deps (#558)"

- webapp/.eslintrc.json
- webapp/components/display-logo.html
- webapp/components/info-banner.html
- webapp/components/interop.html
- webapp/components/product-info.html
- webapp/components/results-navigation.html
- webapp/components/test-runs-query-builder.html
- webapp/components/test-runs-query.html
- webapp/components/test-runs.html
- webapp/components/test-search.html
- webapp/components/test/path-part.html
- webapp/components/wpt-flags.html
- webapp/components/wpt-results.html
- webapp/components/wpt-runs.html
- webapp/package.json
Fixes #597 .
@lukebjerring , there are still a few remaining lint errors, mostly unused/undefined variables. Could you take over and finish those?
> Eslint fix

- api/query/autocomplete.go
- api/query/query.go
- api/query/query_mock.go
- revisions/api/handlers/list.go
- shared/params.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/469
> Drop ErrMissing

- webapp/components/abstract-test-file-results-table.html
- webapp/components/test-file-results-table-terse.html
- webapp/components/test-file-results-table-verbose.html
- webapp/components/test-results-history-grid.html
There is almost 100% shared code from one branch (expanded) to the other (terse) for the table branches. This PR collapses the code onto the base class. Also fixes the history grid in the process.
> Clean up table base classes

- webapp/components/self-navigator.html
- webapp/components/test/util/helpers.html
- webapp/components/test/wpt-results.html
- webapp/components/wpt-results.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/225
- Visit /results?q=this-wont-match-anything
- Observe 'No results'
- Visit /results?label=foo
- Observe 'Failed to fetch results'
> Distinguish 'no results' from failed fetch.

- webapp/components/self-navigator.html
- webapp/components/test-runs-query-builder.html
- webapp/components/test-runs-query.html
- webapp/components/wpt-results.html
One step further for https://github.com/web-platform-tests/wpt.fyi/issues/535
Updates the url when a query is submitted.
- Visit /flags, enable query builder
- Visit /results, build a query, submit
- See that the query params have updated.
> Update the URL when submitting a query

- shared/params_test.go
- webapp/test_results_handler.go
- webapp/test_results_handler_test.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/328
> Fall back to base64 instead of opening with it for before/after

- webapp/about_handler_test.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/17
> Add about_handler_test.go

- webapp/bower.json
- webapp/components/anomalies.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/12
> Use 'pluralize' to pluralize browser(s)

- webapp/about_handler.go
- webapp/templates/about.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/25
Visit /about
> Show version in /about

- webapp/components/wpt-results.html
- webdriver/product_test.go
Fixes single-product views, broken by https://github.com/web-platform-tests/wpt.fyi/pull/609
Load `?product=chrome`, see that results load as expected.
> Fix single-item diffs

- shared/spanner.go
- shared/spanner_test.go
Test and implement a unified enum for (sub)test status as they will be modeled in Cloud Spanner.
> Test and implement test status enum for use with Cloud Spanner

- results-processor/main.py
- results-processor/wptreport.py
This PR depends on #632 landing first.
> Results processor: Get test run ID from results receiver API payload

- shared/params.go
- shared/params_test.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/652
> Handle empty product[ spec

- api/webhook/taskcluster_test.go
Turns out no basic operation apart from channel communication is guaranteed to be atomic. And to make things worse, my check-and-increment logic is apparently racy.
This should fix the flakiness in `taskcluster_test.go`
> Use atomic operations in concurrency tests

- README.md
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/649
> Include results-collection in README

- webapp/routes.go
- webapp/test_runs_handler.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/671 (and other bugs with the same cause).
Drive by fix for https://github.com/web-platform-tests/wpt.fyi/issues/670 too.
Visit /test-runs?product=chrome-68
Observe a result
> Only set from if the query is the default

- webapp/components/interop.html
- webapp/components/results-navigation.html
- webapp/components/test-file-results.html
- webapp/components/test-runs-query-builder.html
- webapp/components/test-runs-query.html
- webapp/components/test-runs.html
- webapp/components/test/test-file-results.html
- webapp/components/test/test-runs-query-builder.html
- webapp/components/test/test-runs-query.html
- webapp/components/wpt-results.html
Adds a tickbox for showing a diff to the builder.
This required an unfortunate amount of refactoring :(
Select 2 products in the query builder, tick 'diff', submit.
> Add diff to query builder

- .travis.yml
- Makefile
- util/cleanup-versions.sh
Might not work just yet; prompting @Hexcles for collaboratively getting this set up.
> Cleanup staging on master

- webapp/components/interop.html
- webapp/components/wpt-colors.html
- webapp/components/wpt-results.html
> Consolidate color scheme

- webapp/components/wpt-flags.html
- webapp/components/wpt-results.html
As requested, a flag for top-level coloring on the wpt.fyi homepage.
Navigate to /flags, tick the feature, return to homepage, observe colors.
> Add colorHomepage feature flag

- webapp/components/abstract-test-file-results-table.html
- webapp/components/test-file-results.html
> Apply wpt-colors to individual files

- api/webhook/taskcluster.go
- api/webhook/taskcluster_test.go
This will allow us to distinguish `master` runs.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/699
> Add the github branch as a label

- api/webhook/taskcluster.go
Avoids having to deal with branch vs product name clashes, etc.
See https://github.com/web-platform-tests/wpt.fyi/issues/702
> Only label master, not all branches

- api/checks/webhook.go
In order to beta-launch, add a whitelisting behaviour for a couple of accounts that can manually (lukebjerring) and semi-regularly (autofoolip) create PRs.
> Whitelist lukebjerring and autofoolip for wpt checks

- results-processor/gsutil.py
- results-processor/main.py
- results-processor/processor.py
- results-processor/wptreport.py
Please see each individual commit (and review them one by one).
Fixes #247 .
> Refactor results-processor & make it (almost) idempotent

- webapp/admin_handler.go
- webapp/routes.go
- webapp/routes_test.go
> Add an admin-only endpoint to flush cache

- webapp/components/wpt-results.html
Makes the features a little less confusing.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/761
> Add tooltips for query-builder and diff-filter icons

- .travis.yml
`master` build has failed a couple of times. Emails to that effect would be good (so the PR author can follow up).
> Email on build failure

- api/routes.go
- shared/routing.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/779
@cc jugglinmike
#Review information
- Load one of the affected api endpoints
- e.g. /api/runs
- See headers, be unsurprised
> Wrap API handlers with application/json

- webapp/components/test-search.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/783
> Don't return the lowercase path

- webapp/components/info-banner.html
- webapp/components/test-runs-query.html
- webapp/components/test/wpt-results.html
- webapp/components/wpt-flags.html
- webapp/components/wpt-results.html
Inspired by #769, it's a nicer way of having an edit button available for the query builder.
> Show query info banner on /results

- webapp/components/wpt-results.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/797
> Bind the product specs for history grid

- webapp/components/info-banner.html
- webapp/components/wpt-results.html
- webapp/components/wpt-runs.html
Fixes the appearance when the message is too long.
Visit a nice long query, e.g.  `/?product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&product=chrome`
> Style the query summary (info-banner) with flex

- api/checks/update.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/812
> Add missing data for regression message

- api/checks/webhook.go
Fixes a bug with checking that the `err` is nil (wrong comparator).
> Fix wpt check_suite creation logic

- api/taskcluster/webhook.go
Will help with debugging for https://github.com/web-platform-tests/wpt.fyi/issues/835
> Log task group id

- ISSUE_TEMPLATE/checks.md
- api/checks/summaries/_file_an_issue.md
- api/checks/summaries/compile.go
- api/checks/summaries/compile_test.go
- api/checks/summaries/completed.md
- api/checks/summaries/pending.md
- api/checks/summaries/regressed.md
Adds a note about being in beta, and a URL for filing an issue on wpt.fyi with the Regressions project.
> Add feedback URL to check summaries

- api/checks/api.go
Fixes the current 500'ing cancel requests.
> Pass the required title field for Cancel action

- api/checks/webhook.go
Volunteer a few more guinea pigs for the checks beta.
> Add some active contributors to the checks beta

- api/checks/webhook.go
- api/checks/webhook_test.go
I'm not sure the wrapper worked anyway, given that we're seeing nil pointers...
> Remove unneeded CheckRunEvent wrapper

- webapp/components/wpt-flags.html
Supports enabling the feature via /admin/flags, to help eventually resolve https://github.com/web-platform-tests/wpt.fyi/issues/866
> Add /admin/flag for checksAllUsers

- api/checks/runs.go
- api/checks/update.go
Add more detail to checks update handling.
> More logging

- webapp/components/wpt-results.html
Part of #896 
Removes actual whitespace and replaces it with a CSS margin.
> Wrap closing tags to ensure no whitespace

- results-processor/requirements.txt
GitHub says there's a security vulnerability.
> Upgrade all Python dependencies

- webapp/components/product-info.html
- webapp/components/test-runs-query-builder.html
- webapp/components/test-runs-query.html
- webapp/components/test/test-runs-query.html
Clean up a few constants, with the benefit of less pollution of `window` and also a fresh copy of things that are collections.
> Namespace some more constants

- api/checks/api.go
- api/checks/api_mock.go
- api/checks/suites.go
- api/checks/summaries/compile.go
- api/checks/summaries/compile_test.go
- api/checks/summaries/completed.md
- api/checks/summaries/regressed.md
- api/checks/update.go
- api/checks/update_test.go
- api/checks/webhook.go
- shared/models.go
Related to https://github.com/web-platform-tests/wpt.fyi/issues/784
Records and web-platform-tests/wpt PRs for the CheckSuite, and links to the PR and the latest results for that PR from the check's summaries.
> Include PR numbers in check suites

- api/query/cache/index/index.go
This is a follow-up to #936, which, as it turns out, was incomplete. I noticed that per-shard locks were never being acquired for writing. This wraps adding run data to a shard and deleting run data from a shard in a critical section gated by the per-shard lock.
> Fix intrashard concurrency bug... again

- util/cleanup-versions.sh
When we're developing quickly, a week's worth of leftover PRs can build up.
> Change cleanup-versions to delete anything over a day old

- api/checks/summaries/_pr_and_master_specs.md
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/903
> Checks: Use hash as ID for both runs in summary

- webapp/components/self-navigator.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/941
> Include landing state in history stack

- webapp/components/self-navigator.html
> Fix navigation

- api/taskcluster/webhook.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/959
> Check context before extracting

- webapp/components/wpt-insights.html
Adds queries for flakes in the last 10 runs to the insights tab.
> Add flakes to insights tab

- shared/params.go
- shared/product_spec.go
- shared/test_run_filter.go
- shared/test_run_filter_test.go
- shared/util.go
Fixes pagination when a product has a label (or, a label is used in general).
> Add TestRunFilter custom marshalling

- results-processor/processor.py
Damn my butter fingers... Urgent fix. TBR
> fixup! [processor] Only upload results when they exist

- webapp/package-lock.json
- webapp/package.json
Remove unnecessary (indirect) dev dependencies from package.json and run
`npm update`.
> Clean up package.json and upgrade npm packages

- util/populate_dev_data.go
- webapp/package-lock.json
Tweaks the `make dev_data` script to grab `master` runs, and de-duplicate (ignore) the runs that it's already seen for other label queries.
> Add master runs in dev_data

- Makefile
- util/deploy.sh
Fixes:
- `-q` was consuming the next argument
- `-r` was missing
- `-g` was allowed, but not used
Should help with https://github.com/web-platform-tests/wpt.fyi/issues/992, but we'll let that be proven first.
> Fix the optargs flags in deploy.sh

- webapp/components/test-search.js
- webapp/components/test/test-search.html
Also update list of potential status literals in accordance with constants in golang code
> Client: Add browser:!STATUS structured search syntax

- webapp/package-lock.json
- webapp/package.json
- webdriver/install.sh
- webdriver/label_test.go
Also, change the installer to a more modern FF.
> Restore wct-legacy-browser dependency for devDependencies

- api/checks/webhook.go
- api/checks/webhook_test.go
Adds the ID for the production wpt.fyi check to the known app IDs.
> Create prod wpt.fyi checks app ID

- api/azure/webhook.go
- api/azure/webhook_test.go
- api/checks/api.go
- api/receiver/appengine_mock.go
- api/taskcluster/webhook.go
- api/taskcluster/webhook_test.go
- shared/appengine.go
- shared/sharedtest/appengine_mock.go
- webapp/about_handler.go
- webapp/package-lock.json
We were checking for `master` to return staging.wpt.fyi, but this is convoluting two different cases (are we staging, or prod? vs which version am I).
> Distinguish hostname and versioned hostname

- webapp/components/wpt-results.js
> Rejig the indentation + fix retry

- webapp/components/wpt-flags.js
- webapp/components/wpt-results.js
Has been enabled in prod for a while now.
> Bake in diffFilterUIToggle feature

- webapp/components/wpt-results.js
Lets the user know that they can retry.
> Show a toast when /api/search returns a 422

- .travis.yml
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1037
> Split the deploy tasks on travis

- Makefile
- webapp/package-lock.json
- webapp/package.json
> Upgrade nodejs in Docker and some npm packages

- .travis.yml
> Fix travis PR-deploy non-empty check

- util/cleanup-versions.sh
Include `searchcache` in the set of things we clean up.
> Cleanup searchcache automatically too

- api/checks/summaries/compile.go
- api/checks/summaries/compile_test.go
- api/checks/summaries/completed.md
- api/checks/summaries/regressed.md
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1045
Verified by running the tests with output printed, copying into an MD file, and rendering a preview in VS code.
> Escape pipe in URLs

- webapp/components/test/wpt-permalinks.html
- webapp/components/wpt-permalinks.js
Adds a test that was failing, then fixes the test.
Fixes #1077
> Include q param when copying link for run_ids

- util/travis-deploy-staging.sh
Ripped out of #1073 to fix #1082
> Deploy searchcache if anything under api/query changes

- api/query/atoms.go
- api/query/atoms_test.go
- util/travis-deploy-staging.sh
- webapp/components/test-search.js
- webapp/components/test/test-search.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1051
- Load https://any-browser-status-dot-wptdashboard-staging.appspot.com/?q=status:timeout
- See all timeouts
> Add support for status:[status] atoms

- api/checks/webhook.go
Ensures that we can find logs for a SHA[:7] by text search in appengine, even for failed requests.
> Always log the event sha for check_suite/run events

- webapp/components/product-info.js
Also alphabetize the list.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1097.
> Add Azure Pipelines as a Source in the query builder

- webapp/components/test-runs-query-builder.js
Follow-up to https://github.com/web-platform-tests/wpt.fyi/pull/1098 that actually uses the set dynamically.
Adds the logos too.
> Add icons to source dropdown, include Azure

- webapp/templates/admin_upload.html
Should let you pick a few files.
Fixes #1102
> Allow multiple files in /admin/results/upload

- api/query/README.md
- webapp/components/interop.js
- webapp/components/test-search.js
Adds some autocomplete behaviour for the search for basic atoms.
Adds a small link to some docs about the search syntax. Adds the docs, too.
Fixes #1126
> Improve discoverability of structured search

- webapp/components/wpt-results.js
> Preserve search in builder

- api/checks/webhook_test.go
- api/query/search_test.go
- revisions/announcer/announcer_test.go
- revisions/api/handlers/latest_test.go
- revisions/api/types_test.go
- revisions/git/tags_test.go
- revisions/test/git.go
- shared/request_caching_test.go
> Make tests quieter

- results-processor/wptreport.py
- results-processor/wptreport_test.py
See https://github.com/web-platform-tests/wpt/issues/15174#issuecomment-459961243
for the origins of this feature.
This also changes labels to be stored as a set while being processed and only normalised into a sorted list at the last moment.
> Normalize product names to handle underscore delimited variants

- webapp/components/abstract-test-file-results-table.js
- webapp/components/wpt-results.js
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1154
> Add CSS for sticky table headers

- webdriver/product_test.go
> Add "master" label to an integration test

- api/azure/notify.go
- api/azure/webhook.go
Steps for https://github.com/web-platform-tests/wpt.fyi/issues/1130
> Add /api/checks/azure/{id}?artifact=foo whitelisting

- webdriver/webapp_server.go
Broken in ec9455cc5cf4f701663e16f2ddefde919092df64 (wrong type).
> Fix static data setup in webdriver tests

- api/azure/api.go
- api/azure/mock_azure/api_mock.go
- api/azure/webhook.go
- api/azure/webhook_test.go
Artifact name alone isn't sufficient; they can be a manual full-run.
> Detect master branch for azure builds

- results-processor/wptreport.py
And only set it when it's not 0.
Fixing https://github.com/web-platform-tests/wpt.fyi/commit/70bae65e863afbc6261a2303c99f9f8f192b79d2#r32488233
> [processor] Make sure TestRun ID is an int

- api/query/atoms.go
- api/query/atoms_test.go
> Fix seq operator when runs exactly matches number of constraints

- api/screenshot/cache.go
- api/screenshot/model.go
- api/screenshot/model_medium_test.go
- api/screenshot/routes.go
- shared/routing.go
- webapp/index.yaml
- webapp/routes.go
This implements API endpoint [1](https://docs.google.com/document/d/1IhZa4mrjK1msUMhtamKwKJ_HhXD-nqh_4-BcPWM6soQ/edit?ts=5c4b4334#heading=h.ratj488usbcf) and [2](https://docs.google.com/document/d/1IhZa4mrjK1msUMhtamKwKJ_HhXD-nqh_4-BcPWM6soQ/edit?ts=5c4b4334#heading=h.xczylqsapugz) in the design.
> Screenshot storage backend

- api/azure/api.go
- api/azure/mock_azure/api_mock.go
- api/azure/notify.go
- api/azure/webhook.go
- api/azure/webhook_test.go
> Get the triggering commit from azure builds

- api/screenshot/model.go
- shared/datastore.go
- shared/datastore_ae.go
- shared/datastore_cloud.go
The first user is api/screenshot/model.go.
> Fix the API for Project to allow multiple fields

- api/azure/api.go
- api/azure/webhook.go
- api/azure/webhook_test.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1195
I wrote the regex and forgot to add it as a condition in #1180
> Handle refs/heads/epochs/* as master runs

- api/README.md
- api/receiver/api.go
- api/receiver/api_medium_test.go
- api/receiver/mock_receiver/api_mock.go
- api/receiver/receive_results.go
- api/receiver/receive_results_test.go
- results-processor/gsutil.py
- results-processor/processor.py
- shared/errors.go
- webapp/templates/admin_upload.html
> Plumb screenshots to the processor

- api/query/cache/poll/poll.go
- api/query/cache/service/main.go
Ingestion relies on the ID being set.
> Set ID before ingesting

- api/receiver/api.go
- api/receiver/api_medium_test.go
- api/screenshot/cache.go
- api/taskcluster/webhook.go
- shared/appengine.go
- shared/run_diff.go
See individual commit messages.
> Miscellaneous no-op code-health improvements

- webapp/components/interop.js
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/132
- Visit /interop
- Click the interoperability headers ( `0 / 4`, etc )
> Add ability to sort interop view

- api/azure/api.go
- api/azure/api_test.go
- api/azure/webhook.go
- api/azure/webhook_test.go
- api/receiver/api.go
- api/receiver/api_medium_test.go
- api/receiver/handlers.go
- api/receiver/routes.go
- api/routes.go
- api/taskcluster/webhook.go
- shared/appengine.go
- shared/datastore.go
- webapp/routes.go
It'd be easier to review each individual commit as the changes are explained in the commit messages.
No behaviours should be affected. No non-mechanical/non-trivial changes were mixed in. Tests should pass.
> More no-op code cleanup

- .pyup.yml
Automatically update `requirements.txt` every week!
> Add pyup configuration file

- ISSUE_TEMPLATE/screenshots.md
Rendered: https://github.com/web-platform-tests/wpt.fyi/blob/83119c37383a847f44038619a3c033e19a9946e8/ISSUE_TEMPLATE/screenshots.md
> Create issue template for screenshots

- webapp/components/reftest-analyzer.js
> Show an error message when screenshots can't load

- webapp/components/reftest-analyzer.js
Ensures that the spinner hangs around for longer.
> Consider more things loading when setting up the reftest analyzer

- webapp/components/wpt-header.js
- webapp/static/logo.svg
> Show favicon in header

- Dockerfile
- Makefile
- api/query/cache/index/go.mod
- api/query/cache/service/Dockerfile
- revisions/service/Dockerfile
> Modularize query/cache/index for the go-farm dep

- Makefile
> Install up-to-date deps for Firefox

- Makefile
- api/interop.go
- api/interop_medium_test.go
- api/query/cache/index/index.go
- api/query/cache/index/index_filter_test.go
- api/query/cache/index/index_medium_test.go
- api/query/cache/index/index_mock.go
- api/query/cache/index/index_test.go
- shared/metrics/models.go
- shared/metrics/models_test.go
- util/docker-dev/run.sh
- util/populate_dev_data.go
- webdriver/webapp_server.go
Remove dependency on results-analysis by moving the bunch of necessary type definitions into this repo.
Easier to review by commits. No behaviour changes and tests should pass.
> Remove dependency of results-analysis

- Makefile
- webdriver/firefox.go
- webdriver/install.sh
- webdriver/webdriver.go
> Use FF66 and log more errors

- api/query/cache/index/index.go
Fixes #1276 
Gently error when a report is empty, and serve a response that has no results (since the contents are never going to be non-empty)
> Allow empty reports in index

- api/query/cache/service/main.go
Instead of hard-coding it to ~200GB.
Needs to land before #1281 .
> [searchcache] Dynamically detect total memory

- webapp/components/reftest-analyzer.js
Makes a single call for the full image data array - the API is actually pretty slow to be called indivdually.
> Load the whole image data in one call

- .travis.yml
- webapp/package-lock.json
Hopefully this will alleviate the network timeout issue on Travis.
Docs: https://docs.travis-ci.com/user/caching/
Also did an `npm up` by the way.
> Cache npm modules and tox venv on Travis

- api/query/autocomplete.go
- api/query/autocomplete_medium_test.go
- api/query/autocomplete_test.go
- api/query/cache/backfill/backfill.go
- api/query/cache/backfill/backfill_medium_test.go
- api/query/cache/backfill/backfill_test.go
- api/query/cache/poll/poll.go
- api/query/cache/service/main.go
- api/query/query.go
- api/query/search.go
- api/query/search_medium_test.go
Not sure the exact problem, but mockgen is choking on these files.
Obviated the problem by just deleting the interfaces.
> Remove some redundant abstractions

- webapp/components/display-logo.js
Fixes #1305 
https://polymer-library.polymer-project.org/3.0/docs/devguide/templates#dom-if
> Remove instead of hiding empty logo

- .travis.yml
- webdriver/dev_appserver.js
- webdriver/path-test.js
Actually runs the (one) puppeteer tests on Travis.
> Fix tests + run on Travis

- api/query/search.go
- api/query/search_test.go
> Give 15s to return searchcache response

- Makefile
- webdriver/path_test.go
- webdriver/product_test.go
- webdriver/webapp_server.go
Extracted from #1295 with some tweaks for easier review & cleaner history.
> Fix dev_appserver re-use in golang

- util/populate_dev_data.go
- webdriver/path_test.go
- webdriver/search_test.go
Extracted from #1295: add interop for default view
> Fix large Go tests

- webapp/components/abstract-test-file-results-table.js
> Tweak white-space style for <code>

- .travis.yml
- webdriver/path_test.go
- webdriver/search_test.go
Work around #1327 & #1330 to get the tree green.
> Skip some WebDriver tests on staging and disable puppeteer_chrome_test

- webapp/static/common.css
This make it so that the last directory is not right at the bottom
of the page and gives a small amount of white space there in case you are scrolling.
Minor change to the UI
common.css
None
> Add padding to the bottom of the page

- util/populate_dev_data.go
- webapp/components/wpt-flags.js
- webapp/components/wpt-header.js
- webapp/components/wpt-insights.js
- webapp/insights_handler.go
Removes the "if" parts of the insights tab.
> Bake-in insights tab

- Makefile
- util/deploy-comment.sh
Tweaks the behaviour of the deployment messages to use the GitHub deployments API.
> Post a GitHub deployment instead

- api/query/README.md
> Document `status:missing`

- webapp/components/channel-picker.js
- webapp/components/wpt-insights.js
Suggested in #1499 
- Go to the insights tab
- See new "Release regressions" insight
> Add "Release regressions" to insights

- util/travis-deploy-staging.sh
Fixes what's considered deps for the webapp deployment.
> Fix staging deployment

- webapp/components/wpt-env-flags.js
- webapp/components/wpt-flags.js
- webapp/dynamic-components/templates/wpt-env-flags.js
- webapp/dynamic-components/wpt-env-flags.js
- webapp/dynamic_components_handler.go
- webapp/routes.go
- webapp/web/app.dev.yaml
- webapp/web/app.yaml
#1534 was a bad patch. This fixes that.
> Fix wpt-env-flags.js

- docs/admin.md
I did this because it's so much work to find https://wpt.fyi//admin/results/upload for me every few months that I need it.
> Document /admin

- api/query/autocomplete.go
- api/query/autocomplete_medium_test.go
- api/query/autocomplete_test.go
- webapp/components/path.js
- webapp/components/test-search.js
- webapp/views/wpt-app.js
- webapp/views/wpt-results.js
- webdriver/path_test.go
- webdriver/search_test.go
This reverts https://github.com/web-platform-tests/wpt.fyi/pull/1501.
> Revert "Explode folder contents in UI and collapse folders in autocomplete suggestions"

- Makefile
- api/taskcluster/webhook.go
- api/taskcluster/webhook_test.go
- go.mod
- util/tools.go
Please see each individual commit message, and skip the second one (it's a mechanic change that will be automated soon).
All tests should pass.
> Improve go.mod workflow and clean up Makefile

- .github/actions/make-in-docker/Dockerfile
- .github/workflows/ci.yml
- Makefile
- util/wct.sh
- webapp/wct.conf.json
- webdriver/chrome.go
See individual commit messages.
We should see three new GitHub Checks: web_components_test, go_chrome_test & go_firefox_test. All need to pass.
> Run web component tests and WebDriver tests on GitHub Actions

- .github/workflows/ci.yml
If a PR is from a fork, we don't receive the push event.
https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
> Also run tests on PRs originated from a fork

- webapp/README.md
- webapp/components/test-file-results-table.js
- webapp/components/test/test-file-results-table.html
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1553
> Make harness status "OK" grey rather than green

- revisions/service/main.go
This should fix the problem found in https://github.com/web-platform-tests/wpt.fyi/issues/1579#issuecomment-545581342
Test: Travis should successfully deploy a staging version of this branch.
> Fix the WPT repo URL in announcer

- webdriver/package-lock.json
- webdriver/package.json
It is never `require()`'d.
Introduced in https://github.com/web-platform-tests/wpt.fyi/pull/1304.
> Remove the @google-cloud/datastore dependency in webdriver/

- util/deploy.sh
Fix
https://github.com/web-platform-tests/wpt.fyi/pull/1638#issuecomment-554796859
> [deploy] Strip the trailing newline from branch names

- webapp/components/test-file-results.js
- webapp/components/test/test-file-results.html
- webapp/components/utils.js
Also reorganized the code a bit to get better test coverage.
Fixes #1646.
Compare
https://fix-duration-dot-wptdashboard-staging.appspot.com/results/webgl/bufferSubData.html?diff&filter=ADC&run_id=269870019&run_id=271890023
and
https://wptdashboard-staging.appspot.com/results/webgl/bufferSubData.html?diff&filter=ADC&run_id=269870019&run_id=271890023
This PR version should render the table correctly.
> Fix an exception when duration is missing

- webapp/templates/_ga.html
- webapp/templates/_head_common.html
- webapp/templates/about.html
- webapp/templates/analyzer.html
- webapp/templates/flags.html
- webapp/templates/index.html
- webapp/templates/insights.html
- webapp/templates/processor.html
- webapp/templates/test-runs.html
Also tweak templates to place GA snippets before any other scripts
instead of at the end as suggested by
https://developers.google.com/analytics/devguides/collection/analyticsjs
> Collect exceptions using Google Analytics

- .github/workflows/docker-update.yml
Inspired by
https://github.com/web-platform-tests/wpt/issues/20392 (although no one
has filed an issue against wpt.fyi yet)
Similar to
https://github.com/web-platform-tests/wpt/pull/20412
> Do not attempt to update Docker image on forks

- ISSUE_TEMPLATE.md
- README.md
> Remove mentions of results-collection

- renovate.json
Add the missing leading columns. Fix #1695.
> Fix renovate.json

- webapp/components/wpt-processor.js
- webapp/package-lock.json
- webapp/package.json
- webapp/templates/processor.html
Use `<vaadin-grid>` instead of `<table>` to allow us show details, select
columns, etc.
Try the staging instance.
https://better-status-dot-wptdashboard-staging.appspot.com/status
> Show pending/invalid runs better

- api/metadata_handler.go
- api/routes.go
- shared/routing.go
- webapp/web/routes_test.go
TODO: Need to change the origin to the URL of Mozilla dashboard origin
> Implement /api/metadata CORS policy

- shared/github_oauth.go
- webapp/login.go
- webapp/test_results_handler.go
Refactor login.go in Preparation for /api/metadata PATCH, taken from #1595.
> Refactor login.go in Preparation for /api/metadata PATCH

- .travis.yml
> Stop deploying revision announcer in staging

- go.mod
- go.sum
I forgot to suggest this in #1742 .
> Remove wpt-metadata from go.mod

- webapp/login.go
- webapp/login_test.go
See each individual commit message. Only the last commit fixes the actual bug, whereas the first two help investigating the cause.
With the first two commits, I was able to see the underlying error: "failed to decode state cookie: securecookie: expired timestamp", which led me to the root cause.
> Fix a securecookie test (TestHandleOauth)

- webapp/web/dispatch.yaml
Part of #1738.
This needs to be manually deployed per https://github.com/web-platform-tests/wpt.fyi/blob/master/docs/app-engine.md
> Remove dispatch rules for announcer

- webapp/components/display-logo.js
- webapp/components/path.js
- webapp/components/test-file-results-table.js
- webapp/components/test-run.js
- webapp/components/wpt-colors.js
- webapp/components/wpt-header.js
- webapp/components/wpt-prs.js
- webapp/templates/about.html
- webapp/templates/analyzer.html
- webapp/templates/flags.html
- webapp/templates/index.html
- webapp/templates/insights.html
- webapp/templates/processor.html
- webapp/templates/test-runs.html
- webapp/views/wpt-interop.js
- webapp/views/wpt-results.js
See individual commits for details.
Lighthouse a11y scores before the change:
* homepage: 75
* file result: 71
Lighthouse a11y scores after the change:
* homepage: 81
* file result: 76
> Accessibility fixes as suggested by Lighthouse

- .travis.yml
- Makefile
- webapp/.gitignore
- webapp/.lighthouserc.yml
- webapp/package-lock.json
- webapp/package.json
This PR sets up Lighthouse CI on Travis. Currently it will only run on master against the newly deployed version on staging, because it's easier to set up.
I cherry-picked a few assertions as errors -- these are the ones I just fixed in #1763 so we don't want regressions. We are still far away from being able to use the "recommended" preset.
For testing purposes, I triggered a run on this PR branch:
https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/281682765
See the commit status of e61631d2810798974e9e37cc9bfd9b55edf4ca11 .
> Set up Lighthouse CI

- docs/app-engine.md
Update documentation to point to the correct paths.
> Fix release docs to point to webapp/web in several spots.

- .github/workflows/ci.yml
- .github/workflows/docker-update.yml
- .travis.yml
`actions/checkout@v2` came out: https://github.com/actions/checkout#whats-new
It's basically a drop-in replacement with some performance improvements for us.
Also clean up some unused configurations in `.travis.yml`.
> Upgrade actions/checkout and clean up Travis

- webapp/components/wpt-amend-metadata.js
> Fix Triage Metadata UI Typo

- results-processor/Dockerfile
- results-processor/requirements.txt
- webapp/package-lock.json
The second commit contains the actual fix. Also see #1881 for more details.
> Fix deployment of results-receiver

- shared/github_oauth.go
> Remove TODO for the deprecating OAuth issue 

- webapp/README.md
Add instructions for running `web_components_test` platform-independently
> Update web_components_test README

- README.md
Adding pyup.io and GitHub Actions badges. See the Markdown preview.
> Add some CI badges

- results-processor/tox.ini
> Fix tox.ini to match README

- webapp/components/test-file-results.js
- webapp/components/wpt-metadata.js
- webapp/views/wpt-app.js
- webapp/views/wpt-results.js
Fix for https://github.com/web-platform-tests/wpt.fyi/issues/1899. 
Question to discuss:
How should I display wildcards - might clutter the UI.
Follow-up PR:
Display triaged metadata under subtest view, both inline and on the bottom of the page.
> [UI] Add metadata bug icon

- webapp/components/test/wpt-metadata.html
- webapp/components/wpt-metadata.js
- webapp/views/wpt-app.js
- webapp/views/wpt-results.js
Fix for https://github.com/web-platform-tests/wpt.fyi/issues/1994
> [Triage Metadata] Add testResults filter for displayed metadata

- shared/triage_metadata.go
Fix for https://github.com/web-platform-tests/wpt.fyi/issues/1872
> [Triage Metadata] Improve generated PR descriptions

- webapp/views/wpt-results.js
Fix for https://github.com/web-platform-tests/wpt.fyi/issues/2032
> Null check for metadataMap

- webapp/components/test-file-results-table.js
- webapp/components/test-file-results.js
- webapp/components/test/wpt-metadata.html
- webapp/components/wpt-metadata.js
- webapp/views/wpt-results.js
A follow-up for #1982 and fix #1899.
> [Triage Metadata] Inline bug icons for subtests

- webapp/components/path.js
- webapp/components/test/path.html
- webapp/components/test/wpt-results.html
- webapp/components/wpt-metadata.js
- webapp/views/wpt-results.js
Bug fix for https://github.com/web-platform-tests/wpt.fyi/issues/1899
> Add metadata bug icons for wildcards

- webapp/components/wpt-header.js
> Display solidarity banner in header to show support

- webapp/components/test-file-results-table.js
Fix for https://github.com/web-platform-tests/wpt.fyi/issues/2065
> Remove bug icons for passed subtests

- webapp/components/test/wpt-metadata.html
- webapp/components/wpt-metadata.js
Fix https://github.com/web-platform-tests/wpt.fyi/issues/2058
> [UI] Prepend https to WPT Metadata URLs

- webapp/components/path.js
- webapp/components/test/path.html
- webapp/components/test/wpt-metadata.html
- webapp/components/wpt-metadata.js
Fix https://github.com/web-platform-tests/wpt.fyi/issues/2063
> Filter wildcards using searchResults

- webapp/components/test-file-results-table.js
- webapp/components/wpt-amend-metadata.js
- webapp/views/wpt-results.js
Fix https://github.com/web-platform-tests/wpt.fyi/issues/2085.
> [UI] Show instructions after toggling the triage mode

- api/metadata_handler.go
- shared/appengine.go
- util/populate_dev_data.go
> Use a single GitHub bot client throughout the code

- shared/appengine.go
> [GO1.12] Add a nil check for the cloudtasks

- webapp/components/wpt-amend-metadata.js
- webapp/package-lock.json
- webapp/package.json
> [Triage Metadata] Make triage dialog scrollable

- .travis.yml
- util/commands.sh
- util/docker-dev/run.sh
instead of building from scratch.
This should speed up our Travis builds by 2x.
> Pull image from Docker Hub on Travis

- Makefile
- webapp/wct.conf.json
This still does **not** address #2142 but seems like a better workaround to me.
> Unpin Chrome but disable script streaming

- go.mod
- go.sum
- shared/appengine.go
See https://github.com/googleapis/google-cloud-go/issues/3205
Hopefully this fixes #2224.
> Set grpc keepalive option on cloudtasks client

- .pyup.yml
> Fix #2315 by shortening the pyup branch prefix

- webapp/components/results-navigation.js
- webapp/components/wpt-header.js
- webapp/views/wpt-app.js
- webdriver/label_test.go
- webdriver/product_test.go
- webdriver/webdriver.go
Fix https://github.com/web-platform-tests/wpt.fyi/issues/2287
> [UI] Move the interop tab to headers

- api/taskcluster/webhook.go
In https://github.com/web-platform-tests/wpt/issues/27243, we are seeing
500 errors from GitHub when we try to request 100 check-runs per page.
As a workaround whilst they investigate, GitHub have suggested
requesting fewer check-runs at a time.
> [taskcluster] Fetch only 30 check-runs per page from GitHub

- webdriver/package-lock.json
- webdriver/package.json
Reverts web-platform-tests/wpt.fyi#2375. The head started failing since the merge of this PR
> Revert "Update dependency puppeteer to v6"

- results-processor/requirements.txt
https://github.com/web-platform-tests/wpt.fyi/issues/2389.
See [syntax for pinning dependencies](https://pyup.io/docs/bot/filter/)
> [pyup] Ignore updates for idna

- webapp/components/wpt-bsf.js
Fix https://github.com/web-platform-tests/wpt.fyi/issues/2394
> [BSF] Switch the default to experimental

- api/checks/api.go
- api/checks/jwt.go
- api/checks/mock_checks/api_mock.go
- api/checks/runs.go
- api/checks/summaries/actions.go
- api/checks/summaries/actions_test.go
- api/checks/summaries/compile.go
- api/checks/summaries/completed.go
- api/checks/summaries/pending.go
- api/checks/summaries/regressed.go
- api/checks/webhook.go
- api/checks/webhook_test.go
- api/manifest/api.go
- api/metadata_cache.go
- api/prs.go
- api/receiver/mock_receiver/api_mock.go
- api/taskcluster/mock_taskcluster/webhook_mock.go
- api/taskcluster/webhook.go
- api/taskcluster/webhook_test.go
- go.mod
- go.sum
- shared/appengine.go
- shared/github_oauth.go
- shared/metadata_util.go
- shared/sharedtest/appengine_mock.go
- shared/sharedtest/github_oauth_mock.go
- shared/triage_metadata.go
- webapp/login_test.go
> Upgrade to go-github v33

- webapp/package-lock.json
- webapp/package.json
Reverts web-platform-tests/wpt.fyi#2380. See https://github.com/web-platform-tests/wpt.fyi/issues/2411
> Revert "Update dependency @vaadin/vaadin-grid to v6"

- .pyup.yml
Schedule monthly pyup update, instead of weekly
See `schedules` in https://pyup.io/docs/bot/config/
> [Pyup] Change pyup update frequency to monthly

- webapp/components/compat-2021.js
This is mostly a copy of the existing code from
https://ecosystem-infra.github.io/wpt-results-analysis/compat, but with
the necessary modifications for the polymer ecosystem (e.g. using data
binding, etc). A few TODOs are left for cases where using more polymer
features may be useful.
> [compat2021] Add summary scores component

- util/deploy.sh
See https://github.com/web-platform-tests/wpt.fyi/pull/2455#issuecomment-796926463
> Fix util/deploy.sh to never start or end with a hyphen

- webapp/components/compat-2021.js
This is mostly a copy of the existing code from
https://ecosystem-infra.github.io/wpt-results-analysis/compat, but with
the necessary modifications for the polymer ecosystem (e.g. using data
binding, etc). A few TODOs are left for cases where using more polymer
features may be useful.
> [compat2021] Add chart component

- webapp/components/compat-2021.js
This also brings in most of Una's changes from
https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/38 and
https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/42
Includes a few TODOs for places where we could be using polymer
elements/etc.
> [compat2021] Add stable checkbox and update URL as feature/stable change

- webapp/components/compat-2021.js
The UI change here is not massive, but requires substantially
refactoring how the page works. We now load the unified CSV rather than
individual CSV files for each feature. To aid with this and provide a
layer of caching, a specific data management class is introduced
(generalized from just chart data as it will eventually be used for the
summary scores at the top as well).
In addition to the above, this PR also improves the browser changelog
tooltip action. Loading changelogs automatically is now supported for
Firefox stable, and paper-dialogs pop-ups are added for Firefox Nightly
and Safari.
> [compat2021] Add a default summary-over-time view on the graph

- docs/app-engine.md
Update deployment instructions for Mac
> Update deployment instructions for mac

- api/query/cache/poll/poll.go
Remove pending PRs after 10 minutes in searchcache. If we remove pending PRs immediately after its closed, the wpt-metadata copy in memory might not be up-to-date. See [this comment](https://github.com/web-platform-tests/wpt.fyi/pull/2498#discussion_r601402388)
> [Triage Metadata] Remove pending PRs after 10 minutes in searchcache

- renovate.json
> Ignore vaadin/* update in Renovate

- webapp/views/wpt-app.js
Changes the "View source on GitHub" link to have two links instead: one to the master branch, as before, and one that links directly to the current commit. This is useful because the test results shown might not be from the master branch: they could be from a pull request, from a historical commit, or they could be from the last commit that has had runs from all selected browsers, which might not be the current HEAD of the master branch.
Closes #2593.
TODO
TODO
TODO
> Link to the GitHub source for the current commit, in addition to master

- .github/workflows/deploy.yml
Fix https://github.com/web-platform-tests/wpt.fyi/issues/2585. Do not run the job if a PR is from a fork
> [GitHub Actions] Check if PRs are from a fork

- api/README.md
> Update /api/results/upload documentation

- api/query/README.md
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1592.
> Document the path search atom

- webapp/components/reftest-analyzer.js
This is really halfway between a feature request and a PR.  I've written code for it -- but I haven't tested that code since setting up a development environment looked like a decent amount of work.  So there's some chance this code might work, but it likely requires some modifications to get it running correctly.
This adds the number of different pixels and the maximum color component difference to the reftest analyzer.  This information is useful for adding `<meta name=fuzzy>` annotations as described in https://web-platform-tests.org/writing-tests/reftests.html#fuzzy-matching
Unknown.  I haven't actually tested it.  Like I said, this is halfway between a feature request and a PR.  I'd like to be able to use this feature on the "COMPARE" links on pages like …
> Add maximum color difference and total different pixel count to reftest analyzer

- webapp/components/compat-2021.js
See https://github.com/web-platform-tests/wpt.fyi/issues/2663
> [compat2021] Add disclaimer for STP version

- api/query/cache/index/index_filter_test.go
> Check test containment in assert

- shared/metadata.go
- shared/triage_metadata.go
- shared/triage_metadata_test.go
- webapp/components/test/wpt-amend-metadata.html
- webapp/components/wpt-amend-metadata.js
Add Triage UI for #1491
https://github.com/web-platform-tests/wpt-metadata/pull/2251
> Add triage UI for label

- webapp/components/interop-2022.js
- webapp/interop_2022_handler.go
- webapp/routes.go
- webapp/templates/interop-2022.html
Set up a interop-2022 dashboard and a new /interop2022 endpoint. The dashboard is mostly taken and tweaked from compat-2021
> [Interop2022] Set up interop-2022 dashboard

- api/checks/api.go
- api/checks/jwt.go
- api/checks/mock_checks/api_mock.go
- api/checks/runs.go
- api/checks/summaries/actions.go
- api/checks/summaries/actions_test.go
- api/checks/summaries/compile.go
- api/checks/summaries/completed.go
- api/checks/summaries/pending.go
- api/checks/summaries/regressed.go
- api/checks/webhook.go
- api/checks/webhook_test.go
- api/manifest/api.go
- api/metadata_cache.go
- api/query/cache/poll/poll.go
- api/receiver/mock_receiver/api_mock.go
- api/taskcluster/mock_taskcluster/webhook_mock.go
- api/taskcluster/webhook.go
- api/taskcluster/webhook_test.go
- go.mod
- go.sum
- shared/appengine.go
- shared/github_oauth.go
- shared/metadata_util.go
- shared/run_diff.go
- shared/sharedtest/appengine_mock.go
- shared/sharedtest/github_oauth_mock.go
- shared/triage_metadata.go
- webapp/login_test.go
#2746
Updates Golang dependency `go-github` to the most recent major release (v42.0.0) following guidelines mentioned [here](https://github.com/web-platform-tests/wpt.fyi/pull/2212).
> Update Go dependency go-github to latest release

- webapp/components/wpt-header.js
UI adjustment to avoid cluttering. Remove the banner.
> [UI] UI adjustment to avoid cluttering

- shared/browsers.go
- shared/browsers_test.go
- shared/product_spec.go
- webapp/components/product-info.js
- webapp/components/test/test-runs-query-builder.html
Add chrome_android as a browser name in wpt.fyi. We plan to publish wpt test results for chrome android to wpt.fyi.
> Add "chrome_android" as browser name

- webapp/components/interop-2022.js
Use matrix.to to deep link to the Matrix room, making it easier to join the room with mobile clients or other clients.
> matrix.to Matrix room deep link

- .github/workflows/deploy.yml
- results-processor/app.staging.yaml
- util/deploy-staging.sh
- util/deploy.sh
Fix #2867. Only use 3 instances for processor staging deployment
> Create a staging yaml for processor

- webapp/components/interop-2022.js
[Staging link](https://interop-height-dot-wptdashboard-staging.uk.r.appspot.com/interop-2022)
> Interop 2022 - Fix page jumping from browser names

- webapp/package-lock.json
- webapp/package.json
Babel should been put in `devDependencies` instead of `dependencies`.
> Move Babel to dev dependency

- webapp/components/interop.js
- webapp/static/interop-data.json
This change adds the ability to change/view the investigation scores designated on Interop Collaboration pages. The graph will also be updated to display the change in score over time.
> Investigation scores

- webapp/static/interop-data.json
Fix link from `interop2022` to `interop20xx`.
> Update url to Matrix channel to #interop20xx

- webapp/static/interop-data.json
Updates the score for Editing investigation area of Interop-2022 based on https://github.com/web-platform-tests/interop-2022-editing/issues/10#issuecomment-1286114970
> Update the score for the Editing investigation

- webapp/components/interop.js
- webapp/package-lock.json
- webapp/package.json
> Include countup locally instead of fetching it from a 3P server

- webapp/static/interop-data.json
See https://github.com/web-platform-tests/interop-2022-pointer/issues/7
> Interop 2022: update pointer/mouse investigation score

- webapp/static/interop-data.json
See https://github.com/web-platform-tests/interop-2022-editing/issues/10
> Interop 2022: update editing investigation score

- webapp/static/interop-data.json
See https://github.com/web-platform-tests/interop-2022-viewport/issues/22#issuecomment-1357998964
> Interop 2022: update viewport investigation score

- webapp/static/interop-data.json
See https://github.com/web-platform-tests/interop-2022-pointer/issues/7#issuecomment-1351616023
> Interop 2022: update pointer investigation score

- Makefile
- webapp/components/test/test-run.html
- webdriver/package-lock.json
- webdriver/package.json
Reverts web-platform-tests/wpt.fyi#3147
> Revert "Bump puppeteer from 19.6.2 to 19.6.3 in /webdriver"

- webapp/components/interop.js
Fixes #3126
TODO
TODO
TODO
TODO
> Reduce size of interop dashboard circles

- webapp/components/interop.js
- Pick a nicer blue
- Remove the arrow, which does not make a lot of sense with the 2 column layout
TODO
TODO
TODO
TODO
> Update styling for experimental/stable toggle

- webapp/static/interop-data.json
- webapp/static/interop-data_v2.json
Fixes https://github.com/web-platform-tests/interop/issues/269
> rename Math Functions category

- .github/dependabot.yml
> Enable dependabot updates for docker images

- Makefile
Fix https://github.com/web-platform-tests/wpt.fyi/issues/3152. The underlying issue has been addressed in the latest Chrome
> Revert Chrome 109 pin

- api/README.md
Fixes #2940
This change updates the documentation that describes wpt.fyi summary files and their new v2 format.
> Update summary file format in documentation

- webapp/components/interop-dashboard.js
- webapp/components/interop-data.js
- webapp/static/interop-data.json
This adds links on the investigation areas in the interop dashboard.
Closes #3140
> Add links for investigation areas

- webapp/components/test/interop-data.html
Edit test message to be clearer about requirements of interop-data files matching.
> Verbose message for interop-data matching

- webapp/components/interop-data.js
- webapp/static/interop-data.json
See https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/3#issuecomment-1546395755
> Update score for Accessibility Testing (70%)

- webapp/components/interop-data.js
- webapp/static/interop-data.json
As discussed in the Interop 2023 Mobile Testing meeting on 2023-06-20
Notes: https://github.com/web-platform-tests/interop-2023-mobile-testing/issues/8
> Update Mobile Testing score to 40%

- webapp/components/interop-data.js
- webapp/static/interop-data.json
See https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/3#issuecomment-1610097208
> Update score for Accessibility Testing (78%)

- webapp/components/new-test-results-history-grid.js
This PR fixes an issue on #3368 where individual test run links were returning undefined. This bug happened when the mock data was changed from depicting one set of browser data to four. The chart reference variable was being overwritten for each individual chart, therefore only the links in the final chart were still functional. These changes ensure that the chart for each browser is stored in an array and can be indexed as needed.
> Fix links on chart navigating to bad URLs

- Makefile
Currently, all the go_chrome_test github actions are failing since this PR https://github.com/web-platform-tests/wpt.fyi/pull/3419. Turns out that we cannot use the old way for versions >114. https://stackoverflow.com/a/76729048
The likely culprit is that the distro where we download Chrome updated to 115. And then https://chromedriver.storage.googleapis.com stopped after 114. (You can visit that url to see the keys available) 
In the future, we can download the chrome version too.
> Use Chrome For Testing for downloading ChromeDriver

- Makefile
More details from https://github.com/web-platform-tests/wpt.fyi/pull/3433/files/e554cc6656dd6286ed48470c52801c078f1f96d6#r1282787489
> Chromedriver download from latest-patch-versions-per-build-with-downloads

- webapp/components/new-test-results-history-grid.js
Quick fix to update a changed key name
> change testName to test_name

- util/deploy-production.sh
- util/docker-dev/run.sh
This shell script now automates the entire process (steps 1-9) of the production deployment instructions. I used it successfully for https://github.com/web-platform-tests/wpt.fyi/issues/3543.
> Add missing functionality to deploy-production.sh

- webapp/components/interop-data.js
- webapp/static/interop-data.json
As discussed in the meetings:
- https://github.com/web-platform-tests/interop-2023-mobile-testing/issues/12
- https://github.com/web-platform-tests/interop-2023-mobile-testing/issues/14
> Update the mobile testing score to 70%

- webapp/components/interop-data.js
- webapp/static/interop-data.json
update ax investigation score to 98%
> update ax investigation score to 98%

- docs/app-engine.md
Update the production deployment doc to use the new script.
> Update the instructions for production deployment

- webapp/components/test-search.js
- webapp/components/test/test-search.html
Modify the OHM engine to interpret feature:value
> Add support for searching for web feature in the frontend [Part 4/4]

- webapp/components/wpt-bsf.js
- webapp/views/wpt-app.js
This is another step in the migration from Polymer to Lit.
> Use one-way binding for wpt-bsf

- webapp/components/interop-data.js
- webapp/static/interop-data.json
See https://github.com/web-platform-tests/interop-accessibility/issues/72
> interop-accessibility repo rename

- README.md
> Remove pyup leftovers from the README

- webapp/components/interop-data.js
- webapp/static/interop-data.json
The score is at 1.8% based on https://github.com/web-platform-tests/interop-accessibility/issues/110#issuecomment-2030971932
> Update the investigation score for Accessibility 2024

- webapp/views/wpt-results.js
Address https://github.com/web-platform-tests/wpt.fyi/pull/3753#discussion_r1548428134
> Use correct capitalization for VIEW_ENUM constant

- webapp/components/interop-data.js
- webapp/static/interop-data.json
update a11y investigation to 3.3%
https://github.com/web-platform-tests/interop-accessibility/issues/90
> update a11y investigation to 3.3%

- webapp/components/interop-data.js
- webapp/static/interop-data.json
Per the action item from the last mobile investigation [meeting](https://github.com/web-platform-tests/interop-mobile-testing/issues/26).
> Update mobile investigation score to 13%

- webapp/components/interop-data.js
- webapp/static/interop-data.json
update 2024 a11y investigation score: 3.3% to 12%
> update 2024 a11y investigation score

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
See https://github.com/web-platform-tests/wpt.fyi/actions/runs/9830208900 for the current warnings.
> Upgrade GitHub actions to v3 to resolve CodeQL warnings

- api/routes.go
> Fix #3542: /api/metadata should be application/json

- .vscode/launch.json
- .vscode/tasks.json
- Makefile
- util/docker-dev/run.sh
- util/docker-dev/web_server.sh
- util/server-watch.sh
- webdriver/README.md
This has already proved useful in #3910, so I am taking it out of that PR. VSCode tasks is still a WIP, and I expect to keep adding to it over time.
> Add VSCode debugging support for the web server

- webapp/components/interop-dashboard.js
- webapp/views/wpt-app.js
Reverts web-platform-tests/wpt.fyi#3950 now that the proposal period is over.
> Revert "Add Interop 2025 proposal submission banner"

- results-processor/gsutil.py
- results-processor/main.py
- results-processor/mypy.ini
- results-processor/processor.py
- results-processor/requirements.in
- results-processor/requirements.txt
- results-processor/wptreport.py
- results-processor/wptscreenshot.py
This should be relatively self-evident to review, and CI should verify whether or not this works.
> Get almost the entire results-processor typed

- webapp/components/interop-data.js
- webapp/static/interop-data.json
As agreed at the October 22nd meeting:
https://github.com/web-platform-tests/interop-mobile-testing/issues/31
> Update the mobile investigation score to 62.5%

- webapp/components/interop-dashboard.js
As discussed at the October 22 meeting:
https://github.com/web-platform-tests/interop-mobile-testing/issues/31
> Make the warning more pronounced

- api/azure/mock_azure/api_mock.go
- api/checks/mock_checks/api_mock.go
- api/manifest/mock_manifest/api_mock.go
- api/receiver/mock_receiver/api_mock.go
- api/taskcluster/mock_taskcluster/webhook_mock.go
- shared/sharedtest/appengine_mock.go
- shared/sharedtest/cache_mock.go
- shared/sharedtest/datastore_mock.go
- shared/sharedtest/fetch_bsf_mock.go
- shared/sharedtest/github_oauth_mock.go
- shared/sharedtest/metadata_util_mock.go
- shared/sharedtest/run_diff_mock.go
- shared/sharedtest/test_run_query_mock.go
- shared/sharedtest/triage_metadata_mock.go
This is automatically generated by running tests.
> Update mock files per mock 0.5.0

- webapp/components/interop-dashboard.js
This was inadvertently left out of #4085.
> Cleanup a now redundant class

- webapp/components/interop-dashboard.js
- webapp/components/interop-data-manager.js
- webapp/components/interop-data.js
- webapp/components/interop-summary.js
- webapp/interop_handler.go
- webapp/interop_handler_test.go
- webapp/static/interop-data.json
This PR adds all required changes for Interop 2025, but does not make the 2025 dashboard visible client-side.
> Add specifications for Interop 2025

- webapp/web/app.staging.yaml
- webapp/web/app.yaml
This should help the webapp avoid hitting the resource limits.
> Use the processor VM size for the webapp

- api/query/README.md
The links to features are incorrect, I think...
closes #4276
> Fix features links

- go.mod
- go.sum
- webapp/web/Dockerfile
Updating a golang dependency as part of team rotation duties.
This one seems pretty simple to me.  Hopefully, I am not missing something.
> Bump taskcluster to v83

- webapp/components/interop-data.js
- webapp/static/interop-data.json
Update hyperlinks for Interop 2025 investigation areas
> Update hyperlinks for Interop 2025 investigation areas

- webapp/components/interop-data.js
- webapp/static/interop-data.json
update scores for 2025 a11y investigation
- https://github.com/web-platform-tests/interop-accessibility/issues/148
change percentage from 0 to 30
> update scores for 2025 a11y investigation

- webapp/components/interop-data.js
- webapp/static/interop-data.json
See notes from https://github.com/web-platform-tests/interop-mobile-testing/issues/38
> Update the mobile investigation score from today's meeting
