shared/fetch_runs.go
shared/models.go
webapp/api_handlers.go
webapp/results_redirect_handler.go
webapp/results_redirect_handler_test.go
webapp/run_diff.go
webapp/test_handler.go
webapp/util.go

Works towards https://github.com/web-platform-tests/wpt.fyi/issues/44
Note that the existing `wptdashboard/metrics` refs will can't be migrated in a single step.

Add a copy of wptd/shared Go code

---

webapp/params.go
webapp/params_test.go

Handles requests which have a full-length SHA as the `?sha=[SHA]` value.

Shorten full-length SHA params

---

webapp/components/interop.html
webapp/components/wpt-results.html

Tests should use http scheme by default and https scheme if the path has ".https.".
(This is rebased on current master. Please "squash and merge".)

Use correct scheme in w3c-test.org link

---

shared/fetch_runs.go

The modified function is labeled as "shared," but it is only referenced from a script intended for local development. That leads me to believe the change won't effect any other aspects of the system. (If that's correct, it might be wise to re-locate it.)

Initialize dev database with "complete" runs

---

webapp/components/interop.html
webapp/components/wpt-results.html

This <th> is used at all levels. At the top level most directories
correspond to a spec, but not all, in particular HTML is split across
directories. And except for in css/, tests and directories that aren't
at the top level never correspond to specs. So just call it path.

Rename the "Spec" column to "Path"

---

webapp/components/wpt-results.html
webapp/main.go
webapp/results_redirect_handler.go
webapp/test/wpt-results.html
webapp/test_results_handler.go
webapp/wct.conf.json

Working towards https://github.com/web-platform-tests/wpt.fyi/issues/13 (current path scheme is future-hostile) and https://github.com/web-platform-tests/wpt.fyi/issues/39 (interop focus)
Redirects the `/*` path wildcards to `/results/*`, which will be _mooooostly_ backward-compatible for existing links, except for the clashes which are possible (and hence the change moving forward).

Add results/ prefix to landing page

---

.travis.yml

Forks can't access Travis CI secrets (by design), so the creds needed for a staging deploy are not available. Bypass the task.

Don't run deploy on forks

---

webapp/components/test-run.html

Add a map of the dataset names to Canonical Case names, and use them in the UI.
Resolves https://github.com/web-platform-tests/wpt.fyi/issues/6
Running at https://lukebjerring-camel-case-names-dot-wptdashboard.appspot.com

Add display names for platforms

---

webapp/api_handlers.go
webapp/params.go
webapp/params_test.go
webapp/test_results_handler.go
webapp/test_run_handler.go

Working towards https://github.com/web-platform-tests/wpt.fyi/issues/60
Spoofs the `?label=unstable` functionality support by querying for `[browser]-experimental` during query execution. This is to ensure that when we develop real labels, the UI doesn't need to change behaviour (just the datastore query).
Notes:
- `?labels=A,B,C` and `?label=A&label=B` forms of the param are both supported.
- Param is supported by both the `/api/runs` and the `/results` endpoints (and bubbles through).
CC @jugglinmike who may be happy to be able to view the experimental runs in the UI.

Fake-support the label=experimental param

---

webapp/main.go
webapp/test_results_handler.go

Preserve the query param when redirecting to `/results/`
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/89

Redirect with query params

---

webapp/components/wpt-results.html
webapp/test/wpt-results.html

Trim any trailing slash on the URL path when computing the test-path.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/93 (sometimes the user will manually tweak the URL and leave a trailing slash).

Strip trailing slashes

---

webapp/api_handlers.go
webapp/params.go
webapp/params_test.go

Changes the silent-fallback behaviour of `?browser=invalid-name` and `?sha=invalid-sha` to throw 400's instead of falling back to default values.
Resolves https://github.com/web-platform-tests/wpt.fyi/issues/71
Running at https://lukebjerring-error-bad-params-dot-wptdashboard.appspot.com
Examples:
- https://lukebjerring-error-bad-params-dot-wptdashboard.appspot.com/results?sha=not-a-sha
- https://lukebjerring-error-bad-params-dot-wptdashboard.appspot.com/api/runs?browser=not-a-browser

Throw errors for invalid params

---

Makefile
util/populate_dev_data.go
webapp/anomaly_handler.go

Fix lint suggestions and change the Makefile to get the WPTD_PATH variable in a relavite way, so that running `make lint` inside and outside docker both work.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/102

Use relative (not docker-specific) WPTD_PATH

---

webapp/components/runs.html
webapp/components/test-file-results.html

Also log the non-OK fetches in a consistent way.
Note that in runs.html the resolved value changes from undefined to
null, but that doesn't matter as both are falsy and filter soon after
into `nonEmpty`.

Use Fetch's response.ok instead of checking for status 200

---

Makefile
shared/fetch_runs.go
util/docker-dev/dev_data.sh
util/populate_dev_data.go

Adds a fetch for `?label=experimental` when populating dev data locally, so that experimental related UI features are easier to test (e.g. https://github.com/web-platform-tests/wpt.fyi/pull/99)
Also adds a flag for the `wpt.fyi` host to use, because the experimental label isn't supported in prod yet.

Add experimental runs when adding dev data

---

Dockerfile.dev
Makefile

Adds `eslint` as a make rule when running `lint`, which is what we execute during our git pre-push hook.
To support this, we install wct
Note that we don't yet run `wct` from inside docker - I'll cover that in a follow-up PR.

Include eslint in git pre-push hook

---

git/hooks/pre-push

When a read occurs before the read for the pre-push params, it causes an infinite loop. Similarly, when we use the `confirm` logging helper, which reads file desc 1, we get caught in the loop.

Fix read nesting bugs in pre-push

---

util/populate_dev_data.go
webapp/api_handlers.go
webapp/api_handlers_test.go
webapp/github_client.go
webapp/main.go
webapp/params.go
webapp/util_test.go

WIP - request for feedback
Adds an endpoint for getting a manifest for a given SHA.
To achieve this, it does:
- GitHub search for the PR associated with the SHA
- GitHub fetch for the release by tag-name `merge_pr_[PR number]`
- GitHub download of the release's asset with the name `MANIFEST-[sha].json.gz`
@gsnedders @jgraham if there is a better way to do this (without a local git clone) I'd be happy to know about it
@tabatkins - Haven't done `latest` behaviour yet, needs to be given a SHA param, but it's running here if you want to play around and point out any major flaws. AppEngine seems to behave nicely if you allow gzip encoding, but defaults to raw JSON @ ~20MB.
https://manifest-api-dot-wptdashboard.appspot.com/api/manifest?sha=ae34fb2b39f8b2cf9c3989a566ab938cde45dec0
There are some …

Add /api/manifest endpoint

---

Dockerfile.dev

The docker base image is v167 of gcloud SDK, which contains some bugs about resolving the Golang version to use for the separated `wpt.fyi/api` package.
This PR adds a `gcloud components update` which bumps us up to v200 (as at time of PR).
We are going to consolidate the docker files/images anyway (see #107), but this is a quick workaround until then.

Add a gcloud update to Dockerfile.dev

---

api/github_client.go
api/manifest.go
api/manifest_test.go
api/results_redirect_handler_test.go

Special-case `latest` as a SHA (which is the default when no SHA is provided) and fetch the latest release using [GitHub's latest release API](https://developer.github.com/v3/repos/releases/#get-the-latest-release)
@tabatkins - as I understand it, this is a step in the direction you wanted.
See https://manifest-latest-dot-wptdashboard.appspot.com/api/manifest

Add support for latest manifest

---

Makefile
git/hooks/pre-push

Adds `go build` and `go test` during prepush, since they are super fast to execute, and can catch silly errors when prepping for a PR.
Note that `make build` was previously only grabbing the `go_deps`, but not actually building.

Run build + test on prepush

---

api/README.md
shared/models.go
webapp/components/wpt-results.html

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/61 and https://github.com/web-platform-tests/wpt.fyi/issues/14 using the `/api/manifest` endpoint.
This example is from an `any.js` source-file:
https://manifest-test-source-dot-wptdashboard.appspot.com/results/console/console-counting-label-conversion.any.html
This example is from a `wdspec` python test:
https://manifest-test-source-dot-wptdashboard.appspot.com/webdriver/tests/element_retrieval/get_active_element.py

Use manifest test source for source and w3c-test links

---

api/manifest.go
api/manifest_test.go

Adds a header `x-wpt-sha` to the response which contains the full SHA of the manifest that is returned.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/133
cc: @tabatkins 
Header is present for requests to
https://sha-header-dot-wptdashboard.appspot.com/api/manifest?sha=latest

Return an HTTP header with the manifest's SHA

---

results-processor/.gitignore
results-processor/requirements-top_level.txt
results-processor/requirements.txt
results-processor/tox.ini
results-processor/wptreport.py
results-processor/wptreport_test.py

WPTReport abstracts wptreport.json and provides some helper functions to
summarize and split the full report (the split output is needed by the
current frontend).
The code is largely based on
https://github.com/web-platform-tests/results-collection/blob/master/src/scripts/upload-wpt-results.py
but without any sharding support.
wptreport.py is also an executable (requires Python 3), a handy script
to summarize and/or split a wptreport JSON locally. See its help message
for detailed usage.
The plan is to run unit tests via `tox`, which takes care of creating
virtualenv and installing dependencies. The setup currently works
locally as long as Python 3 and tox are available. It hasn't been
integrated into Travis or the project Makefile yet; the integration will
happen soon later.

[processor] Implement WPTReport and tests

---

util/travis-deploy-staging.sh

We should us the [double dot syntax](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#double_dot) to select revisions reachable from `HEAD` (i.e. the PR branch) but not from `TRAVIS_BRANCH` (i.e. the base branch), which is equivalent to the effect of rebase+merge.
@lukebjerring was the previous triple dot a typo or intended?

Fix the revision selection in deployment script

---

.travis.yml
util/travis-deploy-staging.sh

Re-using `travis-deploy-staging.sh` from PRs and master has stopped master deploying (since the script checks for `$TRAVIS_PULL_REQUEST_BRANCH`).
This changes that condition to be for the PR deploy in `.travis.yml`, and makes the script fall back to `$TRAVIS_BRANCH` when `$TRAVIS_PULL_REQUEST_BRANCH` isn't set.

Check whether in PR outside travis-staging-deploy

---

results-processor/Dockerfile
results-processor/gsutil.py
results-processor/main.py
results-processor/requirements-top_level.txt
results-processor/requirements.txt
results-processor/test.py
results-processor/wptreport.py
results-processor/wptreport_test.py

This PR is part of #146 and implements all basic functionalities except creating the task run, namely:
1. `wptreport` can now create a full results directory that contains both the summary and split test results (both gzipped), which is ready to be uploaded to the GCS bucket that backs the current frontend.
2. Create a new `gsutil` module that abstracts external calls out to `gsutil` which does all the parallel recursive upload. It's much simpler than implementing ourselves using the Python GCS library.
3. We now have a simple Flask-based web server which handles the tasks from TaskQueue. The handler currently uploads the processed results to a temporary dev bucket.
The next step is to upload to the prod bucket, and create test runs by calling a HTTP API on wpt.fyi.

[processor] Implement GCS upload & task handler

---

.travis.yml
Makefile

Integrate Python unit tests and lints (both managed by `tox`) into Makefile & Travis.
Also, since we are running everything inside Docker now, we don't need to specify `language`, which supposedly saves some time installing the language-specific dependencies on Travis outside Docker.

Add Python tests to Travis

---

api/receiver/appengine.go
api/receiver/appengine_mock.go
api/receiver/appengine_test.go
api/receiver/results_receiver.go
api/receiver/results_receiver_test.go
results-processor/Dockerfile
results-processor/main.py
results-processor/wptreport.py
results-processor/wptreport_test.py
webapp/templates/admin_upload.html

Old results don't have the required metadata. This change provides admins with a way to fill in (or override) the metadata.
https://extra-params-dot-wptdashboard.appspot.com/admin/results/upload

[processor] Take optional parameters from the admin upload form

---

Makefile
util/travis-deploy-staging.sh

Changes the deploy script to use the `wptdashboard-staging` project instead.
Applies to https://github.com/web-platform-tests/wpt.fyi/issues/161

Deploy to wptdashboard-staging instead

---

util/travis-deploy-staging.sh

Since we use `(foo|bar)`, we need `egrep` instead of `grep`.
Re: #161

Fix staging deployment script

---

results-processor/config.py
results-processor/main.py
results-processor/requirements-top_level.txt
results-processor/requirements.txt
results-processor/wptreport.py
results-processor/wptreport_test.py
webapp/queue.yaml

This PR implements the final piece of #146 , i.e. creating test runs.
We now have a fully isolated staging project (which gives us a separate Datastore) so we don't need to worry about polluting prod data. The processor now decides which GCS buckets to upload the processed results to depending on which project it's running in. And then the it will send a POST request to the `/api/run` endpoint of the *current* project, which is handled by the default Go app and will eventually create a test run in the Datastore of the project.
Also see #192 for the migration plan.
Since GCS buckets are all in a global namespace, we need to create separate buckets for the staging deployment.
* `wptd-staging` (in `wptdashboard-staging` project) is the staging counterpart of `wptd`, and is similarly publicly …

Processor creates test runs after uploading processed results

---

.travis.yml
Makefile
webdriver/search_test.go
webdriver/webapp_server.go

Changes the webdriver test to take a `--staging=true` flag (and optional `--remote_host` for the wpt.fyi address).
Also re-jigged .travis.yml to run the continuous master deployment in `script` so that it occurs before the `MAKE_TEST_TARGET`.
Resolves https://github.com/web-platform-tests/wpt.fyi/issues/199

Add staging.wpt.fyi continuous webdriver test

---

results-processor/main.py
results-processor/wptreport.py
results-processor/wptreport_test.py

To make file paths consistent with the existing files in the buckets,
different separators are used in different buckets:
* wptd (sharded results): dashes ('-')
* wptd-results (raw full results): underscores ('_')

[processor] tweak the separators in product IDs

---

api/routes.go
shared/routing.go
shared/util.go
webapp/routes.go
webapp/routes_test.go
webapp/test_results_handler.go

Migrate the webapp's routing to leverage gorilla/mux, a more powerful routing library. Unblocks #213 by supporting an `{id}` in the path.
@foolip - note that this highlighted a poor choice of nesting `/interop/anomalies` and thus migrates it to `/anomalies`
See auto-deployed environment.

Migrate webapp to use a gorilla/mux Router

---

api/results_redirect_handler.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/routing.go

Working towards #213 
Adds an `ID` field to the `TestRun` struct, which is manually populated after loading from datastore, and ignored by datastore (to avoid duplicating the field).
Load https://test-run-id-field-dot-wptdashboard-staging.appspot.com/api/runs and witness `id` in the JSON.

Add an ID field to the TestRun model.

---

Makefile

The script prints out a few thousand lines of logs. They were put inside
a pair of Travis folding marks, but are still too noisy (e.g. folding
doesn't take effect when logs are still being streamed, or when Makefile
is used locally).
In the Dockerfile of results receiver, the stdout of this script is
directed to /dev/null, which seems to be a good compromise so far as
some of the more useful information is in stderr, so let's do this in
the project Makefile, too.

Silence gloud install script

---

api/receiver/appengine.go
webapp/templates/admin_upload.html

There are two changes in the receiver service in this PR:
1. Add "Accept-Encoding: gzip" header when downloading remote reports with urlfetch.
2. Tweak the admin upload page to add optional override fields to URL payload and to stop using XHR.
Please visit `/admin/results/upload` of the staging deployment.

Instruct URLfetch to accept gzipped content and tweak admin upload page

---

webapp/app.yaml

Both the results receiver and the manifest API need a lot more memory than the default 128MB:
* The receiver needs to fetch wptreport from a remote URL to memory if the runner provides a URL instead of uploading a file.
* The manifest API needs to deserialize the WPT manifest JSON, which is also pretty big.
1GB is the largest memory AppEngine offers. We might not need that much, but we can scale down later based on monitoring.
This should fix or alleviate #220 .
Once the staging deployment is up, try the manifest API a few times and examine the logs. There should be no OOM.

Increase the memory limit of webapp

---

util/deploy.sh

Example failed deployment build: https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/387942807
> ERROR: (gcloud.app.deploy) argument --version/-v: Bad value [zcorpan/clarify-browsers-passing]: May only contain lowercase letters, digits, and hyphens. Must begin and end with a letter or digit. Must not exceed 63 characters.

Replace / and _ with - in automatic branch naming

---

.travis.yml
Makefile
util/deploy-comment.sh
util/travis-deploy-staging.sh

This PR tries to fix the staging deployment for `results-processor` (by quoting some variables that might contain spaces), as well as to fix #229 (by inverting the check for `TRAVIS_SECURE_ENV_VARS` so that it also works when the env var doesn't exist).
I also made some drive-by changes to improve logging, mostly to make `curl` and `apt-get` quieter.

Fix staging deployment and tweak some logging

---

webapp/anomaly_handler.go
webapp/interop_handler.go

Relies on https://github.com/web-platform-tests/results-analysis/pull/40
Change the datastore-reading struct to be the Legacy formats, which don't ignore the nested `TestRun` entities.

Load interop + anomalies data with backward compatible struct

---

api/results_redirect_handler.go
api/test_run.go
api/test_runs.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/run_diff.go
util/populate_dev_data.go

Resolves #212 
Adds the field `Labels []string` to the TestRun entity, for arbitrary label assignment that can be used to query with the `?label=foo` param in the `/api/runs` endpoint.
To verify, we'll have to combine #240 with the auto-deployed environment, uploading a run that includes a `labels` field (with an array of strings).
Then, `/api/runs?label=[uploader]` should display a result.

Add Labels to the TestRun entity

---

api/test_run_medium_test.go
results-processor/main.py
results-processor/wptreport.py

Currently, there is only one label: uploader.
The test run creation API doesn't handle labels at the moment, but extra params are safely ignored.
Part of #212 .
The JSON payload now has one extra field: `labels`, which is an array of strings.

[processor] Send labels when creating test runs

---

.travis.yml
util/deploy.sh

As it turns out, PR #238 wasn't the right fix. There are a lot more
places that we need to add quotes; and in the end, util/deploy.sh
can't support multiple targets without some big changes. Passing strings
with spaces around in Bash is too brittle, so the easy and reliable fix
is to split the master deployment into two commands.
One downside of splitting it into two commands is increased overhead.
Reducing the dependency in util/deploy.sh from webserver_deps to
webapp_deps hopefully alleviates the problem.
Lastly, simplify the conditions in .travis.yml a bit.
@lukebjerring can you confirm `util/deploy.sh` only needs webapp_deps instead of webserver_deps?

Fix Travis staging deployment of master

---

shared/datastore.go
shared/datastore_medium_test.go
shared/params.go
shared/params_test.go

This is part of #245. With this change, two kinds of runs will be considered as experimental and show up in `labels=experimental` queries: those with the `-experimental` suffix in the browser names, and those with the "experimental" label.
The implementation isn't the most efficient. Filtering happens in the app instead of in Datastore, because the union of the two conditions can't be expressed as Datastore queries. However, once we no longer create those spoofed `*-experimental` runs (i.e. once the results receiver is in prod), we can batch convert the existing `*-experimental` runs to have an `experimental` label and remove a whole bunch of special cases in the code.
Please verify in staging deployment that various label/browser params (especially `labels=experimental`) still filter …

Change the filtering of experimental runs

---

revisions/epoch/fractional.go
revisions/epoch/fractional_test.go
revisions/epoch/gregorian.go
revisions/epoch/gregorian_test.go

Announcer: Convert times to UTC before executing `IsEpochal(a, b)` logic.

Announcer: Perform time-based logic in terms of UTC timestamps

---

api/README.md
api/receiver/results_receiver.go
api/receiver/results_receiver_test.go
results-processor/main.py
results-processor/wptreport.py
results-processor/wptreport_test.py

An optional parameter is added to the payload of the results receiving API: `labels`. The main purpose is to fix #245 , but the runner can add arbitrary labels and filter test runs on wpt.fyi by these labels.
Re #245: In order to keep the number of required parameters minimal, we will automatically add a "stable" label if neither "stable" or "experimental" is present (i.e. we assume test runs are from stable browsers by default), which is compatible with the current behaviour.
1. An optional parameter `labels` is added to the API endpoint. It's a comma-separated string. The receiver (Go) does not touch this parameter, but simply passes it along to the processor.
2. The processor now has a new method `prepare_labels` which includes all the magics and heuristics.
3. Both new pieces come …

Accept labels from runners in results receiver

---

results-processor/main.py
results-processor/wptreport.py
results-processor/wptreport_test.py

Fixes #259
Replace non-URL-safe characters with underscores in URLs. e.g. `chrome-69.0 dev-linux.json` will now become `chrome-69.0_dev-linux.json`.
I didn't use percent encoding because I'd like to keep the URLs short and easily readable. These fields can be found inside the report anyway, so we are not losing any information.
The fields in Datastore are kept intact, i.e. they may still contain spaces. Only the URLs (of the full report, summary, and sharded results) are sanitized.

Sanitize special characters in report URLs

---

.gitignore
api/README.md
api/routes.go
api/shas.go
api/shas_medium_test.go
api/test_run.go
api/test_runs.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/params.go
shared/params_test.go
shared/run_diff.go
shared/util.go
webapp/index.yaml

Prior to this PR, fetching `?complete=true&max-count=5` didn't work.
This PR fixes that, and adds `/api/shas`, which simple enumerates a list of revision SHA[0:10] hashes (mostly for debugging purposes).
Multiple complete runs, with complete and max-count, e.g.
https://multiple-complete-dot-wptdashboard-staging.appspot.com/api/runs?complete=true&max-count=5
SHAs endpoint
https://multiple-complete-dot-wptdashboard-staging.appspot.com/api/shas
https://multiple-complete-dot-wptdashboard-staging.appspot.com/api/shas?complete=true

Add /api/shas endpoint and handle ?complete for multiple complete runs

---

results-processor/Dockerfile
results-processor/gsutil.py
results-processor/main.py

First of all, this fixes the out-of-disk-space issue by forcing AppEngine to restart the Docker instance when things go wrong as described in https://github.com/web-platform-tests/wpt.fyi/issues/271#issuecomment-397394519 ("problem 2").
Secondly (but perhaps more importantly), this PR fixes the root issue: `gsutil rsync` timeout. There are three fixes in total, in the decreasing order of effectiveness/importance:
1. Change the paths used in `gsutil rsync` to reduce the length of remote file lists (see https://github.com/web-platform-tests/wpt.fyi/issues/271#issuecomment-397502130 for further explanation).
2. Install `python-crcmod` so that `gsutil rsync` can use the compiled `crcmod` C extension https://cloud.google.com/storage/docs/gsutil/commands/rsync#slow-checksums
3. Explicitly use …

Attempt to fix timeout and low disk space issues

---

results-processor/gsutil.py
results-processor/main.py

This was accidentally dropped in #276 because of switching from rsync to cp.
This PR adds an option to gsutil.copy to set the gzip header, changes the
method name and adds documentation to gsutil.rsync make it clear that it will
set the encoding header.

Add Content-Encoding:gzip back to summary files

---

api/test_run.go
api/test_run_medium_test.go
shared/datastore.go

Currently `id` is `0` for runs fetched by their ID (e.g. https://staging.wpt.fyi/api/runs/5089364245741568)

Ensure ID set for /api/runs/[ID] response

---

api/test_run.go
api/test_run_medium_test.go

Fixes #278
(`WriteHeader` must be called before `Write` otherwise the clients will receive the default status code.)

Set response code correctly in POST /api/run

---

api/README.md

I just found that this param hadn't been documented. PTAL.

Add doc for `labels` to /api/runs

---

webapp/components/test-file-results.html

This makes it consistent with viewing a testharness.js test manually.

Rename Test file to Harness status

---

api/shas.go
api/shas_medium_test.go
api/test_runs.go

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/284
Was a dumb typo in a boolean check. PR Adds a few test cases that actually cover the HTTP endpoint (and passing the parsed value), which would have caught it.

Fix /api/shas ?complete bug + add a test

---

webapp/index.yaml

Fixes #298
* Added an index as suggested by AppEngine.
* Also moved the only non-TestRun index to the top.
https://staging.wpt.fyi/api/diff?before=chrome@61df0b90ef&after=chrome-69@61df0b90ef is working now. (Datastore indexes aren't versioned, and I've manually deployed the new index to staging.)

Add a Datastore index

---

webapp/templates/index.html

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/294
Spitting out an empty string for the attribute doesn't correctly parse as an empty array.

Add conditional for polymer attributes

---

shared/params.go
shared/util.go
webapp/index.yaml
webapp/interop_handler.go

Fixes #214 
Since we don't actually store a revision on a `PassRateMetadata` entity, this PR loads the default set of products for the given SHA and then finds a `PassRateMetadata` that has all of the run keys (IDs) in its `TestRunIDs` field.

Load interop by SHA

---

webdriver/anomalies_test.go

Not a great test, but asserts that at least one sibling `a` of an `h2` shows up in the shadowRoot of the wpt-anomalies element.

Add integration test for anomalies

---

util/travis-deploy-staging.sh

Fixes #302 .
The root cause is that somewhere there's a (or some) `\r` in `TEMP_FILE` (probably from `gcloud`) which confuses `grep` and `sed`. I believe the regression was introduced by me in #244 , when I got rid of `tr -d "\r"` and *thought* I'd verified that it wouldn't be a problem... Apparently I missed something.
This change also simplifies the pattern matching by using only `sed`, and tweaks `APP_DEPS` (`results-processor` is standalone and doesn't depend on `shared`).

Fix staging comment

---

results-processor/main.py
results-processor/wptreport.py
results-processor/wptreport_test.py

With https://github.com/web-platform-tests/data-migration/pull/6 , the
unshard script will also start to use '-' as the separator, which is
more consistent with the naming convention in the frontend serving
bucket (wptd) and design docs. And there is no need for the processor to
special case this any more.
This change has no user-facing effect. And existing historical reports
will be renamed in batch later.
Small non-user-visible change for code health and consistency.

Always use '-' as the separator in report URLs

---

util/deploy.sh

It's almost always a good idea to separate deployment and promotion.
Setting traffic split is very easy (with either the dashboard or CLI),
so let's always use --no-promote and then require a manual promotion.

Always use --no-promote (even for prod deploy)

---

api/test_run.go
api/test_run_medium_test.go
results-processor/wptreport.py
results-processor/wptreport_test.py
shared/models.go

First step of #310
Results processor will extract 'time_start' and 'time_end' from reports,
which are microseconds since epochs, convert them into ISO UTC time
strings, and send them to /api/run.
The API handler will unmarshal them into TimeStart and TimeEnd in
TestRun, which are two newly added fields in this PR. In the absence of
the two fields, the API handler will use the current timestamp as
TimeStart and TimeEnd.
CreatedAt continues to be the current timestamp when the API handler
receives the request, but the "retro" mode is now removed.

Add TimeStart and TimeEnd to TestRun

---

shared/params.go
shared/params_test.go
webapp/test_results_handler.go

This fixes the `?complete=true` behaviour when combined with a `?label=experimental` flag.

Write general handling for TestRun filter params

---

api/shas.go
api/test_run.go
api/test_run_medium_test.go
api/test_runs.go
api/test_runs_medium_test.go
shared/datastore.go
shared/params.go
shared/params_test.go
webapp/test_results_handler.go
webapp/test_results_handler_test.go

Follow-up for #318, re-using the generalized `TestRunFilter` code in the `/api/runs` endpoint.

Refactor api methods to re-use the TestRunFilter struct

---

Makefile

Using this make rule ensures that necessary file copying that is a part of announcer deployment gets cleaned up.

make rule for deploying to production

---

webapp/components/test-run.html

Fixes #331 
This PR takes both the browser names and the labels into account when deciding the logos, because browser names in the recent runs (since the introduction of results receiver) no longer have the "-experimental" suffix.
See the homepage of the staging deployment. Chrome Dev logo should be used.

Fix logos for experimental browsers

---

shared/datastore.go
shared/params.go
shared/params_test.go

This no longer works as intended - you end up comparing `chrome-experimental` with (the latest) `chrome`, which is also experimental.
Related to #311

Remove special case of browser name label

---

webapp/components/test-run.html

Fixes console output, e.g. https://staging.wpt.fyi/results/?product=chrome&product=safari&diff
> async.html:33 Uncaught TypeError: Cannot read property 'includes' of undefined
at HTMLElement.displayLogo (test-run.html:107)
at runMethodEffect (property-effects.html:818)
at Function._evaluateBinding (property-effects.html:2721)
at Object.runBindingEffect [as fn] (property-effects.html:581)
at runEffectsForProperty (property-effects.html:162)
at runEffects (property-effects.html:128)
at HTMLElement._propagatePropertyChanges (property-effects.html:1741)
at HTMLElement._propertiesChanged (property-effects.html:1705)
at HTMLElement._flushProperties (properties-changed.html:341)
at HTMLElement._flushProperties (property-effects.html:1559)

Handle test-run elements where run has no labels

---

docs/app-engine.md
webapp/dispatch.yaml

Fixes #326
I **think** URLs that don't match any of the rules will go to the default service, but I can't find the doc to prove it. https://cloud.google.com/appengine/docs/standard/python/reference/dispatch-yaml

Add dispatch.yaml for the announcer

---

shared/fetch_runs.go

Another case where non-consolidated query param handling causes problems. This causes `complete` to only be used when nothing that clashes with it is used (e.g. `?label=experimental`, used by results-analysis).
The current interop view @ https://staging.wpt.fyi/interop/?label=experimental was computed using this change locally.
The previous one, https://staging.wpt.fyi/interop/?label=experimental&sha=27406c9d23 was computed without the fix.

Use proper filters for the run fetch

---

shared/params.go
webapp/components/interop.html
webapp/components/results-navigation.html
webapp/components/self-navigator.html
webapp/components/wpt-results.html
webapp/interop_handler.go

Ensures params are kept when switching between `interop` and `results`.
e.g. https://interop-tab-dot-wptdashboard-staging.appspot.com/interop/?label=experimental

Persist params when switching tabs

---

api/README.md
api/interop.go
api/routes.go

Copy-paste of the HTML `/interop` handler, but dumps only the JSON into the response.

Add interop api endpoint

---

api/results_redirect_handler.go
api/shas.go
api/shas_medium_test.go
shared/datastore.go
shared/datastore_medium_test.go
webapp/index.yaml

Fixes #310 by changing the sorting property from `CreatedAt` (when the test run is uploaded to wpt.fyi) to `TimeStart` (which the test run starts). Ideally we should order by the commit date of the revision, but `TimeStart` is a good approximation which already exists in the wptreport (as `time_start`) and saves us the trouble of consulting git.
For historical runs, `CreatedAt` is used to backfill `TimeStart` using [this script](https://github.com/web-platform-tests/data-migration/blob/master/add_time_start/add_time_start.go). I've already run the migration script against the staging project.
Because of the backfilling, there should be no observable change at the moment, but moving forward we should expect Edge & Safari runs to space more evenly in "recent runs".
In addition to changing …

Sort test runs by start time

---

webapp/bower.json
webapp/components/test-run.html

This PR exposes more information about browsers using `<paper-tooltip>, namely:
* The full, untruncated version
* All labels
* Optional explanation text (currently it only has a reminder for whether experimental features are enabled, related to #333 .)
Hover your mouse on any browser (both the logo and the text) in the staging deployment. Specifically, try the following browsers: Chrome stable, Chrome experimental and Firefox (any channel).

Add tooltips to browsers

---

api/test_run.go
webapp/test_runs_handler.go

To use shared param parsing routines.
Also fix a bug in api/test_run.go where the handler didn't return early
after an error occurred.

Clean up webapp/test_runs_handler.go

---

api/manifest_medium_test.go
api/receiver/appengine_medium_test.go
api/shas_medium_test.go
api/test_run_medium_test.go
api/test_runs_medium_test.go
shared/datastore_medium_test.go
shared/sharedtest/util.go

There are multiple benefits for doing this:
1. The same code that creates a new aetest instance and then a new
context with a dummy request and two error checks is repeated many
times throughout the codebase only to get a strongly consistent
Datastore emulation. This is error-prone and sometimes confusing
(because of the fake URL).
2. With a central reusable routine, we can easily control all the aetest
instances. For example, in this PR SuppressDevAppServerLog is added
to suppress the lengthy and unhelpful messages from dev_appserver to
make the output of go_test much cleaner.
The utiltiy function is placed inside shared/sharedtest package,
following the Go convention as seen in http/httptest.

Extract creation of AppEngine testing server

---

Makefile
shared/fetch_runs.go
util/commands.sh
util/docker-dev/dev_data.sh
util/populate_dev_data.go

This allows for use cases like `./util/docker-dev/dev_data.sh -num_remote_runs=10`for 10 runs from each label configuration to be copied from remote (prod/staging) to local datastore.

Add param to populate_dev_data

---

shared/datastore.go
shared/datastore_medium_test.go
shared/params.go
shared/params_test.go
webapp/test_results_handler_test.go

This PR should make the "@SHA" part of ProductSpec fully working.
When the staging instance is up, try `/results/?product=edge@b7f4f1d1ea`.
Two pieces were missing previously:
1. `ProductSpec.String()` didn't add SHA back when serializing `ProductSpec`, which caused SHA to be missing in the UI (the arguments for components).
2. `LoadTestRuns()` didn't filter by `ProductSpec.Revision`.
They are added in this PR along with tests.
Besides, the receiver name of some functions in `shared/params.go` are renamed to fix a warning from my local golint ("receiver name should be consistent"). I'm not sure why Travis didn't complain. Perhaps my local golint is newer.

Implement the "@SHA" part of ProductSpec

---

ISSUE_TEMPLATE.md

The contents of the `ISSUE_TEMPLATE.md` file will be displayed in the
GitHub.com UI when contributors attempt to report an issue. The goal of
the text introduced here is to help reporters orient themselves and file
issues in the appropriate project.

Introduce GitHub issue template

---

webapp/components/test-file-results.html

Show "Harness status" as the row header only for testharness tests; for
other tests, use "File status" instead. Fixes #371.
Compare:
* /results/infrastructure/server/order-of-metas.any.html
* /results/infrastructure/reftest-wait.html

Use different names for harness and file statuses

---

Makefile

Otherwise, running locally non-deterministically works (or doesn't).

apt-get update before installing deps

---

shared/fetch_runs.go
util/populate_dev_data.go

Simplify the `FetchRun` signature to re-use the `TestRunFilter` struct.

Change FetchRun signature to take filter struct

---

util/cleanup-versions.sh
util/docker-dev/dev_data.sh

Fixes #123 .
Also make a drive-by change in dev_data.sh to remove an unused import.
I already used the script locally to delete a bunch of stale versions.

Add a helper script to clean up staging versions

---

webapp/components/test-file-results.html

Commit 26b7470752c6ecb4343dafdae5cf369ed6ce987c removed the redundant
`testFile` and `encodedTestFile` properties from test-file-results.html
and switched to `path` & `encodedPath` from the base class instead. Yet
there was one `encodedTestFile` that was left unrenamed, which broke
test-file-results.
Go to any individual test file and results should render properly. (staging.wpt.fyi is showing empty results right now.)

Fix test-file-results.html

---

Makefile

https://github.com/golang/appengine/issues/136 has been fixed so we
don't need the hack.
This change only stops to pin protobuf in new Go workspace. If your
protobuf pkg has already been pinned, you'd need to manually:
cd $GOPATH/src/github.com/golang/protobuf && git checkout master && git pull
Or if you use Docker, simply remove the Docker instance.

Stop pinning the version of Go protobuf

---

webapp/components/test-file-results.html

This commit:
1. Removes a redundant `console.error` for non-OK `fetch`; `fetch`
already prints errors to console.
2. Fixes a null access error in isTestHarness: `resultPerTestRun` may
contain null (e.g. when 404), so we can't unconditionally check the
`status` field.
Code health improvements. No visible changes (apart from fewer console errors).

Improve error handling in test-file-results

---

webapp/components/test-results-chart.html
webapp/components/wpt-results.html

While reviewing #397 , I noticed that the chart couldn't handle test names with query strings properly.
This change gets rid of the duplicate and out-of-date `resultsURL` method (that does not contain bug fixes for test names with query strings), and hence fixes the chart for test names with query strings.
Unfortunately, this change is almost a no-op right now as the chart doesn't show up in single-file views without #397. I'll rebase this PR once that lands, and then we can see the change easily on the staging instance.

Extend test-results-chart from test-file-results

---

webapp/components/self-navigator.html

Fixes #400.
Visit /results
Hold Command or Ctrl. Click a link. Should open in new tab (not navigate in the same tab).

Don't handle ctrl+click in self-navigator

---

webapp/components/self-navigator.html

#401 missed the Meta key, which is the default modifier to open new tabs on macOS (Command).
Fixes #400 again.

Don't intercept meta+click

---

util/populate_dev_data.go

Changes the default result of running `make dev_data` to be more useful. There's no downsides to a bunch of runs being available, and the static runs are only useful in very rare cases (no internet..? Changes relative to prod..?)

Change default dev data to 10 prod runs, no static runs

---

webapp/components/test-file-results.html
webapp/components/test-results-chart.html
webapp/components/wpt-results.html

When viewing directories with only one test, the history chart will not show up.
see any individual test file in the auto-deploy environment, eg. FileAPI/FileReader/Progress_event_bubbles_cancelable.html
cc/ @lukebjerring

update displayed tests if there is only 1

---

webapp/bower.json
webapp/components/abstract-test-file-results-table.html
webapp/components/test-file-results-table-terse.html
webapp/components/test-file-results-table-verbose.html
webapp/components/test-file-results.html
webapp/components/test-results-history-grid.html

- Default layout: terse (mostly as-is without this change)
- Alternate layout: verbose (previous layout before message-matching and ellipsis were added)
- Common table layout patterns in abstract mixin
- Mixin applied over different base classes for history grid view and two concrete table classes
- Toggle between layouts with styled paper-toggle-button

Add toggle for two file results layouts

---

Makefile
shared/sharedtest/util.go

Because of the mysterious flaky failures on Travis (#413), this change
temporarily allows go_medium_tests to fail and turns on verbose logging
from dev_appserver.
This is not a long-term solution. This change should be reverted ASAP.

TEMPORARILY allow go_medium_tests to fail

---

webapp/components/test-file-results.html

As in expand/collapse details.

Rename the "Verbose" toggle to "Expand"

---

webapp/components/test-file-results.html
webapp/components/wpt-results.html

We don't have meaningful diff data to show in the single-file result
view (the API simply returns a pair of delta pass/total for the test
file without any subtest details). Besides, the diff column is currently
broken in the web component anyway (empty on prod and uncaught
exceptions on staging). Hence, we hide the diff column in the
single-file view but keep the parameter in URL so that when users go
back to the directory view the diff column will appear again.
In terms of implementation, this PR stops spoofing a diff run into the
`testRuns` array, which is awkward and forces all subclasses of
TestRunsBase to deal with the special case. Instead, the PR creates a
dedicated `diffRun` property that's only used in wpt-results.html (i.e.
the directory view).
Lastly, the PR also fixes a UI …

Hide the diff column in single-file results

---

api/README.md
results-processor/main.py
results-processor/requirements.txt
results-processor/wptreport.py
results-processor/wptreport_test.py

The core change is to add chunk-merging support to `WPTReport` so that the processor can handle multi-URL payloads. This fixes #148.
Meanwhile, exception handling is vastly improved, not only to make the code more readable, but also to catch invalid reports in a central place and prevent TaskQueue from continuously retrying the task. This fixes #228.
The PR is a little big. I carefully rebased the history to make each commit (and its message) meaningful, so it might be easier to review each individual commit.
In addition to lots of unit tests, I've promoted the staging instance to the default processor on *staging.wpt.fyi* and manually tested it from end to end. Besides, it also means the branch is now processing incoming uploads from Buildbot, so at least we can be sure there's no …

[processor] Add support for chunked reports

---

.travis.yml

Everything now runs inside the Docker container so we no longer need sudo or Chrome outside of Docker. This hopefully speeds up the build a bit.

No longer require sudo and Chrome on Travis

---

webapp/components/test-runs.html

Context: https://github.com/web-platform-tests/wpt/pull/12381
.serviceworker. now implies .https.
Fixes #428 .

Use HTTPS for .serviceworker. tests too

---

api/routes.go
shared/routing.go
webapp/routes_test.go

This commit adds Access-Control-Allow-Origin: * to the headers of all
read-only APIs. Fixes #433.

Set all-permissive CORS for all read-only APIs

---

Makefile
shared/sharedtest/util.go

This reverts commit 0d6743e4b9dbb6a8e1cd26440e27784cd49c8de6.
So I don't know what happened. Gcloud SDK v212 seems to have fixed the mysterious flaky failure in our medium tests. The changelog doesn't say any bug fixes, either.
Fixes #413 ... Sigh
(Please do not merge the PR immediately. I'd like to watch the tree for a bit longer.)

Revert "TEMPORARILY allow go_medium_tests to fail (#425)"

---

api/query/search_test.go
api/query/types_test.go

Master build is currently failing because medium tests were recently re-enabled (close to when #414 landed). That caused me to miss the fact that there are types shared by `small` and `medium` test files in a file labeled only as `small`. This refactors common types into a file marked for both `small` and `medium` test contexts.

api/query: refactor types needed for small and medium tests

---

webapp/templates/caveat.html

Hyphenated "work-in-progress" acts like an adjective and not correct here:
https://www.grammarly.com/blog/hyphen-with-compound-modifiers/
And we now have both stable and experimental browsers.
Related: https://github.com/web-platform-tests/wpt.fyi/issues/24

Simplify the caveat

---

webdriver/webapp_server.go

Similar to #348, now that we use public APIs to fetch data from prod, we
no longer need to require production GCP credentials to run WebDriver
tests locally. This makes local debugging much easier.
Tested locally while working on fixing #435 .

Stop requiring creds for local WebDriver tests

---

webapp/components/interop.html
webapp/components/wpt-results.html

This is now the repo name, and with a checkout the paths on the
filesytem will looks something like "wpt/FileAPI/unicode.html".
This is bikeshedding.

Use lowercase "wpt" to represent the root path in UI

---

webapp/components/abstract-test-file-results-table.html
webapp/components/test-file-results-table-terse.html
webapp/components/test-file-results-table-verbose.html
webapp/components/test-file-results.html

In #405, we turned `test-file-results` into a thin layer was only responsible for fetching data and delegated the UI logic to new embedded components `test-file-results-table-{terse,verbose}` (which were subclasses of `AbstractTestFileResultsTable(TestRunsBase)`).
Therefore, information needs to be explicitly passed into the new components. Yet we forgot to pass `isTestHarness`, which caused the regression. This PR turns `isTestHarness` into `hasSubtests` (which is really a more accurate name as we don't know the type of a test for sure without consulting the manifest), and passes the property down to the embedded components.
This PR also removes the `is` getter from `abstract-test-file-results-table`; the abstract class is not a DOM template and doesn't need the `is` getter.
Fixes #419 . …

Fix "File/Harness status"

---

webdriver/label_test.go

Our staging environment now has all four experimental browsers, so the
assertion for testing "?label=experimental" needs to be adjusted
accordingly. The test has been broken for a while on master and wasn't
noticed because of #435.
Tested locally using `make go_chrome_test STAGING=true`.

Fix integration tests in staging environment

---

webdriver/label_test.go

Due to regression #451, this test is now failing on staging.wpt.fyi.
Temporarily disable the test on staging until we fix the regression.
(This test only fails on master because we only test against staging instance on master, after deploying.)

Skip the interop label test on staging

---

webapp/components/wpt-results.html

Fixes #477
- Misspelled CSS class names
- Incorrect parameters to helper functions
- Broken/needless fetch of diff
- Fix application logic for 'none' CSS class:
- Early return needed `!isDiff &&`
- Do not use 'delta none'; other num (passes or total) may be non-zero
- nit: `getDiffDeltaStr` always returns string

Fix diff view in wpt-results

---

webapp/components/test-runs.html

Reverts web-platform-tests/wpt.fyi#475, i.e. relands https://github.com/web-platform-tests/wpt.fyi/pull/450
Fixes #441 . Also see #468 .

Reland "Use ?complete=true as default query for /api/runs"

---

webapp/components/interop.html

Make interop search behave like results search. For now:
- Do not use `/api/search` or `/api/autocomplete`
- Filter top-level test/"file"-associated nodes client-side instead

Refactor interop search

---

Makefile
shared/fetch_runs.go
util/populate_dev_data.go

Fix for https://github.com/web-platform-tests/wpt.fyi/issues/478
After adding a bunch of fetched/remote test-runs, also fetches the latest interop data, and copies it locally by switching out the `TestRunIDs` to match the locally created test-run copies.
Run:
`make dev_data`

Fetch the latest interop run

---

api/shas.go
api/shas_medium_test.go
api/test_runs.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/params.go
shared/params_test.go

Migrates the `getCompleteSHAs` code to the shared codebase, and re-jigs it a bit, such that we grab the default products set, and find (any) product that matches the run. Since the default product specs are versionless, this is a no-op, intended to be followed up with actual changes in another PR.
In particular, review the code for `ProductSpec.Matches(TestRun)`

Refactor the way 'complete' is implemented

---

shared/datastore.go
shared/datastore_medium_test.go

Fixes the `complete` check for the case that we have 2 browsers twice.
This was a subtle bug from the use of a pointer for a local loop variable, instead of the pointer of the item in the array.

Fix `complete` implementation

---

api/interop.go
api/test_runs.go
shared/params.go
webdriver/search_test.go
webdriver/webapp_server.go

Handles ?complete=true (in the `/api/interop` endpoint), by consolidating the handling of params when querying for any non-default `interop` request.
- See [auto-deployed enviroment](https://complete-interop-dot-wptdashboard-staging.appspot.com/)
- Visit various param combos, e.g.
- https://complete-interop-dot-wptdashboard-staging.appspot.com/api/interop/?complete=true
- https://complete-interop-dot-wptdashboard-staging.appspot.com/api/interop/?complete=true&label=experimental
- https://complete-interop-dot-wptdashboard-staging.appspot.com/api/interop/?complete=false&label=stable

Handle ?complete=true in /api/interop

---

webapp/components/abstract-test-file-results-table.html
webapp/components/test-file-results-table-terse.html
webapp/components/test-file-results-table-verbose.html
webapp/components/test-file-results.html

Fixes #494.
Polymer was only updating table rows when their name column happened to change. This was a consequence of depending on `testRuns` and `subtestName`. In the case of the "Harness status" row, the `subtestName` didn't change and Polymer doesn't know that `testRuns[i].subtests.STATUS.*` changed, so so we observed #494.
This change replaces most of the `test-file-results*.html` properties with a `resultsTable` that contains an array of`{name, results: [{status, message}]` where the inner array is parallel to the `testRuns` array. This mirrors the structure of the views themselves and simplifies the binding logic, while also fixing #494.

File-level view data mirrors view structure

---

webapp/components/test-runs.html
webapp/templates/interoperability.html
webapp/templates/results.html
webapp/test_results_handler.go

Further work toward https://github.com/web-platform-tests/wpt.fyi/issues/468
Follow up from #488, making sure that `complete` appears in the outgoing query, even when other params are present, if it was originally present.
Existing issue demonstrated by https://staging.wpt.fyi/interop/?complete&label=stable
- Visit https://complete-client-dot-wptdashboard-staging.appspot.com/interop/?complete&label=stable
- Observe that the outgoing request contains `complete` (and the result is complete.)

Propagate the `complete` param to client

---

webapp/components/abstract-test-file-results-table.html

test-file-results-table: Return status string for messageless status or "status-as-message"

---

webapp/components/test-file-results.html
webapp/components/test-results-history-grid.html

Recent changes to `abstract-test-file-results-table.html` deleted a helper used in `test-results-history-grid.html`. This brings back a simplified version of the helper to ensure a single source of truth on how to name top-level test status.
Fixes #504.

Fix history grid broken by missing helper function

---

webapp/components/interop.html
webapp/components/path-part.html
webapp/components/wpt-results.html

So that "open in new tab" (or equivalant) can preserve URL parameters
correctly. Towards #193 resolution.
Go to `/results/?complete=true&label=stable` on the staging instance. Hovering on various links (especially the top path just below the tab switcher, and the list of subdirectories/files), and you should see the URL parameters included in the linked paths.

Include URL params in href (especially path-part)

---

api/shas.go
api/test_runs.go
shared/datastore.go
shared/datastore_medium_test.go

Builds on #489 to actually "fix" the behaviour of combining `labels` + `complete` when getting SHAs.
We're currently just ignoring labels when we get a list of complete SHAs, which may mean that if we limit the number to 1, we get a SHA that isn't complete for those labels.
e.g.
- https://staging.wpt.fyi/api/shas?label=stable&complete&max-count=1 (currently says `["6a9c5cbeae"]`)
- https://staging.wpt.fyi/test-runs?labels=stable (shows the most recent complete is `d2fa1bdc90`)
This fixes the issue, e.g. 
https://complete-from-products-dot-wptdashboard-staging.appspot.com/api/shas?label=stable&complete&max-count=1 now shows `d2fa1bdc90`
Also supports the corrected meaning of `complete` to be product combos, e.g.
https://complete-from-products-dot-wptdashboard-staging.appspot.com/api/shas?la …

Allow custom products when computing `complete`

---

api/query/autocomplete.go
api/query/autocomplete_test.go
api/query/search.go
api/query/search_test.go
api/query/util.go

This creates a helper for "canonicalizing" strings in the context of the `api/query` package. This is used sparingly in the search and autocomplete implementations to perform case-insensitive comparisons.
Fixes #508.

Make search and autocomplete case-insensitive

---

webapp/components/wpt-results.html

Fixes #510.
`wptResultsInstance.searchResults[i].legacy_status` contains the pass rate data for a single file. However, it was being copied by reference into `wptResultsInstance.searchResults.displayedNodes[j].results`, which models (sometimes) the pass rate data for an entire directory. Hence, when the `wptResultsInstance.searchResults.displayedNodes[j].results` was mutated to accumulate all data for its directory, "immutable-after-fetched" `searchResults` nodes were being mutated.
This fixes the problem by copying the values inside `legacy_status` properties into new `results` properties.

Copy immutable `legacy_status` data by value into mutable `results` entries

---

webapp/components/interop.html

Fixes #516 
- View any single file in the interop tab
- (e.g. https://interop-empty-dot-wptdashboard-staging.appspot.com/interop/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm?complete=true)
- Notice that the interop headers are gone.

Don't show interop table for single file

---

webapp/components/test-run.html
webapp/components/wpt-runs.html

Fixes #495 
Re-use the `test-run` component to enumerate all the runs that occurred for each browser at a given revision, rather than just dichotomizing "had runs" and "didn't have runs" per browser.
Review the code like any PR, but also give opinionated feedback on the aesthetics and behaviour!
See https://distinct-run-history-dot-wptdashboard-staging.appspot.com/test-runs

Distinguish runs in history tab

---

api/diff.go
api/interop.go
api/manifest.go
api/query/autocomplete.go
api/query/autocomplete_medium_test.go
api/query/query.go
api/query/query_test.go
api/query/search.go
api/query/search_medium_test.go
api/results_receive_handler.go
api/results_redirect_handler.go
api/shas.go
api/shas_medium_test.go
api/test_run.go
api/test_run_medium_test.go
api/test_runs.go
api/test_runs_medium_test.go
shared/datastore_medium_test.go
shared/sharedtest/util.go
shared/util.go
webapp/admin_handler.go
webapp/anomaly_handler.go

Logging in GAE Standard Environment goes nowhere when the golang `"log"` package is used. This change introduces an abstract `Logger` interface that is `".../appengine/log"`-compatible. Other implementations are available for GAE Flex (`stdLogger`) and test (`nilLogger`) environments.
Might be easier to review commit-by-commit.

Abstract GAE-compatible logging interface

---

api/query/query.go

1. `gzip` reader/writers do not close their delegates
1. Wrap in new `compositeReadWriteCloser`
1. `*memcacheWriteCloser` ptr type (not `memcacheWriteCloser` value type) should be `io.WriteCloser`

Fix two query API bugs

---

revisions/api/types.go
revisions/epoch/fractional.go
revisions/epoch/fractional_test.go
revisions/epoch/gregorian.go
revisions/epoch/types.go
revisions/service/main.go

Also add deprecation notice to four- and eight-hour epochs

Add six- and 12-hour epochs

---

util/cleanup-versions.sh

This now deletes staging instances that are more than 1 week old *and* whose corresponding PRs have been merged.

Change the grace period for deleting versions

---

results-processor/app.yaml
webapp/queue.yaml

Now that we have results coming from Taskcluster for every single PR merge, 1 instance of results processor isn't quite enough (it's still able to keep up, but the average latency for processing results is now much higher). So let's have 2 processors :)
Note that `queue.yaml` needs to be manually deployed for the change to take effect.

Run 2 instances of results processor

---

shared/util.go

This will enable use cases such as, in metrics computation:
- Create `logrus` logger -> stdout with log level `Warning`
- Create `logrus` logger -> file with log level `Debug`
- Compose two loggers in `context.Context` key for logging during metrics computation

Implement LoggerMux

---

api/README.md

The `time_start` and `time_end` properties are cited as being inserted
by the WPT CLI. That tool does indeed define those properties [1], but
the values are in units of milliseconds, not microseconds. This is
documented by the MozLog project [2] which the WPT CLI uses to provide
structured logging:
> time - The timestamp of the message in ms since the epoch (int).
[1] https://github.com/web-platform-tests/wpt/blob/632a3f59238036b6e24b28d47218ba9986ff4c62/tools/wptrunner/wptrunner/formatters.py#L13-L25
[2] https://firefox-source-docs.mozilla.org/mozbase/mozlog.html#data-format

Correct description of results format

---

api/webhook/routes.go
api/webhook/taskcluster.go
api/webhook/taskcluster_test.go
webapp/routes.go

The webhook listens to GitHub "status" events (i.e. all status updates
for all commits from all CI integration), but only reacts to the
"success" event from Taskcluster on master. When it receives such
events, it will query Taskcluster API for metadata, from which it
extracts task info, constructs a list of artifact URLs
(wptreport.json.gz), and sends the URLs to the results receiver.
In addition to unit tests, the code has already been deployed in my personal GCP and correctly sending results to the staging receiver: https://staging.wpt.fyi/test-runs?labels=taskcluster

Implement a GitHub webhook for Taskcluster

---

results-processor/main.py
results-processor/wptreport.py
results-processor/wptreport_test.py

This change makes the results processor to save the merged report
instead of just the last chunk of the report if the original report is
chunked when uploaded.
Besides, it also sets the channel label (stable/experimental) based on a
new property in the report, `run_info.browser_channel`, introduced in
https://github.com/web-platform-tests/wpt/pull/12679 .
The integration, including the modified upload process for full raw reports, is tested by deploying to staging.wpt.fyi. The heuristics for adding labels are tested in unit tests.

[processor] Save the merged report and infer labels from browser_channel

---

.travis.yml

We're fairly consistently seeing flakiness due to network errors (usually, `go get`) which are transient and fixed with a job retry.
Worst-case, this triples our computation of tasks that have genuine failures.
Best-case, this stops transient issues blocking clean/happy PRs.
See https://docs.travis-ci.com/user/common-build-problems/#travis_retry

Add a retry to the travis jobs

---

webdriver/install.sh
webdriver/label_test.go

Our integration tests should cover the full [launch checklist](https://github.com/web-platform-tests/wpt.fyi/issues/561#issuecomment-422177245).
This PR adds coverage for:
- `/results?label=stable&aligned`
- `/interop?label=stable&aligned`
Checks that the SHAs of the loaded test runs match.
make go_firefox_test USE_FRAME_BUFFER=false FIREFOX_PATH=~/browsers/firefox/firefox FLAGS='-test.run=^TestLabel'
and 
make go_firefox_test STAGING=true USE_FRAME_BUFFER=false FIREFOX_PATH=~/browsers/firefox/firefox FLAGS='-test.run=^TestLabel'

Check aligned in TestLabelParam webdriver test

---

shared/storage.go
shared/storage_mock.go

This is in anticipation of fetching `TestRun` entities using a memcache-fallback-to-datastore strategy.

Implement CachedStore strategy: memcache+datastore

---

webapp/components/interop.html
webapp/components/loading-state.html
webapp/components/test/interop.html
webapp/components/wpt-results.html

Re-uses the `loadingCount` and `isLoading` properties in a `loading-state` behaviour component.
- Visit the auto-deployed env's interop tab. See a spinner.
- add `?label=foo`. See a failure message.

Add a loading spinner + failure message for interop

---

Makefile
webdriver/chrome.go
webdriver/firefox.go
webdriver/webdriver.go

In an attempt to improve the stability of our integration tests (#566),
this change drops the intermediary Selenium Standalone server, and uses
chromedriver/geckodriver directly in our tests to remove one layer of
indirection.
One observed downside of having Selenium Standalone in between is that
sometimes chromedriver/geckodriver processes, along with the browser
processes, are left behind. (c.f.
https://github.com/SeleniumHQ/selenium/issues/6434 ). Besides, now that
chromedriver/geckodriver are more spec compatible, we don't need
Selenium to smooth over the discrepancies.
Lastly, this also fixes #461 by the way.
Travis should pass.

Drop Selenium and use WebDrivers directly

---

api/receiver/appengine.go
api/receiver/appengine_medium_test.go

Previously, errors from closing a GCS object were discarded, which might
be the cause of #559. This commit hopefully fixes #559.
See the new tests.

Handle errors from Close() in results receiver

---

.travis.yml
util/docker-dev/run.sh

Retry more network-related operations (namely building the Docker image,
installing system dependencies and pulling Go packages). Stop retrying
the test itself.
This is yet another effort towards #566 .
Travis should pass.
The core change is in `.travis.yml`. However, to make it possible to retry `util/docker-dev/run.sh` (which includes installing system dependencies), `util/docker-dev/run.sh` needs to be changed so that `-q` implies removing existing instances.
Also removed `-u $(id -u $USER):$(id -g $USER)` from `.travis.yml` as it's not necessary anymore (it's the default user).

Tweak Travis retry

---

webapp/components/test-run.html

Resurrects the incorrectly-removed `show-source` attribute on `test-run` component.
Fixes #574

Fix source icons in /test-runs

---

webdriver/product_test.go
webdriver/webdriver.go

Adds a simple integration test for `product=chrome[stable]` and `product=firefox[experimental]`, which would have caught #575 (confirmed locally with a pre-#577 run, which fails).
Asserts that 1 `test-run` shows up, and that its `browser_name` and `labels` attributes match.
make go_firefox_test USE_FRAME_BUFFER=false FIREFOX_PATH=~/browsers/firefox/firefox FLAGS='-test.run=^TestProductParam'

Add product spec integration test

---

Dockerfile
Makefile

Unfortunately, there is no go1.11 image under the `gcr.io/gcp-runtimes/go1-builder` docker dossier. All we really need for tooling consistency is go1.11 `gofmt`. This manually installs it from source to a location earlier in `PATH` than the default go toolchain.

Install go1.11 gofmt as part of go_deps

---

webapp/.eslintrc.json
webapp/bower.json
webapp/components/test/wpt-flags.html
webapp/components/wpt-flags.html
webapp/flags_handler.go
webapp/routes.go
webapp/routes_test.go
webapp/templates/flags.html

As discussed in https://github.com/web-platform-tests/wpt.fyi/issues/440, we should be putting new features behind flags by default.
This PR adds an `wpt-flags` component which uses `window.localStorage` to store feature state.
Also configurable with `wpt-flags-editor` component, which uses checkboxes.
Visit [/flags](https://flags-dot-wptdashboard-staging.appspot.com/flags) (might need a query parameter if your browser's stored a redirect from `/flags` -> `/results/flags`.

Add component for configuring features

---

webapp/components/interop.html
webapp/components/loading-state.html
webapp/components/test/loading-state.html
webapp/components/wpt-results.html
webapp/components/wpt-runs.html

Leverages (and extends) the `LoadingState` behaviour to display a spinner while the runs in `/test-runs` are being fetched.
Also adds a WCT test suite for the basic behaviour.
Visit `/test-runs`, observe a spinner.

Add spinner to /test-runs

---

webapp/components/interop.html
webapp/components/results-navigation.html
webapp/components/test-results-history-grid.html
webapp/components/test-runs-query.html
webapp/components/test-runs.html
webapp/components/test-search.html
webapp/components/wpt-results.html
webapp/interop_handler.go
webapp/templates/interoperability.html
webapp/templates/results.html
webapp/test_results_handler.go
webdriver/label_test.go
webdriver/search_test.go

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/563
The query param is not part of the test-runs query, but a (separate) filtering query. Additionally, you can't actually override the `computed` field (on a property) value, so we can't branch what constitutes the query.

Propagate the query param when navigating

---

Makefile
api/webhook/taskcluster_test.go

This mainly fixes two things:
* `go get -u golang.org/x/lint/golint` now works, so we can remove the manual checkout.
* Fix the lint for test tags which has been broken for a while (again, because of multi-line).
Along with some drive-by cleanups.
With the first commit, the missing tag in `api/webhook/taskcluster_test.go` was found (and fixed in the second commit).

Remove the workaround for golint and fix test tag lint

---

webapp/components/test-run.html
webapp/components/test/test-run.html
webapp/components/wpt-results.html

Improves https://github.com/web-platform-tests/wpt.fyi/issues/204 and adds run execution-time data for a misinterpretation of https://github.com/web-platform-tests/wpt.fyi/issues/282
Changes the hover content to show how long a run took (and what time it started). This disambiguates the date shown.

Switch date of runs to time_start and show execution time

---

webapp/components/test/test-run.html

Turns out I mocked the wrong `Date.prototype` method, but Travis didn't go red even though the test is failing :rage:

Fix test-run wct test

---

webapp/components/self-navigator.html
webdriver/path_test.go
webdriver/search_test.go

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/606
The underlying issue is that we set a default value, which caused the `!this.path` check to be false, and initial computation was stepped over (caused way back in #254)

Always compute path when value is default

---

webapp/components/abstract-test-file-results-table.html

More subtle fix for https://github.com/web-platform-tests/wpt.fyi/issues/449

Separate the first row in test-file-results display

---

util/docker-dev/web_server.sh
webdriver/webapp_server.go

Sad fix for https://github.com/web-platform-tests/wpt.fyi/issues/614
Relative paths seem to have stopped working in gcloud 219.0.1

Use an explicit app.yaml path in web_server.sh

---

api/diff.go
shared/params.go
webapp/templates/results.html
webapp/test_results_handler.go
webapp/test_results_handler_test.go

Ensures that params like `aligned` and `labels` are respected.
Also drops the base64 behaviour for the `before` and `after` params (a speculative, unused feature).
- Visit https://diff-dot-wptdashboard-staging.appspot.com/results?before=chrome[stable]&after=chrome[experimental]&aligned
- In another tab, visit https://diff-dot-wptdashboard-staging.appspot.com/results?product=chrome[stable]&product=chrome[experimental]&diff
- Find a row with a diff count that differs between the 2 diffs
- Ensure the same test's diff value is correctly calculated by https://diff-dot-wptdashboard-staging.appspot.com/api/diff (for the same params) for the row that would otherwise be wrong.
- https://diff-dot-wptdashboard-staging.appspot.com/api/diff?before=chrome[stable]&after=chrome[experimental]&aligned
- vs …

Handle the standard test run query params in /api/diff

---

webapp/components/results-navigation.html
webapp/components/self-navigator.html

Makes the query strings a bit more readable.
`searchParams.set(key, value)` _requires_ value, and stringifys it (so undefined doesn't work). An empty string results in 'foo='.
Hence, a hacky replace-all it is.

Drop redundant `=true` when building a query string

---

api/webhook/taskcluster.go
api/webhook/taskcluster_test.go

This PR changes the Taskcluster webhook to upload test results to the
results receiver API in parallel in order to reduce the webhook response
time (in half, as we currently run two browsers in each task group).
The goroutine and error handling are tested with simple HTTP testing
servers.
Part of #604 .

[webhook] Upload test results in parallel

---

webapp/about_handler.go

appengine.VersionID will panic when called locally (in dev_appserver),
which breaks the Go tests.
Fixes #614 . Turns out this is a genuine failure, not an infra issue. The failure wasn't caught because the version string and the test were introduced in two different PRs in parallel, and the timing was unfortunate.

Do not call VersionID when running locally

---

webdriver/search_test.go

I missed this one in #600. And I saw flaky failures from this very test
today, so let's double the timeout for this one, too.
Fixes #614 .

Double one more timeout in search_test.go

---

api/receiver/appengine.go
api/receiver/appengine_medium_test.go
api/receiver/appengine_mock.go
api/receiver/create_run.go
api/receiver/create_run_test.go

Also contains an ugly custom data type to work around no appengine-context-free mechanism for constructing datastore keys with predefined kind and integral ID.

 Receiver create_run: copy datastore key into TestRun.ID in response

---

webapp/bower.json
webapp/components/wpt-results.html

Puts the builder in a collapsible that closes when you submit.
- Visit /flags, enable `queryBuilder`
- Visit /esults, click the pencil, submit a query
- See it collapse

Put product builder in collapsible

---

webapp/components/test-file-results-table-terse.html

We're working on unprefixing these keywords in:
https://bugzilla.mozilla.org/show_bug.cgi?id=1322780
But it'd be nice if it worked before that's fixed :)

Use -moz-max-content so that cells show up on hover on Firefox.

---

webapp/components/test-runs-query.html
webapp/components/test-runs.html
webapp/components/test/test-runs-query-builder.html
webapp/components/test/test-runs-query.html
webapp/components/test/test-runs.html
webapp/components/wpt-results.html
webdriver/product_test.go

Further work on https://github.com/web-platform-tests/wpt.fyi/issues/535 
Changes the TestRunQuery to expand channel-labels onto the products during the building phase, and collapse them off of the products when producing the query-string.
- Visit /flags, enable queryBuilder
- Load /results, open the query builder with the pencil icon
- Observe that the Channel is `Stable` for all products
- Submit the query
- Observe that the query is ?aligned&label=stable, not ?product=chrome[stable]&product=...

Consolidate the channels + channel-labels

---

shared/params.go
shared/params_test.go

Simplifies the use-case of iteratively appending `run_id=`, and keeps consistency with other plural/repeated params.

Handle run_id and run_ids

---

revisions/api/handlers/latest.go
revisions/api/handlers/latest_test.go
revisions/api/push/latest.go
revisions/api/push/latest_test.go
revisions/api/types.go
revisions/service/main.go

Implement detection of changes in the announcer and log them. This is towards #551. Eventually, some model of "subscriptions" will be notified of subscribed changes.
```
go run go run github.com/web-platform-tests/wpt.fyi/revisions/service -port=[some-unused-port]
```
Wait for the announcer to update twice _after it has been initialized_. The first update should log a bunch of `Epoch [ID] changed from <nil> to [value]`. The second update (unless you are very unlucky) should contain no `Epoch [...] changed [...]` logs.
If you leave it running for a long time, subsequent epoch updates are also logged.
Some logic that used to live in the `handlers` package is moved to `push`; the "latest" handler delegates to the shared logic in `push`.

Announcer change detection

---

api/spanner/api.go
api/spanner/push_run.go
api/spanner/service/main.go

This implements the initial check for pushing a run to Cloud Spanner: Does the report contain more distinct test results than Cloud Spanner? If `reportResultCount > spannerRowCount` for the given run ID, then (in a follow-up PR) the service will write all results to Cloud Spanner.
If you wish to run locally, make use of the flags defined in `api/spanner/service/main.go` to setup credentials and a port number. If you wish to use a staging instance, then lookup the HTTP basic auth password for the `_spanner` user in Datastore.
`PUT /api/spanner_push_run?run_id=[integral-datastore-id-for-run]`
Logging should show the result of your request.

Spanner push run: Compare result counts

---

webapp/components/wpt-results.html

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/653
When handling a change in navigation state, we are force-submitting on _all_ changes, to ensure the builder always reflects the right state, and thus state is "submitted" as the current query. This is overkill for the case that only the path changes (no reload needed), so this PR checks that the _query_ is actually different, before triggering a data load (which was clobbering the path in the process).

Fix navigation

---

shared/params.go
webapp/components/interop.html
webapp/components/test-runs-query.html
webapp/components/test-runs.html
webapp/components/test/test-runs.html
webapp/components/wpt-results.html
webapp/interop_handler.go
webapp/templates/_test_run_query_params.html
webapp/templates/results.html
webapp/templates/test-runs.html
webapp/test_results_handler.go
webapp/test_results_handler_test.go
webapp/test_runs_handler.go

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/656
- Changes the UI query param plumbing to include `to` and `from` RFC3339 timestamp params
- Plumbs the default, 1-month `from` param value in `/test-runs` UI
- Deletes the now-unused `test-run-resources` full-url attribute that was causing a double-fetch
Open the devtools, visit /test-runs, observe a single fetch to the `/api/runs` endpoint (with a from param)

Handle to/from UI query params

---

shared/params.go
shared/params_test.go

Step towards resolving https://github.com/web-platform-tests/wpt.fyi/issues/639
Hackily avoids having to properly parse multiple `products` values by replacing the nested commas temporarily.

Handle multiple labels for products

---

shared/datastore.go

Re-fixes #https://github.com/web-platform-tests/wpt.fyi/issues/587 without fixed-limiting the key count.
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/671
Fixes #569 and might help #570 too...
/api/runs?product=chrome-68

Iterate keys instead of fetching

---

webapp/about_handler.go
webapp/about_handler_test.go

#618 wrote a broken test "fixed" by #626 (with a backwards boolean value and coincidentally fixing the test, but breaking the actual behaviour). This fixes both.

Fix /about version string

---

webapp/test_runs_handler.go

Use a default `max-count` of 100 for non-default `/runs` queries.
e.g. [/?product=chrome-68](https://test-runs-dot-wptdashboard-staging.appspot.com/runs?product=chrome-68)

Fall back to default max count

---

shared/params.go
shared/params_test.go

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/672 by re-using Full SHA parsing on the product SHA part.

Handle full SHAs in product specs

---

webapp/components/test-runs-query-builder.html

It's unused and unneeded; we're always editing. The read-only version is shown in the header of the results tables.

Delete edit mode from query builder

---

api/routes.go
api/versions.go
api/versions_medium_test.go

Lists the versions that we have for a given product. Fairly sure `Distinct` means the sheer quantity of runs (>1000) won't be a problem.
Relates to being consistent with the autocomplete work in #689 
Visit `/api/versions?product=chrome-70`

Add /api/versions endpoint

---

api/query/autocomplete.go
api/query/autocomplete_medium_test.go
api/query/query.go
api/query/search.go
api/query/search_medium_test.go
api/shas.go
shared/datastore.go
shared/request_caching.go
shared/request_caching_test.go
shared/sharedtest/io.go
shared/storage.go

Add request-level caching to `/api/shas`. To keep tests happy, also apply a bug fix detailed in b4392d9.
Observe logging about cache missing and serving from cache when visiting any `/api/shas?[params]` URL.

Request-level caching of /api/shas + bug fix

---

shared/models.go
shared/params.go
shared/params_test.go

Handles more `browser_version` values.
Adding autocomplete using #691 will result in us suggesting version strings that don't even pass, e.g. `75.0a1` or `69.0.1234.20 dev`.

Handle versions with channels better

---

shared/params.go
util/populate_dev_data.go
webapp/test_results_handler.go
webapp/test_results_handler_medium_test.go

Adds 2 flags `experimentalByDefault` and `experimentalAlignedExceptEdge` which allow for some different defaults as we've discussed offline.
A little hard to test without actually enabling them in staging, but locally they're added by default when you run dev_data (against this PR) and you can test that it works to revert back to normal when you delete them from the datastore using the admin console @ 0.0.0.0:8000

Add env-flags for different default queries

---

webapp/components/test-runs-query-builder.html

More https://github.com/web-platform-tests/wpt.fyi/issues/535 work.
Cosmetic change to include the product icons in the dropdowns.
Toggle the `Product` and `Channel` dropdowns, see icons.

Add icons to the query builder dropdowns

---

api/test_runs_medium_test.go
api/versions.go
shared/params.go
webapp/components/test-runs-query-builder.html

Builds on https://github.com/web-platform-tests/wpt.fyi/pull/689, using the same technique as SHA.
Open the query builder, see autocomplete in the `Version` field for each product.

Add autocomplete to the Version query builder field

---

webapp/components/test-runs-query-builder.html
webapp/components/test-runs-query.html
webapp/components/test/test-runs-query-builder.html
webapp/components/test/test-runs-query.html
webapp/components/wpt-flags.html

Starting towards #687 (for the all-the-same SHA case)
Adds a WPT flag for `queryBuilderSHA` which supports fetching the `/api/shas` endpoint for the current query, and populating the autocomplete of the SHA field using possibilities.
Visit `/flags`, enable both `queryBuilder` and `queryBuilderSHA`, type stuff.

Add field for a SHA, with autocomplete

---

util/populate_dev_data.go
webapp/components/test-search.html
webapp/components/wpt-flags.html

The flag is a no-op for now; I defined methods in the `test-runs` component for diverging query processing behaviour, but they contain a `TODO` and delegate to the unstructured query behaviour for now.

Add flag for structured queries

---

webapp/components/abstract-test-file-results-table.html
webapp/components/test-file-results-table-terse.html
webapp/components/test-file-results-table-verbose.html
webapp/components/test-file-results.html

Fixes #681 and turns 'Failure message: [msg]' into '(ERROR|FAIL) message: [msg]'
cc @foolip

Show error message in verbose table view

---

api/query/autocomplete.go
api/query/search.go
api/shas.go
api/versions.go

A previous strategy for cache handlers was to implement default helper functions and allow nil values on construction. Helper function parameters are now required and comments about using nil and defaults no longer apply.

Drop comments about 'nils' that no longer apply

---

webapp/components/wpt-flags.html

Introduced in https://github.com/web-platform-tests/wpt.fyi/pull/709
and causes a visual misalignment in /flags.
Check /flags in test deployment.

Fix markup structure in wpt-flags.html

---

api/webhook/taskcluster.go
api/webhook/taskcluster_test.go

go-github defines these protos already, so can reduce our code lines, and future code-churn.

Use go-github protos instead of local structs

---

api/diff.go
shared/params.go
shared/params_test.go
shared/run_diff.go
shared/run_diff_test.go
webapp/components/wpt-flags.html
webapp/components/wpt-results.html
webapp/routes_test.go
webapp/templates/results.html
webapp/test_results_handler.go

Splits `path` param from `filter` for parsing, and plumbs the value to the webcomponent.
We'll need this to make the UI ignore tests that didn't run on a PR.
Also changes the `/api/diff` endpoint to allow anything that produces exactly 2 results, e.g. `?product=chrome&max-count=2`
Load some filtered view, e.g. `/results?products=chrome[experimental],chrome[stable]&diff&filter=U` will only show unchanged things (kinda useless, but easy to tell it works).

Plumb diff filter params through the UI

---

webapp/components/test-search.html
webapp/components/test/test-search.html
webapp/components/wpt-results.html

This changes uses [ohm](https://github.com/harc/ohm) to define structured queries compatible with server-side parsing articulated in #713. It also integrates the queries by using `POST`-with-body rather than `GET`-with-query-params on `/api/search`.

Implement and integrate client-side structured query parser/generator

---

shared/datastore.go
shared/datastore_medium_test.go
util/populate_dev_data.go
webapp/components/interop.html
webapp/components/test-results-history-grid.html
webapp/components/test-runs-query-builder.html
webapp/components/test-runs-query.html
webapp/components/test/test-runs-query-builder.html
webapp/components/wpt-flags.html
webapp/test_results_handler.go

Adds a field to the query builder, and uses the `label=master` in the default query.
- Head to /flags, enable the feature
- Open the query builder, tick the box, reload, see `master` label is used

Add feature flag for fetching master branch runs only

---

api/webhook/taskcluster.go
api/webhook/taskcluster_test.go
shared/datastore.go
shared/datastore_medium_test.go

Changes the `/api/webhook/taskcluster` handler to not ignore non-master branches when `taskclusterAllBranches` flag is enabled.
Working towards #712 
This requires a tweak to the logic for task names (we want to ignore `stability`, but process `results`).
It also requires us to override what Taskcluster's wpt-report says was the SHA, since that SHA is a squash-commit over `master` and doesn't match the GitHub SHA for the PR results.
While difficult to confirm this works locally, it's a copy of the code from my [prototype](https://github.com/lukebjerring/web-platform-tests/pull/8/checks) for which you can see `change` branch results have made it into staging: https://staging.wpt.fyi/test-runs?label=change

Process non-master branch Taskcluster results (with flag)

---

api/diff.go
api/test_runs.go
api/test_runs_medium_test.go
shared/params.go
shared/params_test.go
webapp/components/wpt-results.html

Follow-up from https://github.com/web-platform-tests/wpt.fyi/pull/617 
On `/api/diff`, this prevents the (unlikely) race-condition, and any potential discrepancies, between executing the same query on 2 different api endpoints.

Support fetching runs by their IDs

---

api/webhook/taskcluster.go
api/webhook/taskcluster_test.go
api/webhook/verify.go
api/webhook/verify_test.go
shared/datastore.go
shared/datastore_medium_test.go

Extract the "load secret + verify payload" behaviour into a reusable method, in prep for adding another GitHub webhook for custom checks.
Working towards #712

Refactor verifySignature for re-use

---

api/receiver/create_run.go
api/receiver/create_run_test.go
api/results_receive_handler.go

Leverages the `checks` package's API to trigger a `completed` status for any `CheckSuite` for the SHA of the newly-uploaded run.
Currently, not doing this, we end up with infinitely `in_progress` check_runs.

Complete any check_suites when a run arrives

---

api/checks/webhook.go

Currently we're trying to parse all check_run names as a product and erroring out, when we should be ignoring other App IDs.

Ignore other check_suite apps

---

results-processor/processor.py

Oops, it's an unfortunate misread of the API documentation on my end. PTAL.

Fixup: Python Datastore APIs cannot be chained

---

results-processor/processor.py

@lukebjerring oops, sorry... Unlike AppEngine Standard, there is no standalone local emulator for Datastore for AppEngine Flex, so it's hard to test the API integration.

Fixup: cannot take len() of iterators directly

---

shared/storage.go

While it uses the error api, `memcache.ErrCacheMiss` isn't worth logging, so special-case it.

Don't log cache misses as errors

---

shared/params.go
shared/util.go
webapp/test_results_handler.go
webapp/test_results_handler_medium_test.go

With the master-only feature enabled, we end up unable to run a query like `sha=...` for non-master runs.

Only force the master label for default queries

---

api/checks/webhook.go

Detects when a check_suite event occurs for a SHA that's part of a PR that originates from another fork (but is created on the web-platform-tests/wpt repo), and requests a check-suite for the wpt repo too.
The one (other) case that we need to be wary of is the initial creation of the PR. A check_suite is created by GitHub when a new commit is pushed. This, of course, occurs on the forked repository, and there is also initially no associated PR at the time. Thus, when a PR is opened, we should ensure a check_suite on wpt for the PR's HeadSHA.  
Example check that used this code:
https://github.com/web-platform-tests/wpt/pull/14037/checks?sha=2ececcbafaa0b19cb5fac4e912c8709a7e295642

When a check suite is created, detect PRs across forks

---

webapp/components/test-runs-query.html
webapp/components/wpt-runs.html
webapp/test_runs_handler.go

Also shows a date boundary for each separate _day_ (instead of month) and shows a faint timestamp for non-boundary rows.
Computes the `Showing (N) runs` message from the params too.
Visit `/runs`, be amazed

Reduce the displayed runs to 7 days

---

api/checks/webhook.go

Changes the details link for the wpt.fyi checks to filter out deleted tests, since the affected tests is always a subset of the last master run.
For example, if you follow the link here:
https://github.com/web-platform-tests/wpt/pull/14070/checks?check_run_id=32143663
You see a bunch of delete changes. But if you set `&filter=ACU` in the url, it's more informative.

Use ACU filter for master-pr diffs

---

api/checks/webhook.go

The bot produces a bunch of exports from some CLs that worked in Chromium™ and are a good candidate for regression checks.

Whitelist chromium-wpt-export-bot for wpt.fyi checks

---

api/checks/webhook.go
api/diff.go
api/interop.go
api/manifest.go
api/query/query.go
api/query/query_mock.go
api/query/query_test.go
api/results_redirect_handler.go
api/shas.go
api/test_run.go
api/test_runs.go
api/test_runs_medium_test.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/params.go
shared/params_test.go
shared/run_diff.go
shared/test_run_filter.go
util/populate_dev_data.go
webapp/components/wpt-flags.html

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/588
Hides the token behind a feature, but supports base64 encoded tokens of a TestRunFilter.
Currently, the next page only works for `MaxCount` (using an offset). Will follow up with some time-range based behaviour. 
- Head to /admin/flags, turn on the feature
- Visit /api/runs?max-count=1, observe the `x-wpt-next-page` header in the response headers
- Fetch /api/runs?page=[the token], see that you get the next runs (1 per product).
As for code review, I recommend you eyeball and overlook the first commit (a refactor that'll be needed later when combining pagination of time + max-count), and scrutinize the 2nd commit.

Add `max-count` pagination ability to /api/runs

---

util/commands.sh

Fixes #250 .
@AutomatedTester no I wasn't able to find a more elegant solution. In fact, this is a common issue with lots of blogs introducing essentially the same workaround we're already using (e.g. https://denibertovic.com/posts/handling-permissions-with-docker-volumes/). This PR is a workaround for an edge case of the workaround...

Do not fail when GID already exists in Docker

---

api/checks/summaries/compile.go
api/checks/summaries/compile_test.go

We're currently escaping when we shouldn't be.
(e.g. https://github.com/web-platform-tests/wpt/pull/14119/checks?check_run_id=33055714)

Avoid HTML escaping in md template

---

api/checks/summaries/compile.go
api/checks/summaries/compile_test.go

Reverts web-platform-tests/wpt.fyi#774

Avoid HTML escaping in md template properly

---

api/checks/webhook.go
api/interop.go
api/query/query_test.go
api/test_runs.go
shared/datastore.go
shared/models.go
shared/run_diff.go
shared/test_run_filter.go
webdriver/product_test.go

Tests are flaky from the non-deterministic ranging over a map, mistakenly done in #772 
Luckily, most callers were using `AllRuns` already, so this isn't too bad of a follow-up fix.

Fix product order preservation

---

api/README.md
api/test_runs.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/params.go
webapp/components/wpt-flags.html

First steps towards https://github.com/web-platform-tests/wpt.fyi/issues/784
Adds `runsByPRNumber` feature, which will run a GitHub API fetch for commits for the PR number and list all runs pertaining to all SHAs in the PR.
NOTE - won't work on the UI as a result of this PR, needs a follow-up.
- Head to /admin/flags, ensure feature is enabled
- Load /api/runs?pr=[PR number]
- Needs to be a whitelisted user, e.g. `autofoolip`
- e.g. [/api/runs?pr=14143](https://prs-dot-wptdashboard-staging.appspot.com/api/runs?pr=14143)

Add feature for listing runs for a PR

---

api/test_runs.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/params.go
webapp/components/test-runs-query.html
webapp/components/wpt-flags.html
webapp/interop_handler.go
webapp/templates/results.html
webapp/test_results_handler.go
webapp/test_runs_handler.go

Extension of #785 that includes the UI plumbing needed.
Only need to review the last 2 commits.
Find a PR that has loaded results into wpt.fyi, and load ?pr=[PR number]
e.g. [/results/?pr=14143](https://prs-ui-dot-wptdashboard-staging.appspot.com/results/?pr=14143)

Add plumbing for pr param in UI

---

api/test_runs.go

Lists a larger number of commits by default.

Use the max page size by default for listing PR commits

---

Makefile

The cleanup script is silently failing, e.g. https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/458648755
> ERROR: (gcloud.app.versions.list) You do not currently have an active account selected.
> Please run:
>   $ gcloud auth login
We've got the secret ready, but were missing the login command.

Login before running cleanup

---

results-processor/processor.py

> From Werkzeug 0.3 onwards, the KeyError raised by this class is also a subclass of the BadRequest HTTP exception and will render a page for a 400 BAD REQUEST if caught in a catch-all for HTTP exceptions.
For the callers to the processor that aren't providing the value, this is causing 400s.

TBR: Use get to avoid ValueError

---

api/query/query.go
api/query/query_test.go
webapp/components/loading-state.html
webapp/components/wpt-results.html

Makes sure that we handle results fetching (from /api/search) failures in the UI.
Also tweaks the error message to include which run is being a problem.

Handle fetch errors a little better

---

api/checks/suites.go
api/checks/update.go
api/diff.go
api/interop.go
api/manifest.go
api/query/query.go
api/results_redirect_handler.go
api/shas.go
api/test_run.go
api/test_runs.go
api/versions.go
revisions/api/handlers/list.go
shared/params.go
shared/params_test.go
shared/test_run_filter.go
webapp/anomaly_handler.go
webapp/interop_handler.go
webapp/queue.yaml
webapp/test_results_handler.go
webapp/test_runs_handler.go

The more simple API for a TaskQueue POST dumps given params in the payload; we were trying to parse them from the query params.
This PR refactors the `Parse*Param` helpers to take the `url.Values` objects directly, instead of the `*http.Request`. It also uses `ParseForm()` and passes that for /api/checks/{commit}, so that non-empty POST body as url params in the same manner.

TBR: Parse /api/checks/{commit} body as Form

---

webapp/components/product-info.html
webapp/components/test-runs-query-builder.html
webapp/components/test/test-runs-query-builder.html

Handles an edge-case where the user enters a semantic label (e.g. `stable`) manually as a label, rather than clicking the dropdowns 4 times.
As per https://github.com/web-platform-tests/wpt.fyi/pull/769#issuecomment-440844710 
- Visit /runs
- Edit the query, type a semantic label (e.g. a channel, like `stable`)
- Submit, see the expected results
- Edit the query, type a different semantic label (e.g. `experimental`)

QueryBuilder: Handle user-entry semantic labels on submit

---

api/README.md

wpt.fyi is expected to occasionally go offline. Users should be informed
of this expectation so they can respond appropriately.

Document expected downtime

---

api/checks/suites.go
api/checks/update.go
api/checks/webhook.go
api/diff.go
api/receiver/appengine_mock.go
shared/appengine.go
shared/models.go
shared/run_diff.go
shared/sharedtest/appengine_mock.go

No-op refactor that introduces a `DiffAPI` abstraction to supporting adding a range of tests to various currently-untested areas of the Golang codebase.
For the most-part, just verifying that the diff views are still working should suffice for smoke-testing.

Refactor: Add DiffAPI for testability

---

api/interop.go
api/shas.go
api/test_runs.go
shared/datastore.go
shared/datastore_medium_test.go
util/populate_dev_data.go

Changes the capping/limit from key iteration to results, and adds support for the offset param (which will cause pagination to behave correctly too).
Needed for https://github.com/web-platform-tests/wpt.fyi/issues/734
- Visit https://aligned-dot-wptdashboard-staging.appspot.com/runs?aligned&max-count=500
- See more than (the current, buggy outcome of) 5 results
- Be impressed by how many aligned runs we actually have

Fix max-count behaviour for aligned runs

---

shared/test_run_filter.go
shared/test_run_filter_test.go

Recognizes the `from` param as pageable, and thus returns a `wpt-next-page` header on /api/runs?from=[RFC3339]`
Part of https://github.com/web-platform-tests/wpt.fyi/issues/636
- Visit /runs with the devtools open
- See that the request to /api/runs has a `wpt-next-page` header (token)
- Load /api/runs?page=[token]

Add time-based pagination

---

webapp/components/test-runs.html
webapp/components/wpt-runs.html

Adds a "load more" button to the bottom of the /runs list when a `wpt-next-page` header is returned from the /api/runs fetch.
- Visit https://more-dot-wptdashboard-staging.appspot.com/runs?max-count=10
- Click "Load more"
- See another 10 runs per-product
NOTE: The UI currently merges `max-count` with the default `from` param of 1 week, so it won't load more than one week's worth of runs.

Add load more button

---

.travis.yml
Makefile
api/query/cache/service/Dockerfile
api/query/cache/service/app.yaml
api/query/cache/service/main.go
util/deploy.sh
webapp/dispatch.yaml

This change adds boilerplate for a new service for handling structured test result queries. For now, the new handler simply returns `Not implemented`.
This API is intended for internal use, as a delegate to the public `/api/search` API.

Script + code boilerplate for /api/search/cache

---

api/query/cache/index/tests.go
api/query/cache/index/tests_test.go

The search cache contains shards that service queries in parallel. Each shard contains with two main parts:
1. A maping of test IDs and test names
1. A mapping of test run IDs and test IDs and result IDs
This change implements the first of these. It is a port of [this file](https://github.com/web-platform-tests/data-migration/blob/mem/grid/mem/tests.go) from the proof-of-concept implementation.
CC @KyleJu, who may end up working on a directory tree-based implementation of this and other components.

Add "Tests" part of search cache index

---

api/query/cache/index/results.go
api/query/cache/index/results_test.go
api/query/cache/index/tests.go

Search cache index: Add "results" part of index  …
The search cache contains shards that service queries in parallel. Each shard contains with two main parts:
1. A maping of test IDs and test names
1. A mapping of test run IDs and test IDs and result IDs
This change implements the second of these. It is a port of [this file](https://github.com/web-platform-tests/data-migration/blob/mem/grid/mem/results.go) from the proof-of-concept implementation.
_Aside_: Also update formatting and documentation in `tests.go` for consistency with `results.go`.
CC @KyleJu

 Search cache index: Add "results" part of index

---

api/checks/update.go

We name the pending check after the browser name, but the completed check is being named after the full product spec for the TestRun, which leaves the differently-named pending runs hanging.

Use only browser name in check name

---

api/checks/summaries/compile.go
api/checks/summaries/compile_test.go
api/checks/summaries/regressed.md
api/checks/update.go
shared/run_diff.go

We were comparing the PR as the 'before' state, which fails to ignore tests which aren't present in the affected tests for the PR execution (and thus shows all failing tests on master as regressions).

Correct the order of the diff used in regressions

---

shared/models.go

We will need to extract the AppID instead of fixing it to the staging.wpt.fyi App once we deploy to prod, but also needed for a testing copy of the App used in #829.

Add AppID field

---

api/checks/update.go

While we need to ignore file-level deletes to compare full master runs to PR runs, it's probably a safe bet that we need to highlight a reduction in the number of _subtests_.
[Here's an example.](https://staging.wpt.fyi/results/accelerometer?product=firefox-65.0a1-linux-18.04%4002621fd7b6&product=firefox-65.0a1-linux-18.04%409c669769fa&diff&q=idlharness)

Count subtest deletion as a regression

---

api/query/cache/index/index.go
api/query/cache/index/index_medium_test.go
api/query/cache/index/index_mock.go
api/query/cache/index/index_test.go
api/query/cache/index/results.go

- `Index` stores `Tests` and shards of `Results`
- `Index` carefully manages repeated and/or concurrent attempts to add same run
- Test new `Index` functionality + medium test for "run eviction relieves memory pressure"
CC @KyleJu

Test & implement search cache index stores all run+test+result data

---

results-processor/processor.py

There is no longer an active plan to implement the Spanner-backed
structured search in the short term, so let us remove the hook. The
function definition is still left as an example.

[processor] Disable push to Spanner

---

api/checks/summaries/_pr_and_master_specs.md
api/checks/summaries/_successfully_scraped.md
api/checks/summaries/compile.go
api/checks/summaries/compile_test.go
api/checks/summaries/completed.go
api/checks/summaries/completed.md
api/checks/summaries/pending.go
api/checks/summaries/regressed.go
api/checks/summaries/regressed.md
api/checks/update.go
shared/util.go
shared/util_test.go

They should be roughly similar, except for the "stuff regressed" and "stuff is fine" messages.
This PR refactors stuff out of `Regressed` and adds a results table to the `Completed` summary.

Consolidate Completed/Regressed summaries

---

results-processor/wptreport.py
results-processor/wptreport_test.py

In addition to the canonical terms, also add the raw browser_channel as
a label.
Fixes #611.
It'd be easier to look at the changes in tests.

[processor] Add the raw browser_channel as a label

---

results-processor/app.yaml
results-processor/gsutil.py
results-processor/main.py
results-processor/processor.py
results-processor/requirements.txt

We don't really need to synchronize the directories. `rsync` used to save us time when the results already exist, but such scenario is becoming less likely following #746. Therefore, we can switch to `cp` which uses less CPU in general, and is easier to parallelize.
Based on monitoring, we only use ~1MB/s network bandwidth during the recursive upload, which is far less than the available bandwidth between GCE & GCS, while on the other hand we use almost 100% CPU. In other words, we are CPU-bound because of the sheer amount of small files. With this PR, we are able to bring down the average upload time (for a full run) from ~30min to ~5min.
Additional drive-by changes:
1. Fix the logging setup that's broken by google.cloud imports.
2. Use logging.warning instead of the deprecated …

Speed up results processor by using cp instead of rsync

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

It is OK to have some failing tasks in a Taskcluster group, in which
case we will just drop the corresponding browser in that group to
prevent incomplete results but still keep the other browsers with
complete results.
Fixes #835 .

Accept Taskcluster groups with failing tasks

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

Prevents checks hanging in a pending status, when they were never going to succeed.
e.g. https://github.com/web-platform-tests/wpt/pull/14309

Don't create a pending check unless create succeeds

---

api/query/atoms.go
api/query/atoms_test.go
api/query/concrete_query.go
api/query/plan.go
api/query/search.go

- Interpret `query.AbstractQuery` (formerly `query.query) as `query.ConcreteQuery`
- This constitutes binding an unmarshaled query to a set of runs
- Export `ConcreteQuery` implementations so that query service strategies can reason about their constituent parts
This work is towards the search cache, but multiple cache search indexing strategies (in different packages) may be implemented to service instances of `ConcreteQuery`. Hence the code lives in `query`, not `cache`, and must be exported.

Search API: Test & implement query interpretation

---

api/checks/api.go
api/checks/api_mock.go
api/checks/jwt.go
api/checks/runs.go
api/checks/summaries/compile.go
api/checks/summaries/completed.go
api/checks/summaries/pending.go
api/checks/summaries/regressed.go
api/checks/webhook.go
api/checks/webhook_test.go
api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
api/test_runs.go
shared/run_diff.go

No longer needed now that https://github.com/google/go-github/pull/1063 has landed.

Remove custom go-github branch

---

api/checks/api.go
api/checks/runs.go
api/checks/summaries/compile.go
api/checks/update.go
shared/params.go

Allows a more complete product spec to be named as a more simple one, so that we're not computing the check name separately.

Fix check run naming

---

api/query/atoms.go
api/query/atoms_test.go

Abstract queries need to be instantiated from other packages for testing purposes. Exporting them is cleaner than requiring such tests to unmarshal JSON to instantiate an opaque query object.

Export symbols from query for use in other packages

---

api/query/cache/index/filter.go
api/query/cache/index/index.go
api/query/cache/index/index_test.go
api/query/cache/index/tests.go
api/query/cache/index/tests_test.go

Drop use of sync.Map in favour of critical sections that ensure a stable state when reading from and writing to index.

Fix cache index synchronization

---

api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go

Plans on a sharded index are implemented by executing a slice of filters, or a ShardedFilter, in parallel. This change introduces filter functions that mirror query atoms. A sharded index creates a slice of filters, or ShardedFilter, that correspond to its shards during the binding phase, then the ShardedFilter can be executed during the execution phase.
This change also creates a placeholder file for forthcoming index+filter bind+execute tests.

Search cache: Add filter functions implementations of Plan

---

api/checks/api.go
api/checks/runs.go
api/checks/summaries/compile.go
api/checks/update.go
shared/models.go

Attempts to prevent check run name mismatching with a two-pronged approach:
- Include the experimental label when converting a TestRun into a product spec
- Pass the existing TestRun to the update method, and compare it to (any) existing run's name-specs

Where applicable, update existing check-runs

---

api/checks/webhook.go
api/checks/webhook_test.go

Step towards #714 by currying an artifact URL from the details URL.
Unfortunately I've had to wrap the `CheckRunEvent` to get the `detailts_url` field, until I land https://github.com/google/go-github/pull/1065

Handle azure completed events

---

api/receiver/receive_results.go
api/receiver/receive_results_test.go

We tried to support `callback_url` in #788, but I missed a request-layer in the conceptual model.

Plumb the callback_url from api/results/upload to TaskQueue

---

api/checks/update.go
api/checks/update_medium_test.go
shared/models.go

Part of #866 
Ensures that the master run we compare to occurred before the run we are comparing it to. This is important for checks on the `master` branch itself, but also for avoiding a master branch that might have run away with other changes while we were processing the PR.

In regression checks, load an earlier master to diff against

---

api/query/cache/index/aggregator.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/cache/index/index_test.go
api/query/concrete_query.go

This change introduces aggregating of search results.
The initial design for this was to separate `Query -> []TestID` "indexed querying" from `[]TestID -> []SearchResult` "result aggregation". The intention was to reuse aggregation across different storage strategies. However, aggregation in the cache requires access to the appropriate shard's test+result data.
This PR implements "result aggregation" as an implementation detail of the cache filters' `Plan.Execute()`. Tests for bind+execute are updated accordingly.

Aggregate search results

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
shared/util.go

This change extends the set of valid task names to accept the
"*-results-without-changes" tasks that are being added in
https://github.com/web-platform-tests/wpt/pull/14382 . The change also
adds a "pr_base" label to these special runs, and "pr_head" to the PR
runs with the changes to prepare for the next step: using these runs
to calculate PR regressions (not implemented in this change).
Related to #708 .

Harvest the "without changes" runs from Taskcluster

---

api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/index.go
api/query/cache/index/index_mock.go
api/query/cache/service/main.go
api/query/search.go

This change implements the `/api/search/cache` endpoint with a cache that backfills from the time it is started.
Tests for this endpoint and integration for posting new test runs will be implemented in follow-up PRs.

Search cache: Implement query handler with backfilling only

---

api/checks/runs.go

In the (abnormal) case that we have multiple CheckSuites for different apps, we were erroring trying to patch with the wrong creds. This change stops one suite's error blocking other suites, and also ensures that we don't mismatch App ID.

Try all suites on error, and match App IDs

---

webapp/components/loading-state.html
webapp/components/wpt-flags.html
webapp/components/wpt-results.html

Work towards https://github.com/web-platform-tests/wpt.fyi/issues/56
Asynchronously loads the latest manifest and uses that as the source-of-truth on the exhaustive list of tests that execute.
See homepage of auto-deployed environment.

Use manifest as source of test paths

---

api/query/search.go
api/query/search_medium_test.go
api/query/search_test.go
api/receiver/appengine_mock.go
shared/appengine.go
shared/sharedtest/appengine_mock.go

This change tests and implements `/api/search` delegating to `/api/search/cache` when the request is a structured query that cannot be serviced using summary files.
The change required some refactoring of the handlers in `search.go` to ensure that an `AppEngineAPI` instance is attached to the handlers. The `AppEngineAPI` is used to instantiate a `*http.Client`, which is done in a special way in AppEngine Standard, and is mocked in tests.

Connect search API frontend to cache backend

---

api/query/cache/backfill/backfill.go
api/query/cache/index/index.go
api/query/cache/poll/poll.go
api/query/cache/service/main.go

This change implements a polling strategy to load newer runs (runs added after cache backfill started). It also integrates polling into the cache's production setup routine.
Since, for now, this is the only mechanism for receiving new runs, the default polling configuration is relatively aggressive: Load up to 10 new runs every 10 seconds. The frequency can be reduced if/when we implement best effort pushing of runs from the processor to the cache on the processor's critical path. The purpose of implemention such a scheme would be to ensure that runs are cached before they are committed to datastore and begin showing up in the wpt.fyi UI.

Search cache: Add load-newer-runs update

---

api/query/atoms.go
api/query/atoms_test.go

`POST` to `/api/search` is returning `HTTP 400`. The source of this appears to be that `{"query": {"pattern": ""}...}` is interpreted as `"pattern"` being missing. This change fixes the issue by differentiating between a missing `"pattern"` key and a key that contains the empty string value.

Modify TestNamePattern unmarshaling to handle empty string pattern

---

api/query/cache/index/aggregator.go
api/query/cache/index/index_filter_test.go

To achieve identical behaviour to existing test run summaries the search cache, which iterates over all (sub)tests for all runs in the cache, must exclude from each runs total those (sub)tests that have status=UNKNOWN, i.e., those tests that do not appear in the corresponding test run report.

Search cache: Exclude missing tests from each run total

---

api/checks/update.go

Prior to #881 we were deliberately not including `D` in the diff filter, since comparisons from a full master run to affected tests on a PR will always make it seem like we deleted a huge number of tests.
Now, we compare either `master` to a less recent run of `master`, or affected tests with/without the change; in both cases, deleted tests matter a lot.

Show deleted changes in diff

---

Makefile
api/taskcluster/webhook.go
api/taskcluster/webhook_test.go

Prevents permanently-pending PRs when one, but not both, fail.
Unrelated driveby to make `prepush` not verbose.

Don't process pr_head/pr_base if the counterpart's task didn't succeed

---

webapp/components/wpt-results.html

Fixes the manifest-based test-list feature, currently broken for navigation to any folder/path.
Head to /flags, enable the manifest one, navigate to any path, see a normal-looking list.

Filter manifest tests by prefix

---

webapp/components/test-search.html
webapp/components/test/test-search.html

This change addresses malformed request errors coming from `POST` to `/api/search`. Current payloads use the key `browserName`, which should be `browser_name`.

Properly snake_case POSTable query object client-side

---

webapp/components/test-runs-query.html
webapp/components/test-runs.html
webapp/templates/_test_run_query_params.html
webapp/test_results_handler.go

Support loading /results with a `run_id` param (or a few), by plumbing the params through to the component.
- Load /results?run_id=[A run ID]&run_id=[Another run ID]
- Be amazed
This is a precursor to a better fix for #889

Plumb run_id params through the UI

---

api/query/search.go
api/query/search_test.go

This change addresses two issues identified in `/api/search` handlers:
1. `POST` requests to `/api/search` were erroneously being served from memcache using their URL;
1. Logger management in `structuredSearchHandler` was not using an `AppEngineContext`, and no logging was capturing the details of search cache request errors.
This change fixes the issues by constructing different cache keys based on `/api/search` HTTP method, constructing contexts correctly, and logging the status+response payload when requests to `/api/search/cache` fail.

Search cache: Fix cache key bug and add more logging

---

webapp/components/product-info.html
webapp/components/test-runs-query-builder.html
webapp/components/test-runs-query.html
webapp/components/test/test-runs-query-builder.html
webapp/components/test/test-runs-query.html

See #538 
"Dev" is a Chrome-specific name, and not something we reflect on wpt.fyi.
Also moves the set into a property-accessor on a namespacing wpt object as a cleanup.

Drop dev from builder channels

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Another attempt to fix https://github.com/web-platform-tests/wpt/issues/14465 from the wpt.fyi side. This PR normalizes the version string of STP in the results processor. The raw report stored to GCS won't be modified, but the browser version field in Datastore will store the normalized version.
e.g. "Technology Preview (Release 67, 13607.1.9.0.1)" -> "67 preview" (which will be parsed by the Go code into: major=67, channel=preview)

Normalize version strings in processor

---

shared/spanner.go

According to https://searchfox.org/mozilla-central/source/testing/mozbase/mozlog/mozlog/logtypes.py#184-196 at time of authorship.
```python
class Status(DataType):
allowed = ["PASS", "FAIL", "OK", "ERROR", "TIMEOUT", "CRASH", "ASSERT", "SKIP"]
def convert(self, data):
value = data.upper()
if value not in self.allowed:
raise ValueError
return value
class SubStatus(Status):
allowed = ["PASS", "FAIL", "ERROR", "TIMEOUT", "ASSERT", "NOTRUN", "SKIP"]
```
According to @jgraham this is not currently used, in practice, by Mozilla, but the intent is that a halting but non-crashing assertion failed.

Add test status value: "ASSERT"

---

api/checks/update.go
api/checks/update_test.go
api/diff.go
shared/run_diff.go
shared/run_diff_test.go

Iteratively reduce the maximum depth of the paths by collapsing folders until the total number of folders is under the limit desired (or they can't be collapsed further).
This is needed for full runs, where we're showing 10 results from 2dcontext, "And 1000s more..."

Collapse results summaries for non-regression output

---

api/query/cache/backfill/backfill.go
api/query/cache/service/main.go

Two changes:
Between:
- A conservative initial size-of-run estimate;
- The fact that many runs only contain affected tests from PRs now;
- Backfill infrastructure should stop backfill when running low on space anyway...
this change proposes decreasing the estimated bytes-per-run that is used to limit the Datastore query for backfilling a search cache instance.
Recent changes to the `app.yaml` deployment spec for the `searchcache` service mean that we can safely double our soft memory limit.

Search cache: Update backfill params

---

api/query/cache/query/query.go
api/query/cache/query/query_test.go
api/query/cache/service/main.go

This change abstracts and tests the step of filtering out tests that appear nowhere in the result reports of relevant test runs.
The unit tests are offer loose constraints. It may be worth adding medium or large tests that validate that index behaviour under the transformed query matches expectations.

Search cache: Abstract and test "preparing" a "user query"

---

api/checks/update_medium_test.go
api/interop_medium_test.go
api/manifest.go
api/shas_medium_test.go
api/test_runs_medium_test.go
shared/datastore.go
shared/datastore_medium_test.go
shared/models.go
shared/params.go
shared/params_test.go
util/populate_dev_data.go
util/populate_dev_data.py
webdriver/webapp_server.go

Changes the datastore treatment of the `sha` param to be "a prefix of the `FullRevisionHash` field".
This steps towards #49 and also supports 7-char SHAs.

Treat sha as a prefix of FullRevisionHash

---

api/query/cache/index/filter.go
api/query/cache/index/index.go
api/query/cache/index/results.go

Presently there is a mutex guarding read and write to the entire searchcache index. However, one of its read operations gives an index-type object shared custody of test+result data, which leads to a concurrency bug when the index-type object attempts to read from the shared structures while the enclosing Index shard is performing a write operation on the same shared structure.
This change introduces a sync.RWMutex for each shard. A pointer to the mutex is passed to index-type objects so they can acquire a read lock. The Index-type implementation is updated to synchronize its access to shard data as too.

Fix intrashard concurrency bug

---

shared/params.go
shared/params_test.go

Fixes a runtime error seen in prod.
> runtime error: invalid memory address or nil pointer dereference
> at panic (go/src/runtime/panic.go:491)
> at github.com/web-platform-tests/wpt.fyi/shared.ParseTestRunFilterParams (params.go:641)
> at github.com/web-platform-tests/wpt.fyi/api.apiTestRunsHandler (test_runs.go:61)
> at github.com/web-platform-tests/wpt.fyi/shared.WrapPermissiveCORS.func1 (routing.go:46)
> at github.com/web-platform-tests/wpt.fyi/shared.WrapApplicationJSON.func1 (routing.go:55)
> at github.com/web-platform-tests/wpt.fyi/shared.WrapHSTS.func1 (routing.go:37)
> at net/http.HandlerFunc.ServeHTTP (server.go:1918)
> at github.com/gorilla/mux.(*Router).ServeHTTP (mux.go:162)

Fix nil pointer error for pagination

---

shared/params.go
shared/params_test.go

Typing a date that requires RFC3339 is tedious, so we should just consider anything we're given for parsing and do a best-effort. 
The unit test's cases demonstrate the possibilities.

Make date/time query param parsing more flexible

---

shared/models.go
shared/run_diff.go

Further work on #663 
Note that GitHub uses the triple-dot algorithm when comparing, so even if master runs away from the PR's commit, the differences will be the master-branch point to tip-of-PR-branch, which is exactly what we want.
- Load /api/diff?run_id=5969501392732160&run_id=5487233003945984
- See a rename of /workers/importscripts_mime.tentative.any.js

Diff with HEAD for finding renames in pr_base

---

api/query/cache/index/index.go
api/query/cache/lru/lru.go
api/query/cache/lru/lru_test.go

Currently `searchcache` evicts runs according to their "time started". This change usees an LRU strategy for evicting test runs instead.

Test, implement & integrate: LRU strategy for test runs in searchcache

---

webapp/components/test-runs-query-builder.html
webapp/components/wpt-runs.html

Changes the message to be visible at all times, instead of only when runs are loaded.

Keep the query message visible between submissions in /runs

---

api/checks/api.go
api/checks/summaries/actions.go
api/checks/summaries/pending.go
api/checks/summaries/regressed.go

wpt blocks on cancelled checks, so include the ignore action to mark them successful.
Also, drive-by reorganization of the actions to all be in one file.

Add ignore action to cancelled check

---

webapp/components/interop.html
webapp/components/self-navigator.html
webapp/components/wpt-results.html
webapp/components/wpt-runs.html

More builder work (https://github.com/web-platform-tests/wpt.fyi/issues/535)
When the query is submitted on /runs tab, persist it to the URL.
- Visit the /runs page
- Change the query, submit
- See the changes in the URL
- Reload the page, see the same results

Persist /runs query changes in the URL

---

api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
webapp/components/wpt-flags.html

Stops pending checks for now, until we've resolved empty report behaviour.

Put pending checks behind a feature

---

api/azure/webhook.go
api/taskcluster/webhook.go

Will help authors easily check for their own runs arriving.

Include sender as label for results

---

webapp/index.yaml

#929 changed `sha` param behaviour, but forgot to create the indexes (because locally, everything is indexed).
This takes all indexes with `Revision` and duplicates them to the same index with `FullRevisionHash`.

Add FullRevisionHash indexes

---

api/checks/runs.go
shared/run_diff.go
shared/util.go

We sometimes use "HEAD" for the before in the diff, but are trying to log a 7 char slice of that.

Fix 500s for HEAD rev

---

api/azure/webhook.go
api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
shared/params.go
shared/util.go

Follow up some concerns about https://github.com/web-platform-tests/wpt.fyi/pull/961
Prefixes username labelling behaviour with `user:` to ensure we don't clash with existing semantic labels, like `master` or `firefox`. Little bit of paranoid programming here, but beats the headache of trying to retroactively fix the data if we manage to find a username that causes problems.
Treats `?user=lukebjerring` as an alias for `?label=user:lukebjerring`

Prefix user, add user param

---

api/checks/summaries/actions.go
api/checks/summaries/actions_test.go

The actions were tweaked in #949 and totally broke things in a not-obvious way. This adds a test that prevents future changes and brings the descriptions back to accepted lengths.

Fix the length of all action fields

---

api/checks/update.go
shared/params.go

Right now the `/api/shas` endpoint serves 10-char SHAs, which makes piping those into /api/checks/[SHA:40] a problem.
I'll change the SHAs endpoint to take a `length` param later, but this makes life easier now.

Allow shorter shas in /api/checks/[SHA]

---

webapp/templates/test-runs.html
webapp/test_runs_handler.go

Part of #973 
Fixes the behaviour of the pr param in /runs, by including parsing + plumbing to the UI (the rest of the code is already present from #786

Plumb the pr param in /runs view

---

api/checks/update.go
api/checks/webhook.go
api/diff.go
api/interop.go
api/query/cache/backfill/backfill.go
api/query/cache/backfill/backfill_medium_test.go
api/query/cache/backfill/backfill_mock.go
api/query/cache/poll/poll.go
api/query/query.go
api/results_redirect_handler.go
api/shas.go
api/test_run.go
api/test_runs.go
api/versions.go
shared/datastore.go
shared/datastore_ae.go
shared/datastore_cloud.go
shared/datastore_medium_test.go
shared/models.go
shared/run_diff.go
util/populate_dev_data.go

Refactors the datastore code to support being inside or outside appengine standard, so that we can call the shared library methods for fetching runs with our query params (max-count, etc).
Then, uses the shared library to ensure we get the same number of each product, instead of a disproportionately large number of runs for chrome/firefox (which happen much, much more frequently).
This will allow us to run the flakiness queries against safari / edge.

Tweak the backfill behaviour to get the same number of each product

---

util/populate_dev_data.go
webapp/components/test-results-chart.html
webapp/components/test-results-history-grid.html
webapp/components/test-runs.html
webapp/components/wpt-results.html

Changes the behaviour of the history components to correctly re-use the query parameters.
In turn, this ensures that we're fetching runs that match the query for the main results above the history section.

Consolidate history query params

---

webapp/app.yaml
webapp/components/wpt-flags.html
webapp/routes.go
webapp/service-worker-installer.js
webapp/service_worker_handler.go
webapp/service_worker_handler_test.go
webapp/templates/_head_common.html
webapp/templates/service-worker.js

Adds a dynamic endpoint for `/service-worker.js` that, for valid releases (versions that are a 7-char SHA), crawls the /static/ and /components/ dirs in webapp and preemptively caches all of those requests.
Also caches /bower_components/ requests, but waits for a caller to have requested them (so that we can filter down to files that are actually in use. The directory tree is huge).
Also adds a 1d public-cache duration for the /static/ dir (was 10m).

Add a feature for including a service worker to cache components

---

Makefile
util/cleanup-versions.sh
util/deploy.sh

Changes the staging pushes to deploy and promote a versioned release, rather than clobbering the `master` version (which happens to serve all the traffic).
No tangible change to our release flow, except that staging.wpt.fyi's version will we a 7-char SHA, same as prod, which allows us to leverage a service-worker without risk of stale cache (see #979)

Distinguish release version and promote

---

api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/cache/index/index_test.go
api/query/cache/query/query.go
api/query/concrete_query.go

This change implements server-side changes for a search syntax like `edge:!PASS`. This is different from `!edge:PASS` because if there are two Edge runs being queried, `e1` and `e2`, the new syntax (former) expands to `e1-status != PASS | e2-status != PASS`, whereas the existing syntax (latter) expands to `!(e1-status = PASS | e2-status = PASS)` or `e1-status != PASS & e2-status != PASS`.

Search API: Server-side changes for 'browser NEQ status' syntax

---

webapp/components/test-results-chart.js
webapp/package.json

Changes to use the (correct + working) `@google-web-components` package.
https://www.webcomponents.org/element/@google-web-components/google-chart

Fix google-chart package

---

Makefile
util/wct.sh

Based on my observation, L112 in the original `Makefile` behaves differently on Travis. Namely, the `exit 1` statement seems to kill the whole `make` process. For example, this [Travis log](https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/169019618#L3330) did not have the following critical lines as on my local workstation:
```
Makefile:103: recipe for target 'web_components_test' failed
make: *** [web_components_test] Error 1   
```
L112 has too much magic after all (subshells connected with boolean operators). The reason was to ensure we could kill Xvfb regardless of test results. This can be better achieved by using a `trap` in a separate Bash script, which is what this PR does.
We should see web components test **red** on Travis with this PR.

Move WCT out of Makefile and ensure it fails reliably

---

api/taskcluster/webhook_test.go
util/commands.sh
util/docker-dev/run.sh
webdriver/chrome.go
webdriver/label_test.go
webdriver/path_test.go
webdriver/product_test.go
webdriver/search_test.go
webdriver/test_runs_test.go

1. Stop panicking unnecessarily in webdriver tests.
2. Properly set up the user group inside Docker and start the container with the SYS_ADMIN cap to allow ensure Chrome can use sandbox inside Docker.

Fix crashing in integration tests

---

webapp/package-lock.json
webdriver/anomalies_test.go
webdriver/file_results_test.go
webdriver/label_test.go
webdriver/search_test.go
webdriver/test_runs_test.go
webdriver/webdriver.go

#999 updated FF v62 to v64, which we didn't notice fully breaking go_firefox_test because of other ongoing issues.
It's broken because they launched shadow dom in v63 (yay!) but don't support sending keys to shadow dom inputs (boo!)

Fix go_firefox_test

---

api/checks/jwt.go

Checks for the block being nil and returns an error when it is, to avoid a panic.

Avoid nil pointer

---

api/checks/api.go
api/checks/api_mock.go
api/checks/webhook.go
api/checks/webhook_test.go

Uses the production wpt.fyi installation if the events are arriving in production.

Create suite for different app depending on environment

---

api/query/cache/backfill/backfill.go

- Provide logger on context
- Use `shared.GetDefaultProducts()`, not `nil`

Fix backfill test run metadata loading

---

shared/datastore.go

Passing `nil` (or an empty slice) as `products` to `loadTestRuns()` follows a bunch of application logic that eventually iterates over `products` and therefore always returns an empty set.
Instead, return an error immediately: such a vacuous query is almost certainly _not_ what the client code intended.

datastore: Add `len()` check to signal vacuous `loadTestRuns()` call

---

webapp/package-lock.json

Primary doc: https://docs.npmjs.com/files/package-locks
> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.
To answer my own question earlier, the difference between `package-lock.json` and `npm-shrinkwrap.json` is that the latter can be published to npm.
> Unlike package-lock.json, npm-shrinkwrap.json may be included when publishing a …

Restore package-lock.json

---

Makefile

Only attempt to use a local client-secret.json when there's not a logged in user.
This supports a human who's logged in via `gcloud auth login` to run `make deploy_production` successfully.

Handle non-service-account logins

---

api/query/cache/service/main.go
api/query/search.go

This change allows `searchcache` to return `HTTP 422` and partial results when at least one, but not all, runs needed to service a query are found in the cache.
This allows clients to render partial results and decide whether or not to retry the query later to get more complete results.

searchcache: When some runs missing, HTTP 422 + partial results

---

api/test_runs.go

Changes the behaviour of querying for multiple shas, to not implicitly set a max-count of one result for each product. (For other queries, such as no params, the default is one result per product).
If a user wants exactly one result per product (across 2 shas) they can add the param explicitly.

Allow multiple results per product when more than 1 sha

---

api/README.md
api/receiver/create_run_test.go
api/receiver/receive_results.go
api/receiver/receive_results_test.go

This PR allows uploaders to send multiple (chunked) files in a multipart
/api/results/upload request.
Works alongside with #1022 .

[receiver] Allow multiple result_file fields

---

api/query/cache/service/main.go

This change fault that occurs during query execution that can be traced to expanding a query with `PrepareUserQuery` using different run IDs than those that correspond to the runs that are later used to bind the query.
The change accumulates `ids` (for expansion) and `runs` (for binding) together, tracking only the runs that are resident in the `Index`. This ensures correct prep+bind+execute behaviour, including correct error handling if one of the runs is removed from the `Index` between `ids`/`runs` accumulation and one of prep|bind|execute.

Ensure same runs: `q.PrepareUserQuery(runIDs)` and `idx.Bind(runs, q)`

---

api/labels.go
api/labels_medium_test.go
api/routes.go

Resolves https://github.com/web-platform-tests/wpt.fyi/issues/329
Adds a endpoint /api/labels that lists all of the labels used on any runs.
Loads `TestRun` entities with all distinct `Labels`, aggregates them into a set, spits out a sorted array, caches the whole request for 5 min.

Add /api/labels endpoint

---

webapp/components/results-navigation.js
webapp/components/wpt-flags.js
webapp/components/wpt-permalinks.js
webapp/components/wpt-results.js
webapp/package-lock.json
webapp/package.json

Fixes #645 
Adds a small "Link" button next to "Edit" in the query banner, which opens a dialog allowing the user to tweak the URL a bit and copy to the clipboard with a click (in Chrome/FF, at least).
- Head to /flags, enable the permalink flag
- Visit the homepage, nav to a directory somewhere
- Hit edit, toggle the tickboxes, copy to clipboard

Add feature for copying a permalink

---

api/query/search.go
api/query/search_test.go
api/receiver/appengine_mock.go
shared/appengine.go
shared/sharedtest/appengine_mock.go

Ensures we get a versioned external service hostname, so that branches like https://github.com/web-platform-tests/wpt.fyi/pull/1057 keep the webapp and searchcache in sync, so the changes can be tested in the UI.

Add api method for getting versioned service hostname

---

api/azure/api.go
api/checks/api.go
api/checks/summaries/compile.go
api/checks/summaries/compile_test.go
api/checks/summaries/completed.go
api/checks/summaries/pending.go
api/checks/update.go

Related to #850 
We have duplicated staging/prod wpt.fyi checks on some whitelisted users, and the title on the landing page is not distinct (both hard-coded to wpt.fyi). This PR changes it to actually grab the hostname and use that, so the staging checks will have staging.wpt.fyi in the title.

Use variable hostname in check title

---

api/checks/update.go
webapp/components/wpt-flags.js

Regardless of whether we use neutral for newly-failing / deleted results, always set a pass status when we don't see anything amiss.
Change the non-neutral status to "action_required" instead of failing - fail is too aggressive and might discourage people adding failing tests.
Docs for valid "conclusion" field values:
https://developer.github.com/v3/checks/runs/#update-a-check-run
cc @jgraham

Always pass non-regressing checks, and use action_required instead of failure

---

api/checks/summaries/_pr_runs_links.md

Follows up to improvement of #1008 to cap per-product results at just one item.

Show only one pr_head run in checks pr link

---

results-processor/wptreport.py
results-processor/wptreport_test.py

Firefox started to add browser_build_id (a minor revision number to
run_info), which is different before and after a release cut (for
reference, Nightly is released twice a day), so jobs around release cuts
might be rejected as their chunks may have different build IDs.
In most cases, the minor difference in revisions isn't a big problem,
and having results available is generally more important. Besides, we
had been accepting results with different builds before the introduction
of the build ID field.

[processor] Ignore inconsistent browser_build_id

---

webapp/components/wpt-flags.js
webapp/components/wpt-results.js

Resolves https://github.com/web-platform-tests/wpt.fyi/issues/149
Adds a feature for including a link to the ref, in addition to the test itself. This is implemented by leveraging the manifest.
Naively assumes a single ref, with an `==`. Other cases (rare) will be added in the future.

Include a link to the ref for reftests

---

results-processor/wptreport.py
results-processor/wptreport_test.py

In ac86e63f4c3badf9c5547edaa6c391950387fe90, we allowed browser_build_id
to be different but forgot browser_changeset.

[processor] Also ignore inconsistent browser_changeset

---

webapp/components/wpt-results.js

Fixes #1052 
- Make sure you enable the manifest (/flags, tick the load a manifest feature)
- Load the homepage
- Load https://manifest-dot-wptdashboard-staging.appspot.com/results/css/css-backgrounds?label=master&label=experimental&max-count=10&product=firefox&q=%28firefox%3Apass%7Cfirefox%3Aok%29+%28firefox%3Atimeout%7Cfirefox%3Aerror%7Cfirefox%3Afail%29
You should see only the flaky results, not 0/0 all over the place.

Don't list all the tests found in the manifest if searching.

---

api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/index_filter_test.go
api/query/cache/index/index_test.go
shared/params.go
webapp/components/test-search.js
webapp/components/test/test-search.html

Consolidates the product-spec parsing behaviour of `product` query params and "browser_name" in structured queries to use the same parsing logic server-side.
In turn, this facilitates searching for version-specific statuses, which we can use to find potential regressions in major releases, with `chrome-64:fail chrome-63:pass` type of thing.

Change browser_name to product in searchcache

---

api/checks/update.go
shared/util.go
shared/util_test.go

Resolves https://github.com/web-platform-tests/wpt.fyi/issues/1070
Finds the deepest shared path, and set that as the URL's path.
To test this change, we'll need an [example](https://github.com/web-platform-tests/wpt/pull/15067/checks?check_run_id=54652355) that does a poor job.
Once the enviroment is deployed, we can POST to /api/checks/[SHA]?product=chrome (example is b842c84)
That will recompute the links, with this PR's changes.

Set diff results path to deepest shared dir

---

api/query/search.go
api/query/search_medium_test.go

#1057 broke the check for a "simple" query, causing simple queries to bypass the summaries, causing a regression in performance (particularly for uncommon data), which in turn is timing out some integration tests.

Fix simple (empty) queries

---

api/query/cache/index/aggregator.go
api/query/search.go

Adds a (yet unused) flag to the aggregator, to emit an array of subtest names.
This will be followed by a change to set the flag to true when searching for a specific test-file path.

Add includeSubtests flag for emitting subtest names

---

api/query/cache/index/index.go

Fixes a bug where only one (repeated) subtest name is ever returned for any test.

Fix loop variable pointer reuse

---

api/query/routes.go
shared/routing.go
webapp/routes_test.go

Mozilla would like to use it externally.

Add permissive CORS for /api/search

---

api/query/cache/index/aggregator.go
api/query/cache/index/filter.go
api/query/cache/index/index.go
api/query/cache/index/index_filter_test.go
api/query/cache/index/index_test.go
api/query/cache/monitor/monitor_test.go
api/query/cache/service/main.go
api/query/concrete_query.go
api/query/search.go
webapp/components/test-file-results.js
webapp/components/test-search.js
webapp/components/wpt-results.js

Checks for ?subtests param and plumbs the option to include subtests in the response.
Then, leverages the functionality from the client in order to filter the results on an individual test file page.
Fix for #81 (and duplicate #1048)

Filter the matching subtests for individual tests pages

---

api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/aggregator.go
api/query/cache/index/index_test.go
api/query/cache/service/main.go
api/query/concrete_query.go
api/query/search.go
shared/statuses.go

This will allow us to deprecate the results-analysis pipeline, and compute interop on the fly, including filtering to particular searches, e.g. what's the interoperability of things that Chrome is passing?
And, including custom product sets (see #655)
This PR builds off of #1103, so if you're reviewing, do so with 5599a4e...7a36891
- Grab a specific view that we have precomputed interop for
- Extract the run_id, and POST to /api/search?interop
- `{"run_ids":[6347092704362496,4879930668089344,5070059928027136,6495293554032640],"query":{"exists":[{"pattern":"/2dcontext/"}]}}`
Hopefully, see some interop scores.

Add a query param for including interop summary from /api/search

---

api/azure/webhook.go
api/azure/webhook_test.go

Follows https://github.com/web-platform-tests/wpt/pull/15110, and also allows for the old names.
Can this be tested in webhook_test.go?

Update the Azure Pipelines artifact name matching

---

webapp/components/wpt-insights.js

`!chrome:pass` is "any result that isn't a pass in chrome", which will match all the other browsers.
`chrome:!pass` is "a chrome result that isn't a pass", which is what we want.

Fix the anomalies query

---

webapp/components/interop.js

This is a best-effort to keep the code very consistent with wpt-report, so that a refactor is easy once we're always sending traffic to `/api/search`.
- Head to the interop tab
- Build queries

Add query builder to interop tab

---

shared/params.go
shared/test_run_filter.go
webapp/components/interop.js
webapp/components/test-results-chart.js
webapp/components/test-runs-query.js
webapp/templates/_test_run_query_params.html
webapp/test_results_handler.go

Handles the `offset` param in TestRun queries.
We already support the param when unmarshalling `next-page-token`, but it can also be typed manually by the user.
- Load /results?product=chrome[master]&max-count=2&offset=2
- Load /results?product=chrome[master]&max-count=2&offset=4
- See different runs.

Plumb the offset param

---

api/query/atoms.go
api/query/cache/index/aggregator.go
api/query/cache/index/index_test.go
api/query/cache/service/main.go
api/query/concrete_query.go
api/query/search.go
shared/run_diff.go
shared/statuses.go
shared/statuses_test.go
webapp/components/wpt-results.js

Adds diff param support to /api/search, computing differences for the subtests directly (instead of via summary numbers, which can cause things to cancel each other out).
This is a step towards https://github.com/web-platform-tests/wpt.fyi/issues/1071
We'll need to compute the regression diffs via the same API

Add support for diffs using searchcache

---

webapp/components/product-info.js
webapp/components/wpt-flags.js
webapp/components/wpt-results.js

Inlines a couple of iframes when we load the manifest, and are looking at a `reftest` test type.
- Visit /flags, enable the feature for reftest iframes
- Visit /results, find a reftest, e.g. /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_self.html
- See the iframes when the manifest loads.

Add feature for showing iframes for reftests

---

api/query/atoms.go
api/query/atoms_test.go
api/query/cache/index/filter.go
api/query/cache/index/index_filter_test.go
api/query/concrete_query.go
shared/run_diff.go
webapp/components/test-search.js
webapp/components/test/test-search.html

Add a `path:[test path]` atom, distinct from the `pattern` atom in that it's a prefix-match, not a case-insensitive search (and whatever else we end up doing to make it even more fuzzy).
Fixes #1132

Add "path" atom to structured queries

---

api/receiver/receive_results.go

The two sleeps between three retries are increased from (0.5s, 1s) to
(1s, 2s) to give Taskcluster more time to persist and expose the
artifacts.
This issue was identified in the logs when debugging unrelated Azure timeouts.

[receiver] Sleep longer between retries when fetching results

---

api/azure/webhook.go
api/receiver/client/client.go
api/receiver/receive_results.go
api/taskcluster/webhook.go
api/taskcluster/webhook_test.go
webapp/app.yaml

Fetching artifacts from Azure Pipelines is slow and needs to be done with a slow client.
Related to https://github.com/web-platform-tests/wpt.fyi/issues/1131

Eliminate a potential source of timeout

---

api/checks/summaries/compile.go

The name is the primary string. Travis, Azure Pipelines and
Taskcluster includes their own names as a prefix for the check run
names. This seems redundant with the suite name, but should cause the
checks to be grouped together in the (now large) list of checks on
each PR.

Move the hostname (wpt.fyi) from the check title to the name

---

webapp/components/interop.js
webapp/components/wpt-results.js
webapp/components/wpt-runs.js
webapp/static/common.css

800px is too crowded when we have more than four runs (which is getting more common now that search is heavily used). And reftest previews can be expanded a bit (also to match the default screenshot size 600x600).
See the staging deployment.

Make the page wider and expand reftest previews

---

api/query/cache/service/main.go
shared/run_diff.go

Attempt to fix #1146 
The code for detecting empty differences looks correct, so I'm speculating that the struct is being copied out of the array with each loop iteration, and clearing the field only occurs on the local copy?

Clear unchanged diffs by ref

---

Makefile

Finally took the time to read the deprecation warning today:
https://cloud.google.com/sdk/gcloud/reference/topic/filters
We need to use regex (key~^value$) to ensure full-text matching in
gcloud filters in the future. Instead of using regex, this change uses
`gcloud components list --only-local-state` to avoid filters altogther.

A small fix to avoid gcloud deprecation warnings

---

webapp/components/wpt-results.js

Part of the reason for https://github.com/web-platform-tests/wpt.fyi/issues/1143 is that we're asking for a diff (all the time). We shouldn't do that except when the client wants a diff.

Only fetch diff when requested.

---

webapp/components/test/test-runs-query.html
webapp/components/test/wpt-results.html
webapp/components/wpt-results.js

Tests is the number of entries in the /api/search, subtests is the sum of the maximum 'total' value present across each run.
Resolves https://github.com/web-platform-tests/wpt.fyi/issues/1134

Surface test-count totals in the message

---

Makefile

Simplifies the use case for running locally.

Use git branch name by default for deploy_staging

---

api/checks/webhook.go

Should fix #1130 
Disables the azure pipelines `CheckRunEvent` processing for GitHub webhooks, unless feature `processAzureCheckRunEvents` is enabled.
This PR should be coupled with a change to the non-sharded (affected-tests) Azure jobs, to fire the completion webhook.

Add feature for whether to process azure check_run events

---

webapp/components/pluralize.js
webapp/components/test-run.js
webapp/components/wpt-runs.js

Fixes #114 and https://github.com/web-platform-tests/wpt.fyi/issues/1138
Clicking a run in the /runs UI selects that run, and triggers a toast, which has a "view runs" button.
Selecting exactly two runs also shows a "view diff" button (which includes the ?diff param).
- Visit https://select-dot-wptdashboard-staging.appspot.com/runs
- Click on runs
- Be amazed

Support selecting runs in the /runs UI

---

results-processor/wptreport.py
results-processor/wptreport_test.py

When we normalize product names like "edge_webdriver", we want to add
both "edge" and "webdriver" as labels of the test run.
This was an oversight in #1119. Fixes #1176.

[processor] Add all tokens of product as labels

---

util/populate_dev_data.go
webapp/components/wpt-runs.js

Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1173
Propagates any query params used to filter the `/runs` view across to the `/results` view for specific SHAs.

Propagate /runs query params to /results?sha= links

---

webapp/components/reftest-analyzer.js
webapp/components/test/reftest-analyzer.html
webapp/package-lock.json
webapp/package.json

Start of a Polymer-based reimplementation of the reftest-analyzer, for wpt.fyi.
So far, only shows a zoomed-in view of the image.
https://github.com/mozilla/gecko-dev/blob/master/layout/tools/reftest/reftest-analyzer.xhtml
- Clone this locally, and run it
- Visit http://localhost:8080/components/test/reftest-analyzer.html
- See zoomed in pixels when you hover over the image

Add (beginnings of) ReftestAnalyzer component

---

webapp/components/wpt-results.js

Re-do of https://github.com/web-platform-tests/wpt.fyi/pull/897 after the Polymer 3 upgrade tool cleaned up the wrapping and reverted the fix.
Partial fix for the original issue filed as https://github.com/web-platform-tests/wpt.fyi/issues/896

Wrap tag endings

---

api/azure/api.go
api/azure/webhook.go

Follow up to #1190 to _actually_ fix #1160 
Example mismatch:
https://github.com/web-platform-tests/wpt/commit/a3f763720e95f805c05c4ec4ae2d9adefb441ce9
Example JSON blob for said mismatch:
https://dev.azure.com/web-platform-tests/wpt/_apis/build/builds/8534

Use pr.sourceSha

---

webapp/components/wpt-results.js

We have a mix of infrastructure(s), so show the source.

Show source icon on /results

---

webapp/components/test/interop.html
webapp/components/test/loading-state.html
webapp/components/test/path-part.html
webapp/components/test/reftest-analyzer.html
webapp/components/test/test-file-results-table-terse.html
webapp/components/test/test-file-results.html
webapp/components/test/test-run.html
webapp/components/test/test-runs-query-builder.html
webapp/components/test/test-runs-query.html
webapp/components/test/test-runs.html
webapp/components/test/test-search.html
webapp/components/test/wpt-flags.html
webapp/components/test/wpt-permalinks.html
webapp/components/test/wpt-results.html
webapp/package-lock.json
webapp/package.json

With the following changes by the way:
* Add `license` and `repository` fields to `package.json`
* Switch to `webcomponents-loader` (from `bundle`) in tests to be more
consistent with the real pages and in the hope of speeding up tests a
bit (much smaller JS size).

Trivial npm upgrade

---

api/query/cache/index/aggregator.go
api/query/cache/service/main.go
api/query/concrete_query.go
shared/statuses.go
webapp/components/wpt-flags.js

Hack at https://github.com/web-platform-tests/wpt.fyi/issues/62
Note that this relies on at least one of the runs having a non-ambiguous status (the `OK` status), which should™ usually be the case.

Add feature for ignore testharness status (OK) in summary counts

---

webapp/admin_handler.go
webapp/admin_handler_test.go
webapp/app.yaml

instead of implementing the login redirect ourselves in Go. This
simplifies the code as well as avoids future omission of admin
authentication.
A rather trivial change.

Rely on AppEngine to authenticate admin/ pages

---

webapp/components/interop.js
webapp/components/wpt-flags.js
webapp/components/wpt-results.js

Fix #380. Add a flag to enable web-platform-tests.live.
- Visit /flags, enable the feature for web-platform-tests.live
- Visit /results, find a test
- Click on Run in your browser on web-platform-tests.live
- See if it directs to a web-platform-tests.live page and the result is shown properly

Add a flag to enable web-platform-tests.live instead of w3c-test.org

---

api/screenshot/model.go

We would only save retrieving one field (labels) with projection, but it
requires two additional composite indexes (with and without labels), so
it is not really worthwhile.

No longer use projection in the screenshot API

---

shared/browsers_test.go
shared/errors.go
shared/errors_test.go

The New method has to return an error interface instead of a concrete
type. This is not only in accordance with the best practice (errors are
checked by type assertions[1]), but also avoids a weird issue when
assigning the return value to a predeclared variable of type error:
(error)(nil) != (*MultiError)(nil).
Add a test to prevent regressing this subtle intentional behaviour.
Drive-by fix: remove unnecessary tags in browsers_test.go.
[1]: https://blog.golang.org/error-handling-and-go

Fix the custom error type MultiError

---

shared/test_run_filter_test.go

```go
// Assume someDate is one day after DST switch.
someDate.Sub(7 * 24 * time.Hour) != someDate.AddDate(0, 0, -7)
```

Fix a test broken by DST switch

---

api/README.md
api/manifest.go
webapp/components/wpt-results.js

Otherwise, it's computationally expensive to find a test path (we have to iterate the whole manifest and look up the `manifest.items[type][file][0]` entry).
Fixes #1208

Rearrange manifest to be test-path centric

---

api/receiver/receive_results.go

Azure is now producing much larger artifacts because of the screenshots, so we need to increase the download timeout a bit to accommodate that.

Give a longer timeout to download artifacts

---

api/receiver/api.go
api/receiver/api_medium_test.go
api/receiver/create_run.go
api/receiver/create_run_test.go
api/receiver/mock_receiver/api_mock.go
api/receiver/receive_results.go
api/receiver/receive_results_test.go
api/screenshot/cache.go
results-processor/processor.py
results-processor/wptreport.py
results-processor/wptscreenshot.py

Export an authentication function from the receiver package and use it in the screenshot package to guard the private API.
The branch is based on #1222 .

Protect the screenshot upload API

---

results-processor/processor.py

The bug was introduced in the big refactoring 2b9bd292 by accident.
@foolip TBR to fix a critical issue. I'll follow up with some tests later.

fixup! Wrong URL was passed to create test runs

---

webapp/components/reftest-analyzer.js

Fixes #1225 
SVG2 requires CSS to be supported for this, but it hasn't historically been supported, and isn't in Firefox, so let's not rely on that.

Fix #1225 - set SVG rect width through attribute rather than CSS

---

.travis.yml
Makefile
results-processor/Dockerfile
results-processor/README.md
results-processor/tox.ini

Nothing is changed except our test setup.
Unfortunately, the dev Docker image we use does not have Python 3.6 (it's running Debian stretch). Instead of using debports etc. to get Python 3.6 into stretch, I changed the Travis configuration for the `python_test` target to run tests outside of Docker using Travis' native Python support.

[processor] Upgrade to Python 3.6

---

results-processor/processor.py
results-processor/processor_test.py

Sometimes the runner might provide a, for example, screenshot_url that
does not exist (404), in which case we should not throw, but log an
error instead.

[processor] Do not throw when downloading fails

---

webapp/components/reftest-analyzer.js

1. Show the pixel position & RGB values of the current position (#1228).
2. Mask same pixels even more to highlight the border of the different areas.
Demo: https://reftest-analyzer2-dot-wptdashboard-staging.appspot.com/analyzer?screenshot=sha1%3A8cfce4c0c8e873c12e613a94e53c8c0a8e44eb3e&screenshot=sha1%3Ac8fbf3067a700b1916632ec1eed6c379a7113efd

Improve reftest analyzer

---

webapp/components/wpt-flags.js

`processTaskclusterCheckRunEvents` was missing.
Change the ordering and indentation of the flags to better reflect their
dependencies.
* https://rejig-flags-dot-wptdashboard-staging.appspot.com/flags
* https://rejig-flags-dot-wptdashboard-staging.appspot.com/admin/flags

Add a missing flag and rejig the positions

---

results-processor/processor.py
results-processor/processor_test.py
results-processor/test_server.py

1. Enforce a timeout when issuing HTTP requests (the default is no
timeout, which is not good).
2. When a HTTP error occurs (timeout or unsuccessful status), we wait 1
second and retry again.
3. If no results are downloaded successfully, we abort early.

[processor] Handle HTTP errors better

---

webapp/components/reftest-analyzer.js

In the reftest comparison, "Image before" and "Image after" are very unclear to the user. I changed them to the much clearer - "Actual" and "Expected".
https://wpt.fyi/results/css/css-position/position-relative-table-tbody-left-absolute-child.html?run_id=5668853719760896&run_id=5640982771007488&run_id=5907019957534720&run_id=6231803673182208 would do.
webapp/components/reftest-analyzer.js - renamed labels.
None.

Made the reftest comparison wording clearer

---

results-processor/wptreport.py

This only affects the main entry point of wptreport for more convenience
(i.e. when using wptreport directly from command line).

Tweak wptreport to accept multiple reports

---

webapp/components/reftest-analyzer.js
webapp/package-lock.json
webapp/package.json

#1250 missed another pair of confusing "before"/"after". This PR fixes that. In addition, two more paragraphs of docs are added (one under the zoomed-in view and the other in the tooltip of "highlight diff").
Travis is broken due to #1254 . I've manually deployed the staging instance:
https://reftest-analyzer-dot-wptdashboard-staging.appspot.com/analyzer?screenshot=sha1%3Afcb424b57a939b8fd40803a3a57591fe41bbc25d&screenshot=sha1%3A6ab8cb76ce84ebd802d2e2c7476334652df3d0fe

Further improve the docs for reftest analyzer

---

api/azure/api_test.go
api/query/cache/backfill/backfill.go
api/query/cache/index/filter.go
api/query/cache/index/index.go
api/query/cache/service/main.go
shared/util.go

Fixes #1254
My fork includes the fix that hasn't been merged upstream: https://github.com/Hexcles/logrus/commit/a0dcfa32eb0aa18d477bfe11a13b29d516085798

Use a forked logrus to fix AppEngine build
